apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  settings.yaml: |
    title: Rubiconetic Home Lab
    theme: dark
    color: slate
    layout:
      Infrastructure:
        style: row
        columns: 2

  # Using Magic DNS for links (TailScale)
  services.yaml: |
    - Automation:
        - n8n:
            icon: n8n.png
            href: "{{HOMEPAGE_VAR_N8N_URL}}"
            description: "Workflow Automation"
            # ping: "http://n8n-service:5678/healthz"

    - Infrastructure:
        - CloudBeaver:
            icon: dbeaver.png
            href: "http://wtc2.robin-mine.ts.net:8978"
            description: "Database Manager"
            # ping: "http://cloudbeaver-service:8978"
            
        - Longhorn:
            icon: longhorn.png
            href: "http://wtc2.robin-mine.ts.net:9999" 
            description: "Storage Manager"
        - VaultWarden:
            icon: vaultwarden.png
            href: "{{HOMEPAGE_VAR_VAULTWARDEN_URL}}"
            description: "Password Manager"
            # ping: "http://vaultwarden-service"

  # (Standard boilerplate to keep it from crashing)
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
  kubernetes.yaml: |
    []
  docker.yaml: |
    []
  proxmox.yaml: |
    []
  unifi.yaml: |
    []
  glances.yaml: |
    []
  plex.yaml: |
    []
  jellyfin.yaml: |
    []
  tautulli.yaml: |
    []
  sabnzbd.yaml: |
    []
  radarr.yaml: |
    []
  sonarr.yaml: |
    []
  bookmarks.yaml: |
    []
  custom.css: |
    /* Custom CSS */
  custom.js: |
    /* Custom JS */