apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  settings.yaml: |
    title: Rubiconetic Home Lab
    theme: dark
    color: slate
    layout:
      Infrastructure:
        style: row
        columns: 2

  # Homepage Links
  services.yaml: |
    - Automation:
        - n8n:
            icon: n8n.png
            href: "{{HOMEPAGE_VAR_N8N_URL}}"
            description: "Workflow Automation"
            # ping: "http://n8n-service:5678/healthz"

    - Infrastructure:
        - pgweb:
            icon: postgresql.png
            href: "http://wtc2.robin-mine.ts.net:8081"
            description: "Postgres Explorer"
        - Longhorn:
            icon: longhorn.png
            href: "http://wtc2.robin-mine.ts.net:9999" 
            description: "Storage Manager"
        - VaultWarden:
            icon: vaultwarden.png
            href: "{{HOMEPAGE_VAR_VAULTWARDEN_URL}}"
            description: "Password Manager"
            # ping: "http://vaultwarden-service:8080"
        - CouchDB:
            icon: couchdb.png
            href: "{{HOMEPAGE_VAR_COUCHDB_URL}}"
            description: "Obsidian-Sync Server"
            # ping: "http://obsidian-sync-service:5984"
    - Monitoring:
        - Grafana:
            icon: grafana.png
            href: "http://wtc2.robin-mine.ts.net:8084"
            description: "Metrics Dashboard"
            # ping: "http://grafana-service:8084/api/health"
        - Prometheus:
            icon: prometheus.png
            href: "http://wtc2.robin-mine.ts.net:9090"
            description: "Metrics Collection"
            # ping: "http://prometheus-service:9090/-/ready"
    - Media:
        - Torrenter:
            icon: https://raw.githubusercontent.com/michaelrubi/torrenter/main/src/lib/assets/favicon.svg
            href: "http://wtc2.robin-mine.ts.net:4173"
            description: "Torrent Manager"
            # ping: "http://torrenter-service:4173"
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
  kubernetes.yaml: |
    []
  docker.yaml: |
    []
  proxmox.yaml: |
    []
  unifi.yaml: |
    []
  glances.yaml: |
    []
  plex.yaml: |
    []
  jellyfin.yaml: |
    []
  tautulli.yaml: |
    []
  sabnzbd.yaml: |
    []
  radarr.yaml: |
    []
  sonarr.yaml: |
    []
  bookmarks.yaml: |
    []
  custom.css: |
    /* Custom CSS */
  custom.js: |
    /* Custom JS */