apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: default
spec:
  interval: 1h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: reloader
      version: "1.0.x"
      sourceRef:
        kind: HelmRepository
        name: stakater
      interval: 10m
  values:
    reloader:
      # efficient watching of secrets
      watchGlobally: true