apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:oLIx,iv:ITBCAonjRuxj6jr789tavsAwmMqtTp0oJhUaUDJ1WoY=,tag:fnNaAfidOWY6GQ+Pb0mWIQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:pO9062YBcy86JsVIKF/S/hILybecvA==,iv:EdqD3d8duTm4y17uUjae4QMvorDCCkY7uN82bLlSEw4=,tag:sWbMK925Axjm6p9FzoX6Zg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:qR4Z,iv:xK9i1OkC4HPtL1dUMSagp4j8KjJ10SApMWLYnHIZ53Q=,tag:E3lKHlEudgDwOmtZIrsWpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQjBnODNDNTBSS3ZTMXdL
            bHEzVjU3V2JkUkVXbDNzMHNkZVlhdDEvZGh3CmkvdUlib2RiWDNyOEFKZjF4RHRK
            R3dTL1Z1eUZJV1paVnIyYVlKZWs0OW8KLS0tIEMrTDdYZHlCQy9IMEhJNEZRSXVY
            MmFHVGV0eU9MdEhzMkNUYVd6MFhTVFkKKqlPikU/w4nvQ5h9mQIqoqmV/itNhEFJ
            NON4UCRnc3eXeIb4E9iQHMbEN9FQqARpsYJeMz0ZX5LVukuzyfQJBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:15:51Z"
    mac: ENC[AES256_GCM,data:Ylcshm+QR2Icdl9xgWX/L4StoCd8lC4gpYqR3lKvi0oUJ7PwrUqikFRB1TjTt1VvvX2ZJlmL9n2v1fTMbO5aNmwLk8jNWkzEqpP6BGjPU1x8CuuDUe7BIqyTKVBxLLUjg6A7aGbpgHzt2vk1oKDtlC8OdCfxSz5w0lffTpEmsBQ=,iv:r5sRWnLYxeO1JPODrJpCyyHeC2VkKzXXF/5RI6updPI=,tag:B8QRqwauXYPDA6Hej7OjbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:kdTQy/W/rqonu49cQTqgV06sZCpQK1X73MDbj2XXtuw=,iv:0K4HtbEFqyMhKQ05cWO6aCSPqGXyHzh4FYOflKljFfs=,tag:4fFMCArsw0dUJ5uC9WdVsA==,type:str]
    N8N_URL: ENC[AES256_GCM,data:eXznvZHPPjXwfAW/zFOtrmQJMXQxBKvHHKOzEQ==,iv:JLpCzNkA1IDX7nnCXqwdBxLXA/qYGegwTAhC98fw5XA=,tag:bdNi/00WTYAow1TzIwe+RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQjBnODNDNTBSS3ZTMXdL
            bHEzVjU3V2JkUkVXbDNzMHNkZVlhdDEvZGh3CmkvdUlib2RiWDNyOEFKZjF4RHRK
            R3dTL1Z1eUZJV1paVnIyYVlKZWs0OW8KLS0tIEMrTDdYZHlCQy9IMEhJNEZRSXVY
            MmFHVGV0eU9MdEhzMkNUYVd6MFhTVFkKKqlPikU/w4nvQ5h9mQIqoqmV/itNhEFJ
            NON4UCRnc3eXeIb4E9iQHMbEN9FQqARpsYJeMz0ZX5LVukuzyfQJBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:15:51Z"
    mac: ENC[AES256_GCM,data:Ylcshm+QR2Icdl9xgWX/L4StoCd8lC4gpYqR3lKvi0oUJ7PwrUqikFRB1TjTt1VvvX2ZJlmL9n2v1fTMbO5aNmwLk8jNWkzEqpP6BGjPU1x8CuuDUe7BIqyTKVBxLLUjg6A7aGbpgHzt2vk1oKDtlC8OdCfxSz5w0lffTpEmsBQ=,iv:r5sRWnLYxeO1JPODrJpCyyHeC2VkKzXXF/5RI6updPI=,tag:B8QRqwauXYPDA6Hej7OjbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:1s8Ic+FNAa40w7zXxgYm+kyNQ3+l7YjXfW87XgP3CB3h61LK2fJUNCIxPiPSh5fRoMKA+H0IxeGqNAia5oHzvpjMudCcAwaqvP1JdDQak3Qu163Lq+Ql8xkv37A93Fi5HozSqIslqfQ//I8ot786dWxZ3TYwh9bmgWJr03iDcJaflpH0i7omQPARxdMvgF62fLaQRmVhC92G7/J2b5Cah5Jp9qbJFKUt9Vc2DK4nhAVvQ0f96qv/YQ==,iv:3SjhOAW9+ThugagTBDcD8gVumwHdDNVe91aGZoTxTVw=,tag:U7kFM/xqx1Ybe3wZCO1tSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQjBnODNDNTBSS3ZTMXdL
            bHEzVjU3V2JkUkVXbDNzMHNkZVlhdDEvZGh3CmkvdUlib2RiWDNyOEFKZjF4RHRK
            R3dTL1Z1eUZJV1paVnIyYVlKZWs0OW8KLS0tIEMrTDdYZHlCQy9IMEhJNEZRSXVY
            MmFHVGV0eU9MdEhzMkNUYVd6MFhTVFkKKqlPikU/w4nvQ5h9mQIqoqmV/itNhEFJ
            NON4UCRnc3eXeIb4E9iQHMbEN9FQqARpsYJeMz0ZX5LVukuzyfQJBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:15:51Z"
    mac: ENC[AES256_GCM,data:Ylcshm+QR2Icdl9xgWX/L4StoCd8lC4gpYqR3lKvi0oUJ7PwrUqikFRB1TjTt1VvvX2ZJlmL9n2v1fTMbO5aNmwLk8jNWkzEqpP6BGjPU1x8CuuDUe7BIqyTKVBxLLUjg6A7aGbpgHzt2vk1oKDtlC8OdCfxSz5w0lffTpEmsBQ=,iv:r5sRWnLYxeO1JPODrJpCyyHeC2VkKzXXF/5RI6updPI=,tag:B8QRqwauXYPDA6Hej7OjbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:QZLaBSJf7iooqHCooMeQTue7NbImDlSqiabmWxAsf3AjYw==,iv:uOa41b646DJH0X0qp6weLDklxTNAEtXZr6Ri9qYBA4I=,tag:DdE09EZZIceJ4OcQBnZW9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQjBnODNDNTBSS3ZTMXdL
            bHEzVjU3V2JkUkVXbDNzMHNkZVlhdDEvZGh3CmkvdUlib2RiWDNyOEFKZjF4RHRK
            R3dTL1Z1eUZJV1paVnIyYVlKZWs0OW8KLS0tIEMrTDdYZHlCQy9IMEhJNEZRSXVY
            MmFHVGV0eU9MdEhzMkNUYVd6MFhTVFkKKqlPikU/w4nvQ5h9mQIqoqmV/itNhEFJ
            NON4UCRnc3eXeIb4E9iQHMbEN9FQqARpsYJeMz0ZX5LVukuzyfQJBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:15:51Z"
    mac: ENC[AES256_GCM,data:Ylcshm+QR2Icdl9xgWX/L4StoCd8lC4gpYqR3lKvi0oUJ7PwrUqikFRB1TjTt1VvvX2ZJlmL9n2v1fTMbO5aNmwLk8jNWkzEqpP6BGjPU1x8CuuDUe7BIqyTKVBxLLUjg6A7aGbpgHzt2vk1oKDtlC8OdCfxSz5w0lffTpEmsBQ=,iv:r5sRWnLYxeO1JPODrJpCyyHeC2VkKzXXF/5RI6updPI=,tag:B8QRqwauXYPDA6Hej7OjbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:I7PtcjN2AU2V9ChmObxJWMU4n+uPqLE8+ZO0,iv:ECsK5EtoKKw2kNoPzdduuHcGEByZvcx6l55+cxZxTTc=,tag:rx0Fxl7NnP7UD0bQGBsijg==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:qPR7R0JZvUcRcD98+HeMYycjegOXBHdN9fjlWnFzqAs=,iv:t/2jq+bihvZxOCqs61fNINyhMepdcuuIv1i5d16cPAo=,tag:VIaKEbrJ5E9LDEY2lVwJpQ==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:azFIsthx4h5spddeapGA5BUbHScjOoXRt2drsr3QrYo=,iv:HTfVibyDEDcBTNaXR3IzStNDmf9mjb/pS+ovsS8ur8Y=,tag:HtDFmcyh5QZDfsf7k+U6qg==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:cHShRv3eUfcj3Whwg2ZtU4h6om16uGmLd8hxQ892EyydpgNpi1QShR5Hw0yxPlWo6dPzntAbj7emtd0pnSwfmJLKvQAKPUE2d0IDb7BWZiGqad6K6iIv5/Kw7PHJHViaeBQ3G/6NtBqvYOloSn1v/05YXr/JwO2nbDi/rFuw9bHFbTZfVeW+fsNip+2JYXVzyMarDqozYZSDgiHpU9oLUeAEx0gm85DD64KW5XBpRnT9eXyd1xFtYWjOJrf0TfBFMqFCe+7rSomY1wCfbbwG+/M4r2FEXYQbZL+Rf6x2l0dYTh4ZhzQwKVj5vv0J,iv:8H1/azUadcJlnE1NBU04gxxvYFvY2TffEid0quPdS0E=,tag:h3kQLj1/ZQWNifFzuKqgbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQjBnODNDNTBSS3ZTMXdL
            bHEzVjU3V2JkUkVXbDNzMHNkZVlhdDEvZGh3CmkvdUlib2RiWDNyOEFKZjF4RHRK
            R3dTL1Z1eUZJV1paVnIyYVlKZWs0OW8KLS0tIEMrTDdYZHlCQy9IMEhJNEZRSXVY
            MmFHVGV0eU9MdEhzMkNUYVd6MFhTVFkKKqlPikU/w4nvQ5h9mQIqoqmV/itNhEFJ
            NON4UCRnc3eXeIb4E9iQHMbEN9FQqARpsYJeMz0ZX5LVukuzyfQJBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:15:51Z"
    mac: ENC[AES256_GCM,data:Ylcshm+QR2Icdl9xgWX/L4StoCd8lC4gpYqR3lKvi0oUJ7PwrUqikFRB1TjTt1VvvX2ZJlmL9n2v1fTMbO5aNmwLk8jNWkzEqpP6BGjPU1x8CuuDUe7BIqyTKVBxLLUjg6A7aGbpgHzt2vk1oKDtlC8OdCfxSz5w0lffTpEmsBQ=,iv:r5sRWnLYxeO1JPODrJpCyyHeC2VkKzXXF/5RI6updPI=,tag:B8QRqwauXYPDA6Hej7OjbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:osPCeiWq2g==,iv:b+t94bZE6gTXFrM0TRl7GMr+DMQM8pc/miM5S59nmHk=,tag:3nxmsBDF+5btTySEyTSPkw==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:zBnwwlsGAKpvw6j18AIoikV2V78=,iv:YYc4pp1iMVcjc18+T8ZaAtfjSkyo/iAfxKZtoMpmUyg=,tag:ND3n72r4u6IeYkjxWZU9lw==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:ppys97O+OONCUJECVhmbVsJp6RrP5a/073Llok070e5QY9Ixnw==,iv:z90yTdgo52ymN4tOTZBctxjQRFJ+S2WmiXkpKoiQWnY=,tag:1ouzlPbL073vb8QO//NPLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQjBnODNDNTBSS3ZTMXdL
            bHEzVjU3V2JkUkVXbDNzMHNkZVlhdDEvZGh3CmkvdUlib2RiWDNyOEFKZjF4RHRK
            R3dTL1Z1eUZJV1paVnIyYVlKZWs0OW8KLS0tIEMrTDdYZHlCQy9IMEhJNEZRSXVY
            MmFHVGV0eU9MdEhzMkNUYVd6MFhTVFkKKqlPikU/w4nvQ5h9mQIqoqmV/itNhEFJ
            NON4UCRnc3eXeIb4E9iQHMbEN9FQqARpsYJeMz0ZX5LVukuzyfQJBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:15:51Z"
    mac: ENC[AES256_GCM,data:Ylcshm+QR2Icdl9xgWX/L4StoCd8lC4gpYqR3lKvi0oUJ7PwrUqikFRB1TjTt1VvvX2ZJlmL9n2v1fTMbO5aNmwLk8jNWkzEqpP6BGjPU1x8CuuDUe7BIqyTKVBxLLUjg6A7aGbpgHzt2vk1oKDtlC8OdCfxSz5w0lffTpEmsBQ=,iv:r5sRWnLYxeO1JPODrJpCyyHeC2VkKzXXF/5RI6updPI=,tag:B8QRqwauXYPDA6Hej7OjbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: freescout-secrets
    namespace: default
type: Opaque
stringData:
    FREESCOUT_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:2QvGLHZBirddmc1DaYVcM4AsfPk=,iv:0vf9K31SoBCRs/gGgm7SSinGPOTpR1qyJlW7rC52+1E=,tag:KdofCTQkbsVAJGHChu3qEw==,type:str]
    FREESCOUT_DB_PASSWORD: ENC[AES256_GCM,data:mmvgiSPDeQRKTH9hB+fHMJlxuYw=,iv:UMcTeEhhdp1N2i599PFAO1kgXVAOr9kRjyHERPba4BQ=,tag:ELEhfSpbpcG0Gu0du1zS+g==,type:str]
    FREESCOUT_ADMIN_EMAIL: ENC[AES256_GCM,data:nuyMIooX2tnlc5nj2aNgCzXyo4gL+0g=,iv:EIFw7444w8+QsSHLYM52Z9ml/pjh36QgSo7VgHphdTQ=,tag:ItxFyfNzw23AdL5MSp/eqw==,type:str]
    FREESCOUT_ADMIN_PASSWORD: ENC[AES256_GCM,data:3Bi69GRGoGvzkV/v6xz2PcC9xnI=,iv:ojMuFhGC51ofe3aYdj9Mr9j7xL4ScjJ8CsxXo4nXJ/M=,tag:UYBpNe6gUPFE0hPEkx0TBA==,type:str]
    FREESCOUT_SITE_URL: ENC[AES256_GCM,data:8dqZeANThYQLeIfGYgZCSMNmZWqdY2lgOnhHlg==,iv:qggJkAtpRtxiEZPpFNjIJfAbVJzaxb54aMU7j5L7jp4=,tag:FOdVSP8MgyVYjyudY2f0Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQjBnODNDNTBSS3ZTMXdL
            bHEzVjU3V2JkUkVXbDNzMHNkZVlhdDEvZGh3CmkvdUlib2RiWDNyOEFKZjF4RHRK
            R3dTL1Z1eUZJV1paVnIyYVlKZWs0OW8KLS0tIEMrTDdYZHlCQy9IMEhJNEZRSXVY
            MmFHVGV0eU9MdEhzMkNUYVd6MFhTVFkKKqlPikU/w4nvQ5h9mQIqoqmV/itNhEFJ
            NON4UCRnc3eXeIb4E9iQHMbEN9FQqARpsYJeMz0ZX5LVukuzyfQJBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:15:51Z"
    mac: ENC[AES256_GCM,data:Ylcshm+QR2Icdl9xgWX/L4StoCd8lC4gpYqR3lKvi0oUJ7PwrUqikFRB1TjTt1VvvX2ZJlmL9n2v1fTMbO5aNmwLk8jNWkzEqpP6BGjPU1x8CuuDUe7BIqyTKVBxLLUjg6A7aGbpgHzt2vk1oKDtlC8OdCfxSz5w0lffTpEmsBQ=,iv:r5sRWnLYxeO1JPODrJpCyyHeC2VkKzXXF/5RI6updPI=,tag:B8QRqwauXYPDA6Hej7OjbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:3FuWT3PC5rVYCYnkok3GjVhMDy8fpCt31Jggs1lOUupwprJnvlq8Clcef5U=,iv:kLY+xSpJfcxNVQBejfSzZXgf3iyWq+Xn3qvAP2BOHS8=,tag:iMICmNhAhDfAvniqZF2kDA==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:HngMQcZf20am2f1xrM5IiRkZCNgn0O7RUffj,iv:dziGZuyeDdrBfGuUNomNyocgMzEIrJSW7kPJgp3rZXE=,tag:MfQuxHF2BN0XZwdhfZBQ2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQjBnODNDNTBSS3ZTMXdL
            bHEzVjU3V2JkUkVXbDNzMHNkZVlhdDEvZGh3CmkvdUlib2RiWDNyOEFKZjF4RHRK
            R3dTL1Z1eUZJV1paVnIyYVlKZWs0OW8KLS0tIEMrTDdYZHlCQy9IMEhJNEZRSXVY
            MmFHVGV0eU9MdEhzMkNUYVd6MFhTVFkKKqlPikU/w4nvQ5h9mQIqoqmV/itNhEFJ
            NON4UCRnc3eXeIb4E9iQHMbEN9FQqARpsYJeMz0ZX5LVukuzyfQJBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:15:51Z"
    mac: ENC[AES256_GCM,data:Ylcshm+QR2Icdl9xgWX/L4StoCd8lC4gpYqR3lKvi0oUJ7PwrUqikFRB1TjTt1VvvX2ZJlmL9n2v1fTMbO5aNmwLk8jNWkzEqpP6BGjPU1x8CuuDUe7BIqyTKVBxLLUjg6A7aGbpgHzt2vk1oKDtlC8OdCfxSz5w0lffTpEmsBQ=,iv:r5sRWnLYxeO1JPODrJpCyyHeC2VkKzXXF/5RI6updPI=,tag:B8QRqwauXYPDA6Hej7OjbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
