apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:osjt,iv:DpOBtdHcC358uPOv63KD68GFCkA9piZUYZ2zzNBf1Uk=,tag:AXyb2E/Y0fAThp2472phag==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:I3jrCYcwiv+p8tWR9P2Q3APpMhSjhA==,iv:KmOnSLi1mzBPVwLdjIv8zB576wnnMx7xWkXFiTKMoko=,tag:hPnLbsQsCM1/FwKQCRU5NQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:e9ac,iv:S+dw82NJj8SKLyEsJS2shr9zwzIi8OmPN1sEj05w3Lc=,tag:cVpveUrpCi5ECQWNEOyQ4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjBwU1dtWEhDYnpMK2o1
            bS93YkRDMUkwV2V2NXFhUjVLcWoxZzR6NlhjClRYOTA2L3lJblY5Y2VLbHFPbWNF
            dFNBaVcyYWpHV3hzY0VFT3lEa2c2Q2cKLS0tIE5kcVFYaGFTWXNZZjlOQlBQZTR6
            Wjk0VzViZDdoWnhneWxZTHFNdU5zRHcKuyamAw8SvvRF7dhc+Pi+lvPfMh6NBi9h
            t4HWqRCmzuEUBhfLdICzvCL2USI8v0dcUjIdoDvuikuo+pWV7hegTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:33:55Z"
    mac: ENC[AES256_GCM,data:EI5FmfZ8VHAoDvPhN7sMMBn2SWWRAC6Pu5swMLVSG363rPypubBPpnm/hnRd911rEueFoy44YhBG5+C8EssH0YZwhsrW4DwthI2oWpHwI/P/BiGaIHG/jUQOuFLaqdqbA5fdYw4MncskSH3L3rswl70sV6wiTTUhd59J8WA5ioE=,iv:tINLWw5uZ1bQz8dITeMNW/dZnGBRUSfyH5+xXQ6tM3s=,tag:PEaenzyFfaufsBmqE+eNbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:CNI7KdxOXZpMKoZ0uPkIZ64Pt3TTn5y+tn5ir9oZoXc=,iv:FM8NN57cPBzbP+czcaXXu/o0R6AaWWOymtDRzLeUOO0=,tag:Vqzz/r/bwWcee59fPRvBng==,type:str]
    N8N_URL: ENC[AES256_GCM,data:BAV1bxuXrugngl93Z3ajN7u4LxqXfdoyEpStKw==,iv:YTvE5KxHr2BpuZWh7F5oRHNzd8DbK9hZDGR8VDYuB7M=,tag:mL0jXRW9PpPqCT8K1ndHqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjBwU1dtWEhDYnpMK2o1
            bS93YkRDMUkwV2V2NXFhUjVLcWoxZzR6NlhjClRYOTA2L3lJblY5Y2VLbHFPbWNF
            dFNBaVcyYWpHV3hzY0VFT3lEa2c2Q2cKLS0tIE5kcVFYaGFTWXNZZjlOQlBQZTR6
            Wjk0VzViZDdoWnhneWxZTHFNdU5zRHcKuyamAw8SvvRF7dhc+Pi+lvPfMh6NBi9h
            t4HWqRCmzuEUBhfLdICzvCL2USI8v0dcUjIdoDvuikuo+pWV7hegTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:33:55Z"
    mac: ENC[AES256_GCM,data:EI5FmfZ8VHAoDvPhN7sMMBn2SWWRAC6Pu5swMLVSG363rPypubBPpnm/hnRd911rEueFoy44YhBG5+C8EssH0YZwhsrW4DwthI2oWpHwI/P/BiGaIHG/jUQOuFLaqdqbA5fdYw4MncskSH3L3rswl70sV6wiTTUhd59J8WA5ioE=,iv:tINLWw5uZ1bQz8dITeMNW/dZnGBRUSfyH5+xXQ6tM3s=,tag:PEaenzyFfaufsBmqE+eNbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:C46LGHbUNN/TAKW9fPo2HzycoxH5t6YO0FZ9mIkFe5WIMybNBpwssla1DlyD5oa9644tCLc3urWjlYjLkpA+/pEbvRVE8SEvA8PDo1iGEpYJdrMD1rKxi6MUw4UOOwP7hnnJ+224cWgu687sv41Pvji19FiC0N/RzUMaHqNbuRQIkBQNEdkt4/c/h/jolerJoWypm/OYYOapjPlKpeFVX0cx3rM26lcdpA/cWouS9lfCVvvNPlrxFw==,iv:GloUiR0yHj8aNT4DabFXDahGOnzKjzFnckTvYxDcg6E=,tag:/edZ5ZqCRM5akyCz0JRtlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjBwU1dtWEhDYnpMK2o1
            bS93YkRDMUkwV2V2NXFhUjVLcWoxZzR6NlhjClRYOTA2L3lJblY5Y2VLbHFPbWNF
            dFNBaVcyYWpHV3hzY0VFT3lEa2c2Q2cKLS0tIE5kcVFYaGFTWXNZZjlOQlBQZTR6
            Wjk0VzViZDdoWnhneWxZTHFNdU5zRHcKuyamAw8SvvRF7dhc+Pi+lvPfMh6NBi9h
            t4HWqRCmzuEUBhfLdICzvCL2USI8v0dcUjIdoDvuikuo+pWV7hegTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:33:55Z"
    mac: ENC[AES256_GCM,data:EI5FmfZ8VHAoDvPhN7sMMBn2SWWRAC6Pu5swMLVSG363rPypubBPpnm/hnRd911rEueFoy44YhBG5+C8EssH0YZwhsrW4DwthI2oWpHwI/P/BiGaIHG/jUQOuFLaqdqbA5fdYw4MncskSH3L3rswl70sV6wiTTUhd59J8WA5ioE=,iv:tINLWw5uZ1bQz8dITeMNW/dZnGBRUSfyH5+xXQ6tM3s=,tag:PEaenzyFfaufsBmqE+eNbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:qKLtfGPejftB3L1mQheV15j1ACRFtA25BuY8ED5BCj/SqA==,iv:smsyWAbrehzVClYu/t7qbamJXwUat8p5yvMCrvZkLUQ=,tag:KPS+Cxq0tMnBeP1uXA7D7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjBwU1dtWEhDYnpMK2o1
            bS93YkRDMUkwV2V2NXFhUjVLcWoxZzR6NlhjClRYOTA2L3lJblY5Y2VLbHFPbWNF
            dFNBaVcyYWpHV3hzY0VFT3lEa2c2Q2cKLS0tIE5kcVFYaGFTWXNZZjlOQlBQZTR6
            Wjk0VzViZDdoWnhneWxZTHFNdU5zRHcKuyamAw8SvvRF7dhc+Pi+lvPfMh6NBi9h
            t4HWqRCmzuEUBhfLdICzvCL2USI8v0dcUjIdoDvuikuo+pWV7hegTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:33:55Z"
    mac: ENC[AES256_GCM,data:EI5FmfZ8VHAoDvPhN7sMMBn2SWWRAC6Pu5swMLVSG363rPypubBPpnm/hnRd911rEueFoy44YhBG5+C8EssH0YZwhsrW4DwthI2oWpHwI/P/BiGaIHG/jUQOuFLaqdqbA5fdYw4MncskSH3L3rswl70sV6wiTTUhd59J8WA5ioE=,iv:tINLWw5uZ1bQz8dITeMNW/dZnGBRUSfyH5+xXQ6tM3s=,tag:PEaenzyFfaufsBmqE+eNbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:engk1jwkXd5RfXZY8i5os6y5HtagyBR2LPEl,iv:heZXIJ3J48L6Zu6CACHgn4BaZSmRNtms3/XVewH8v8c=,tag:3AaMuTV3qmRsWBhEDIkshA==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:Iixe1vH1LW5x6RgwtwkBc0iuzNUBR/6U/XwM6PpYqMA=,iv:lvIO49rCjueHRbuCJ02+5M/e/6k1m97ypb6aFDnaq9w=,tag:As/ydUZjHA2JyqIZm5ZDEQ==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:v7otbajnxxskhm/iT2KAmJi2jNvgCvYeTIX6A8DlNe4=,iv:Jv98wuFA9wIDfCRqGeXcWs9Z09PM1W6swLK3V76kksY=,tag:K1VzfIEP7X4nJnPTgA2NDA==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:VLNZN5LySV08toZptzxSHaoKDcGhqP3JmvAmQAW3stb2Xkpu16J3GMAJaNcsSxwMzehvoO81GAjGuN/ykCNYYhuPCnNS6rklZgiYkXA7VaUexybwYMcyrN5r2JbBXuVvhHg6H/I6is1fD6hX2b3ZXrGyhWEHICUM9NFHQOZXoGj3z5lawo398npKl3rpFMhH+5UivuS123Bsd4g7aqQ9v9/UJypHSte/xXZZ+M8FStWMMtcvANhUL4ORgjJMuD9p9ntnkPU9QVG9J7/hlwd8FD/RZTjxrj5yAzBglJKTodbradeYdSF2oGvP+6I7,iv:zUly915c6KPOwoJYYoyIoFqpWlDndAlbgOyt0YQwzVM=,tag:iGZzYf0m5cip+AzGmPcuFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjBwU1dtWEhDYnpMK2o1
            bS93YkRDMUkwV2V2NXFhUjVLcWoxZzR6NlhjClRYOTA2L3lJblY5Y2VLbHFPbWNF
            dFNBaVcyYWpHV3hzY0VFT3lEa2c2Q2cKLS0tIE5kcVFYaGFTWXNZZjlOQlBQZTR6
            Wjk0VzViZDdoWnhneWxZTHFNdU5zRHcKuyamAw8SvvRF7dhc+Pi+lvPfMh6NBi9h
            t4HWqRCmzuEUBhfLdICzvCL2USI8v0dcUjIdoDvuikuo+pWV7hegTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:33:55Z"
    mac: ENC[AES256_GCM,data:EI5FmfZ8VHAoDvPhN7sMMBn2SWWRAC6Pu5swMLVSG363rPypubBPpnm/hnRd911rEueFoy44YhBG5+C8EssH0YZwhsrW4DwthI2oWpHwI/P/BiGaIHG/jUQOuFLaqdqbA5fdYw4MncskSH3L3rswl70sV6wiTTUhd59J8WA5ioE=,iv:tINLWw5uZ1bQz8dITeMNW/dZnGBRUSfyH5+xXQ6tM3s=,tag:PEaenzyFfaufsBmqE+eNbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:rwUi/nAeKg==,iv:r1XLkus/EJLkh6UKxdUJW5+Kbc7uwiNjx+GjnM2dYlM=,tag:Ufr1GQiLORW/v1Yj7x9SDQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:GAYsPpKhqIuWiv8sUJFQGWbTegs=,iv:+mxo5h6R9TGUk58AjutwybZQA+stB1pzXP2xF66/pso=,tag:Wb0LzDB/dUqXchZz4GDGbg==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:MCldxk82PJ026Jh50ogYbcp6z4DzV1LrYlwA51Qqem+Xf5LESQ==,iv:e8pMJpNPUVVAzVM9ndmbliLP+1ObSfOzShQPl5bfzxo=,tag:WcK+P0Sr0MKzaMOFDxUE+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjBwU1dtWEhDYnpMK2o1
            bS93YkRDMUkwV2V2NXFhUjVLcWoxZzR6NlhjClRYOTA2L3lJblY5Y2VLbHFPbWNF
            dFNBaVcyYWpHV3hzY0VFT3lEa2c2Q2cKLS0tIE5kcVFYaGFTWXNZZjlOQlBQZTR6
            Wjk0VzViZDdoWnhneWxZTHFNdU5zRHcKuyamAw8SvvRF7dhc+Pi+lvPfMh6NBi9h
            t4HWqRCmzuEUBhfLdICzvCL2USI8v0dcUjIdoDvuikuo+pWV7hegTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:33:55Z"
    mac: ENC[AES256_GCM,data:EI5FmfZ8VHAoDvPhN7sMMBn2SWWRAC6Pu5swMLVSG363rPypubBPpnm/hnRd911rEueFoy44YhBG5+C8EssH0YZwhsrW4DwthI2oWpHwI/P/BiGaIHG/jUQOuFLaqdqbA5fdYw4MncskSH3L3rswl70sV6wiTTUhd59J8WA5ioE=,iv:tINLWw5uZ1bQz8dITeMNW/dZnGBRUSfyH5+xXQ6tM3s=,tag:PEaenzyFfaufsBmqE+eNbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:CNRnvsOGEqNYW9dmCKT35O4UxPMUAU0TlcsqUwj2AjrnQYa4Imv0OrEEnlQ=,iv:8jlykempjqa35UGhM3VTJInPFYr7fZd1+jGsuQURj2I=,tag:exlgSwUtdx/oitzEgeXSMA==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:9LlYGV2BQYaHZ6x04PDTXmbhoJuIxywLdH3K,iv:NwIut84vbZ5fXy3+lR6Eed3VE03p4AjshvGGqPXrvzg=,tag:cj2fitP9sAkOVyH4N/vtYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjBwU1dtWEhDYnpMK2o1
            bS93YkRDMUkwV2V2NXFhUjVLcWoxZzR6NlhjClRYOTA2L3lJblY5Y2VLbHFPbWNF
            dFNBaVcyYWpHV3hzY0VFT3lEa2c2Q2cKLS0tIE5kcVFYaGFTWXNZZjlOQlBQZTR6
            Wjk0VzViZDdoWnhneWxZTHFNdU5zRHcKuyamAw8SvvRF7dhc+Pi+lvPfMh6NBi9h
            t4HWqRCmzuEUBhfLdICzvCL2USI8v0dcUjIdoDvuikuo+pWV7hegTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:33:55Z"
    mac: ENC[AES256_GCM,data:EI5FmfZ8VHAoDvPhN7sMMBn2SWWRAC6Pu5swMLVSG363rPypubBPpnm/hnRd911rEueFoy44YhBG5+C8EssH0YZwhsrW4DwthI2oWpHwI/P/BiGaIHG/jUQOuFLaqdqbA5fdYw4MncskSH3L3rswl70sV6wiTTUhd59J8WA5ioE=,iv:tINLWw5uZ1bQz8dITeMNW/dZnGBRUSfyH5+xXQ6tM3s=,tag:PEaenzyFfaufsBmqE+eNbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: default
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:ppWN9xCAtp9/xPVxswfHGNYk4o0fRh2KdgdMje0jYyBOUNovSrKUig==,iv:DaB/pZT/K7JNcbNf0LFbVGl7ITc9wwfbvILmIOcSGhM=,tag:6uSq5dP1bMxooCPGOKcESg==,type:str]
    RENOVATE_GITHUB_TOKEN: ENC[AES256_GCM,data:Ix/rjedNPawIcPQKodMnXt4n1hlI9kfdl9dXCOSPoTats/yM0xWaHA==,iv:s/iHDsVO+p99b+xF82BmXl/GgGkP7lRyVujITbmwBXE=,tag:JTcZIwuPlpypI8H/CG5ADw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjBwU1dtWEhDYnpMK2o1
            bS93YkRDMUkwV2V2NXFhUjVLcWoxZzR6NlhjClRYOTA2L3lJblY5Y2VLbHFPbWNF
            dFNBaVcyYWpHV3hzY0VFT3lEa2c2Q2cKLS0tIE5kcVFYaGFTWXNZZjlOQlBQZTR6
            Wjk0VzViZDdoWnhneWxZTHFNdU5zRHcKuyamAw8SvvRF7dhc+Pi+lvPfMh6NBi9h
            t4HWqRCmzuEUBhfLdICzvCL2USI8v0dcUjIdoDvuikuo+pWV7hegTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:33:55Z"
    mac: ENC[AES256_GCM,data:EI5FmfZ8VHAoDvPhN7sMMBn2SWWRAC6Pu5swMLVSG363rPypubBPpnm/hnRd911rEueFoy44YhBG5+C8EssH0YZwhsrW4DwthI2oWpHwI/P/BiGaIHG/jUQOuFLaqdqbA5fdYw4MncskSH3L3rswl70sV6wiTTUhd59J8WA5ioE=,iv:tINLWw5uZ1bQz8dITeMNW/dZnGBRUSfyH5+xXQ6tM3s=,tag:PEaenzyFfaufsBmqE+eNbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-secrets
    namespace: default
type: Opaque
stringData:
    JELLYFIN_KEY: ENC[AES256_GCM,data:/E9i9h5TbC2l0gTT6I50S/pr8IjDP+m3jVadm9VIFA4=,iv:xqpd4oPeeC9iAT22JT2fKJG/rrJGTdXZjGBOGQ941VI=,tag:pE/hHBQVrdoOkM69UWgM6w==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:UWDiwEJnHFLzX8khx5gRWgGRu8najqo5mkU=,iv:y7+ju3oBgwrBOxR2IYeRtbtYP3wfVEr1PJVjcU4LeGk=,tag:sW0YjiRDx80CfZTfpXTM2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjBwU1dtWEhDYnpMK2o1
            bS93YkRDMUkwV2V2NXFhUjVLcWoxZzR6NlhjClRYOTA2L3lJblY5Y2VLbHFPbWNF
            dFNBaVcyYWpHV3hzY0VFT3lEa2c2Q2cKLS0tIE5kcVFYaGFTWXNZZjlOQlBQZTR6
            Wjk0VzViZDdoWnhneWxZTHFNdU5zRHcKuyamAw8SvvRF7dhc+Pi+lvPfMh6NBi9h
            t4HWqRCmzuEUBhfLdICzvCL2USI8v0dcUjIdoDvuikuo+pWV7hegTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:33:55Z"
    mac: ENC[AES256_GCM,data:EI5FmfZ8VHAoDvPhN7sMMBn2SWWRAC6Pu5swMLVSG363rPypubBPpnm/hnRd911rEueFoy44YhBG5+C8EssH0YZwhsrW4DwthI2oWpHwI/P/BiGaIHG/jUQOuFLaqdqbA5fdYw4MncskSH3L3rswl70sV6wiTTUhd59J8WA5ioE=,iv:tINLWw5uZ1bQz8dITeMNW/dZnGBRUSfyH5+xXQ6tM3s=,tag:PEaenzyFfaufsBmqE+eNbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-secrets
    namespace: default
type: Opaque
stringData:
    HA_TOKEN: ENC[AES256_GCM,data:7BaTTDNimtjn0nZFRTv95PGqP7iXGwTuU0qX6Q7fHcG2SrFQz7rtNRy1NTU997lh+hGBDqi+tHyo0+yispgLF8g3nfhUIFMsxQ6adilAkDmbSDSXAr8ivEEAa3Eh/xAR/4Gqh9Q71iGL5BPFV8jJbFuQMyaL5BvcWN3/ZO2SaGJUI0ii6I5Sz1CbPRjtJiXF+mELa3WhWrv1JFcp4SanNIAcgxCJ1D6+TtnE7f5WrImwVe//OPmW,iv:Fs0/1VpLKKguyjST/LECd5M4R0QQ8logitEQ7liPMc8=,tag:HBar/Gtf/aKJTQOr6VJ7Xw==,type:str]
    HA_IP: ENC[AES256_GCM,data:drw+cOgPxzf3WlnAulDsRDXJmXHEPwD6rgs=,iv:7HMfpujvugMrsWGZKaZlMNLC8ZiIbQM8nwR+jxZchz0=,tag:2XIkS+QEBLFyNUVRyZJ0zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjBwU1dtWEhDYnpMK2o1
            bS93YkRDMUkwV2V2NXFhUjVLcWoxZzR6NlhjClRYOTA2L3lJblY5Y2VLbHFPbWNF
            dFNBaVcyYWpHV3hzY0VFT3lEa2c2Q2cKLS0tIE5kcVFYaGFTWXNZZjlOQlBQZTR6
            Wjk0VzViZDdoWnhneWxZTHFNdU5zRHcKuyamAw8SvvRF7dhc+Pi+lvPfMh6NBi9h
            t4HWqRCmzuEUBhfLdICzvCL2USI8v0dcUjIdoDvuikuo+pWV7hegTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:33:55Z"
    mac: ENC[AES256_GCM,data:EI5FmfZ8VHAoDvPhN7sMMBn2SWWRAC6Pu5swMLVSG363rPypubBPpnm/hnRd911rEueFoy44YhBG5+C8EssH0YZwhsrW4DwthI2oWpHwI/P/BiGaIHG/jUQOuFLaqdqbA5fdYw4MncskSH3L3rswl70sV6wiTTUhd59J8WA5ioE=,iv:tINLWw5uZ1bQz8dITeMNW/dZnGBRUSfyH5+xXQ6tM3s=,tag:PEaenzyFfaufsBmqE+eNbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
