apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:3EZc,iv:hnLsSiXmMtUt63pZo+fE5FpRgOkMd28VZ8lPQiAIELE=,tag:hu+71XkbZIbk/GdfeeaW9g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:mh//sUpNHsVRXG7Zk4tJKY3PgJokIA==,iv:/Bf717/V7cR2b1ENyjnVEtFplq3/y8EGj+Py3vE7eLs=,tag:v8u7fwWj75t64Q3DTBUW3w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:8jt+,iv:FOgOpKEY8NC9SamW0dyHv4m5Ah/M+cPfzIG07GnvTQc=,tag:hkxIoJ3a483NL40ebCRefQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaDMzVEY3NVJ0OGdqRHZa
            TURyazZGaTRMbWlTUjl5VXFqTWNmZnJLMEhzCjZ0RG1OVVlRUGJteGM1MWEzcGJw
            Q0RhMlhhTkFLa1lsNlZ3dmtLaWUySVUKLS0tIExhQ3RtWFp2K2hUNlNDN2EreElu
            dUY4clJTM3FnSmkxWVlmU1NBUHBHTmcKh50Xc0BeikPJSTo+k/i8nEeclZWdIZit
            8YuHhNk3dgC6VZPPgPOfQBbaVRAEUwXiQYjBsCuZokRlkS6mTbo5bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:50Z"
    mac: ENC[AES256_GCM,data:5ZoWkqHk9tX9EOHALhRpRpqjiBp9ia1f0TSuutKM9Ehxl3+xPjz2qfdGsWBMWqn9IctJ5SB86ALGHoypv5xNL8adjPE2h9iM0nRPALsqnfPzm1pvHfd3U4AcyIY3lFAKdyjflbDu0ctLmYpNDrsDBca//+gN75qzdjz5afEr+N0=,iv:5PEL6X7C7WMG8Ef4MqcJiwTyW+lH2BlEykIT4MdgNOk=,tag:NWplAukBoJM8DABgAL16EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:be7vlR+hrs85ul+ydMesMaSrOFuiz5iFc30HarkhChM=,iv:mRWA6X+ROvb5uUcUUlq817AwJxPMJMq2nLOUb/EGtmc=,tag:uLWBpbRc/lYYjvQKClQg1w==,type:str]
    N8N_URL: ENC[AES256_GCM,data:1cS/0UA9JbHI6fi2nDu7gBtakpW5faq9CgOzBw==,iv:I1K6aLgGbcDw42UUcKMlBx1Sw9SuMpATlLXAI+F0CZY=,tag:rcEp9EkRzDaynHgvYmIk9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaDMzVEY3NVJ0OGdqRHZa
            TURyazZGaTRMbWlTUjl5VXFqTWNmZnJLMEhzCjZ0RG1OVVlRUGJteGM1MWEzcGJw
            Q0RhMlhhTkFLa1lsNlZ3dmtLaWUySVUKLS0tIExhQ3RtWFp2K2hUNlNDN2EreElu
            dUY4clJTM3FnSmkxWVlmU1NBUHBHTmcKh50Xc0BeikPJSTo+k/i8nEeclZWdIZit
            8YuHhNk3dgC6VZPPgPOfQBbaVRAEUwXiQYjBsCuZokRlkS6mTbo5bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:50Z"
    mac: ENC[AES256_GCM,data:5ZoWkqHk9tX9EOHALhRpRpqjiBp9ia1f0TSuutKM9Ehxl3+xPjz2qfdGsWBMWqn9IctJ5SB86ALGHoypv5xNL8adjPE2h9iM0nRPALsqnfPzm1pvHfd3U4AcyIY3lFAKdyjflbDu0ctLmYpNDrsDBca//+gN75qzdjz5afEr+N0=,iv:5PEL6X7C7WMG8Ef4MqcJiwTyW+lH2BlEykIT4MdgNOk=,tag:NWplAukBoJM8DABgAL16EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:q938McDAQ/WnbNAjcmQhKqjhmPpleUE1LS8w8Z3TI4ajDq2gf8auHkPLYeUj8r/rNM/+UAZBRuS6eeL2bRmQ976B6phM/V+uY5n5hQVZdj+lcLVOuzjCJq7LO9I3EsU0RKPnULR73teSFUbaBeoiByKsJeBBUfRat1oxVI+IdZaIeKMjxOCbEmLFPU59Y0hQMqvDtfzfxGYo01tDO+TmfP4yfJcM4cHYpc5Mzo9UkcY2wKEm8tUqPg==,iv:eKBaqoYMp4/jAvhzZ2nW3P9vopP3vci02o9lJfRm2RA=,tag:1CpR8qPN09iJD5fy/kBzIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaDMzVEY3NVJ0OGdqRHZa
            TURyazZGaTRMbWlTUjl5VXFqTWNmZnJLMEhzCjZ0RG1OVVlRUGJteGM1MWEzcGJw
            Q0RhMlhhTkFLa1lsNlZ3dmtLaWUySVUKLS0tIExhQ3RtWFp2K2hUNlNDN2EreElu
            dUY4clJTM3FnSmkxWVlmU1NBUHBHTmcKh50Xc0BeikPJSTo+k/i8nEeclZWdIZit
            8YuHhNk3dgC6VZPPgPOfQBbaVRAEUwXiQYjBsCuZokRlkS6mTbo5bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:50Z"
    mac: ENC[AES256_GCM,data:5ZoWkqHk9tX9EOHALhRpRpqjiBp9ia1f0TSuutKM9Ehxl3+xPjz2qfdGsWBMWqn9IctJ5SB86ALGHoypv5xNL8adjPE2h9iM0nRPALsqnfPzm1pvHfd3U4AcyIY3lFAKdyjflbDu0ctLmYpNDrsDBca//+gN75qzdjz5afEr+N0=,iv:5PEL6X7C7WMG8Ef4MqcJiwTyW+lH2BlEykIT4MdgNOk=,tag:NWplAukBoJM8DABgAL16EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:vGjN+EBfEJjEWWZA+50cT1N47WPjv/CTTl5tA7QKywgcZQ==,iv:uxznHboA0uRR2v99TR4XiobmXs3dA7cLW7p2ktKbK9A=,tag:ccXPxofbP58medLWFR+8IQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaDMzVEY3NVJ0OGdqRHZa
            TURyazZGaTRMbWlTUjl5VXFqTWNmZnJLMEhzCjZ0RG1OVVlRUGJteGM1MWEzcGJw
            Q0RhMlhhTkFLa1lsNlZ3dmtLaWUySVUKLS0tIExhQ3RtWFp2K2hUNlNDN2EreElu
            dUY4clJTM3FnSmkxWVlmU1NBUHBHTmcKh50Xc0BeikPJSTo+k/i8nEeclZWdIZit
            8YuHhNk3dgC6VZPPgPOfQBbaVRAEUwXiQYjBsCuZokRlkS6mTbo5bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:50Z"
    mac: ENC[AES256_GCM,data:5ZoWkqHk9tX9EOHALhRpRpqjiBp9ia1f0TSuutKM9Ehxl3+xPjz2qfdGsWBMWqn9IctJ5SB86ALGHoypv5xNL8adjPE2h9iM0nRPALsqnfPzm1pvHfd3U4AcyIY3lFAKdyjflbDu0ctLmYpNDrsDBca//+gN75qzdjz5afEr+N0=,iv:5PEL6X7C7WMG8Ef4MqcJiwTyW+lH2BlEykIT4MdgNOk=,tag:NWplAukBoJM8DABgAL16EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:9QmGF9iZIvJlyM594yuhzBSq6SV0t/Bt4mOF,iv:E1NNgUny+l4uXsvXSFfFTxAQvojlN5/KGzcFg9hZT2A=,tag:I9i5RzdDYaGnze2vchnzRQ==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:itOj4M3Ln0lDaMp1gOgdjC6+B/7N3PXkK3qU3wBvSiU=,iv:fuJ3Yp+SmrAiWuiE83pqYUfnmfqDTiDuIku25S3At6E=,tag:Zk1NZg6IwZFv48Rw6KTXMQ==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:R7Tg7c+aZSvx2C+izH3eVX7bkpjhZ5RlRmUqlSvSgvA=,iv:6MRe1RkjBJOH3oUvIaaBySoeGFoNbg8SaylhJFAHYm4=,tag:ZCAyYzgWVN2YQL47twGT/A==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:Z6XDhHmmMG7OGyptKybx0volPy/CddW7A4bjrEQRNJ1OUVKfeIBrlki1G9JE5v96UsDNe5gEEYOhlV5VkKeYGaDurA1qPtjB7jtN6/mN27vHMjVQW6ebsVpfpeULT8GqF0MJyJZz0quLMnygfM5o2b2t/VqQ80l36BUlu/Q0eGrO2X6snasJd0QqTVLeChd2lgwwjgcLlTfuMJKsxfQi29aPW/28AX5GF+RCQy8zP+i/M8mfTexdWQ5OW/0SEHDnyi/Qhz5N+IMjHaIl4zedd81iNx1S4U8vTiyBxsV/oj82y1pV4h8PrTrYOufY,iv:380GnU/GpcENM3KnTEOZNH9B/GRyPZd391V7hR2bIBs=,tag:RFpISf3i30QwWo/kF13NAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaDMzVEY3NVJ0OGdqRHZa
            TURyazZGaTRMbWlTUjl5VXFqTWNmZnJLMEhzCjZ0RG1OVVlRUGJteGM1MWEzcGJw
            Q0RhMlhhTkFLa1lsNlZ3dmtLaWUySVUKLS0tIExhQ3RtWFp2K2hUNlNDN2EreElu
            dUY4clJTM3FnSmkxWVlmU1NBUHBHTmcKh50Xc0BeikPJSTo+k/i8nEeclZWdIZit
            8YuHhNk3dgC6VZPPgPOfQBbaVRAEUwXiQYjBsCuZokRlkS6mTbo5bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:50Z"
    mac: ENC[AES256_GCM,data:5ZoWkqHk9tX9EOHALhRpRpqjiBp9ia1f0TSuutKM9Ehxl3+xPjz2qfdGsWBMWqn9IctJ5SB86ALGHoypv5xNL8adjPE2h9iM0nRPALsqnfPzm1pvHfd3U4AcyIY3lFAKdyjflbDu0ctLmYpNDrsDBca//+gN75qzdjz5afEr+N0=,iv:5PEL6X7C7WMG8Ef4MqcJiwTyW+lH2BlEykIT4MdgNOk=,tag:NWplAukBoJM8DABgAL16EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:3R8pMJIpKA==,iv:XBV4jdECUd2r5PeoF9wHdGTCPD/O/RaCGI/XWc0V4bo=,tag:Hkvs0ztDt9/JjU3yp0K7Vw==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:4LyAylESMEHRuC65nHovY7Croz8=,iv:xhrsOY9EXg6cRFFA5WnsdrvESfr2aXXlUu5cfnwaQUA=,tag:KZnDPUFF4CFmGtxEVLT7/w==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:qnndjLEzeF/m5KTooeKTd7B5WQdBM49WXGz5mLSijpW7OuUsEg==,iv:KmXqq6PKV99EJNsDWfRks3L4Tcsl1KE2MKrYqHYD1FI=,tag:groW6cA990tuTlBoB4AFnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaDMzVEY3NVJ0OGdqRHZa
            TURyazZGaTRMbWlTUjl5VXFqTWNmZnJLMEhzCjZ0RG1OVVlRUGJteGM1MWEzcGJw
            Q0RhMlhhTkFLa1lsNlZ3dmtLaWUySVUKLS0tIExhQ3RtWFp2K2hUNlNDN2EreElu
            dUY4clJTM3FnSmkxWVlmU1NBUHBHTmcKh50Xc0BeikPJSTo+k/i8nEeclZWdIZit
            8YuHhNk3dgC6VZPPgPOfQBbaVRAEUwXiQYjBsCuZokRlkS6mTbo5bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:50Z"
    mac: ENC[AES256_GCM,data:5ZoWkqHk9tX9EOHALhRpRpqjiBp9ia1f0TSuutKM9Ehxl3+xPjz2qfdGsWBMWqn9IctJ5SB86ALGHoypv5xNL8adjPE2h9iM0nRPALsqnfPzm1pvHfd3U4AcyIY3lFAKdyjflbDu0ctLmYpNDrsDBca//+gN75qzdjz5afEr+N0=,iv:5PEL6X7C7WMG8Ef4MqcJiwTyW+lH2BlEykIT4MdgNOk=,tag:NWplAukBoJM8DABgAL16EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: freescout-secrets
    namespace: default
type: Opaque
stringData:
    FREESCOUT_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:R2IpGE7TswqyHJWDK0c11h7WNS4=,iv:VQZ/iqzm5A6HaY3e+Vrt/g3w5s8l3vBjYNHQ/OILGZ0=,tag:pHKUL9K+k5f9s0LMj7A3Tw==,type:str]
    FREESCOUT_DB_PASSWORD: ENC[AES256_GCM,data:pQZPiblNI75LhpxSk1fg3dxMaeg=,iv:1+hT8NerW/i+tTUtTWNwVwkV9dweUDoGiXlXzWe7m0Y=,tag:mK69Veo+k3WcSHlwNyBY7A==,type:str]
    FREESCOUT_ADMIN_EMAIL: ENC[AES256_GCM,data:hkpeX0joTWqmSGmvymPbjeDoUbZfLKA=,iv:tsRiKS2v3bnndWlxi966J0qCf5l9DQoUuryZaHq5abQ=,tag:XFiboUwOZUh2Grr7g7CpWw==,type:str]
    FREESCOUT_ADMIN_PASSWORD: ENC[AES256_GCM,data:9O78u+Z1+U67R2jHEdjp8WGw4Wo=,iv:Oo2PIcNBtHHF2z1voeUScJJbNT2Lv8eTWKaVULcZcmo=,tag:2izc3AWh1Rbe3AMf9NNCwg==,type:str]
    FREESCOUT_SITE_URL: ENC[AES256_GCM,data:8tgysX4hTzgBCjtCisn9KMi36vIm9tSOImWyEA==,iv:BnrXyfDHG1OTXgRZbqLEfbFDqYaaO4yl7Aqr5wRfLT8=,tag:4khNiZ0I+O449Rlxm383cA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaDMzVEY3NVJ0OGdqRHZa
            TURyazZGaTRMbWlTUjl5VXFqTWNmZnJLMEhzCjZ0RG1OVVlRUGJteGM1MWEzcGJw
            Q0RhMlhhTkFLa1lsNlZ3dmtLaWUySVUKLS0tIExhQ3RtWFp2K2hUNlNDN2EreElu
            dUY4clJTM3FnSmkxWVlmU1NBUHBHTmcKh50Xc0BeikPJSTo+k/i8nEeclZWdIZit
            8YuHhNk3dgC6VZPPgPOfQBbaVRAEUwXiQYjBsCuZokRlkS6mTbo5bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:50Z"
    mac: ENC[AES256_GCM,data:5ZoWkqHk9tX9EOHALhRpRpqjiBp9ia1f0TSuutKM9Ehxl3+xPjz2qfdGsWBMWqn9IctJ5SB86ALGHoypv5xNL8adjPE2h9iM0nRPALsqnfPzm1pvHfd3U4AcyIY3lFAKdyjflbDu0ctLmYpNDrsDBca//+gN75qzdjz5afEr+N0=,iv:5PEL6X7C7WMG8Ef4MqcJiwTyW+lH2BlEykIT4MdgNOk=,tag:NWplAukBoJM8DABgAL16EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
