apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:IeOl,iv:ZDpltaDfxEx3UUo5gUQkBLQboeJAMgNIqnEwhO6fNa4=,tag:aQ/GEW6xzXaj/oJlzXJ/mw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:h9Au84tDToSK/mOC9LW9FVk+gjr2kg==,iv:XW6mj47ukEGUgMbhWK/NMkTgMRc0eBVeFIipbMaqurM=,tag:yotiAuUKw+BbJtNFqZPRbQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:gD91,iv:VGoOgB8Wt0D/3b5GrYRMNjQ7WnNn822WvFRUIa4tfL0=,tag:9eAnEEXAK4jAtQbxs0LmIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TklCRVpUTlQrTUJwamtG
            N2hKK1UxbGdpRzFkb05aLzIyT0w0Z3FLRnlZCks4TnMrcGtRWGhQKzhSMEdlckhh
            ZnY4U1pQazJiNEFQSFhNbHVlQnVuZ1UKLS0tIEg0K1NtSDc4RzQzZElSSGRYNTd0
            Z0cvSU9QUWZrYStlcjBBUlA3Sit3NjAKEglN547D8wvlpcIDhWb7+7+zMguM3aGP
            9gW5I4gG1Wf9JVctWMLmnZnHHe0DQsk11PYc/42tNUlvlbCljR2sTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T18:02:04Z"
    mac: ENC[AES256_GCM,data:oMqtCc2JjxP8U3wWltdzErPxmvx8L4wBX6UEM1nbmTnbRMlmCafzzzSBNqVs+DFn1HaUnq/qb0PwGp+D79hFS1QFlTvBSVd1N540ifNe3pH5Mw0wh7F/SpbhZQorGhkKitD9uMXGS/hcCpj13dD+54OVmhzzfMdZmqmbGpdl/hA=,iv:zeqJIQM4cF3HWdIA3qWgAZCGuYNVCr0oqkJDs0TCkvA=,tag:HGJWiDuntbMalA/ApTo1IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:Yd+4+UkM8GFXxkBF3bNTp0nyzfaOFhWNlW7UfJeLsRY=,iv:Q96yePaX4m76FE/kvp5Ps3iAoevOWnoHGgNtrAB7BT8=,tag:A0hWVBHiPYKBlpAHp728rw==,type:str]
    N8N_URL: ENC[AES256_GCM,data:5ybVJ7eet8WOwnAU13bwzuhzoxtF7i9QNU9+JQ==,iv:18+fJFH99z7zQSdYvQGE+nycdQuANzeCtnscru5fWgg=,tag:3Lybhj6dgbCkzVL/roqHFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TklCRVpUTlQrTUJwamtG
            N2hKK1UxbGdpRzFkb05aLzIyT0w0Z3FLRnlZCks4TnMrcGtRWGhQKzhSMEdlckhh
            ZnY4U1pQazJiNEFQSFhNbHVlQnVuZ1UKLS0tIEg0K1NtSDc4RzQzZElSSGRYNTd0
            Z0cvSU9QUWZrYStlcjBBUlA3Sit3NjAKEglN547D8wvlpcIDhWb7+7+zMguM3aGP
            9gW5I4gG1Wf9JVctWMLmnZnHHe0DQsk11PYc/42tNUlvlbCljR2sTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T18:02:04Z"
    mac: ENC[AES256_GCM,data:oMqtCc2JjxP8U3wWltdzErPxmvx8L4wBX6UEM1nbmTnbRMlmCafzzzSBNqVs+DFn1HaUnq/qb0PwGp+D79hFS1QFlTvBSVd1N540ifNe3pH5Mw0wh7F/SpbhZQorGhkKitD9uMXGS/hcCpj13dD+54OVmhzzfMdZmqmbGpdl/hA=,iv:zeqJIQM4cF3HWdIA3qWgAZCGuYNVCr0oqkJDs0TCkvA=,tag:HGJWiDuntbMalA/ApTo1IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:iUw98X+upEDHqDIdPDoUGRR4b3GMKNCTlJ6QyEhOCsbc4glf065ot8Hl1cGVH+xKPy6C2iefJZjKAkX9CsFRIa7MIMlR9uXPwGzvxxZWyk4NY/C/RHiBHqKjK23bXMdiILsoyW6VP9xUtJuvX2u0yWUxbjvvnfPo/dgN1LALjDFazvg1QZ45DflNhrGdo93d6b/tTFlV8BaMGfQKHUOQkFkbZJfC+pIlwHYdnQHxfvwClraecxTewQ==,iv:8R9t4gfygRIjki5thKfzEWoYgg0YJ3Dm4NWNKInBhe8=,tag:tBzOf5W2u9nw6PE5gKgtjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TklCRVpUTlQrTUJwamtG
            N2hKK1UxbGdpRzFkb05aLzIyT0w0Z3FLRnlZCks4TnMrcGtRWGhQKzhSMEdlckhh
            ZnY4U1pQazJiNEFQSFhNbHVlQnVuZ1UKLS0tIEg0K1NtSDc4RzQzZElSSGRYNTd0
            Z0cvSU9QUWZrYStlcjBBUlA3Sit3NjAKEglN547D8wvlpcIDhWb7+7+zMguM3aGP
            9gW5I4gG1Wf9JVctWMLmnZnHHe0DQsk11PYc/42tNUlvlbCljR2sTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T18:02:04Z"
    mac: ENC[AES256_GCM,data:oMqtCc2JjxP8U3wWltdzErPxmvx8L4wBX6UEM1nbmTnbRMlmCafzzzSBNqVs+DFn1HaUnq/qb0PwGp+D79hFS1QFlTvBSVd1N540ifNe3pH5Mw0wh7F/SpbhZQorGhkKitD9uMXGS/hcCpj13dD+54OVmhzzfMdZmqmbGpdl/hA=,iv:zeqJIQM4cF3HWdIA3qWgAZCGuYNVCr0oqkJDs0TCkvA=,tag:HGJWiDuntbMalA/ApTo1IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:NEyXuNtblLjYjIlMG02HvvFE73x+DFEzLAwMDnDAXCzy5Q==,iv:kQQmuS2n/crC2SJZsSg0pW43uZgSJlCXLVOrZMzfqEk=,tag:pBycgcYUr/41ZmzhGmvhcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TklCRVpUTlQrTUJwamtG
            N2hKK1UxbGdpRzFkb05aLzIyT0w0Z3FLRnlZCks4TnMrcGtRWGhQKzhSMEdlckhh
            ZnY4U1pQazJiNEFQSFhNbHVlQnVuZ1UKLS0tIEg0K1NtSDc4RzQzZElSSGRYNTd0
            Z0cvSU9QUWZrYStlcjBBUlA3Sit3NjAKEglN547D8wvlpcIDhWb7+7+zMguM3aGP
            9gW5I4gG1Wf9JVctWMLmnZnHHe0DQsk11PYc/42tNUlvlbCljR2sTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T18:02:04Z"
    mac: ENC[AES256_GCM,data:oMqtCc2JjxP8U3wWltdzErPxmvx8L4wBX6UEM1nbmTnbRMlmCafzzzSBNqVs+DFn1HaUnq/qb0PwGp+D79hFS1QFlTvBSVd1N540ifNe3pH5Mw0wh7F/SpbhZQorGhkKitD9uMXGS/hcCpj13dD+54OVmhzzfMdZmqmbGpdl/hA=,iv:zeqJIQM4cF3HWdIA3qWgAZCGuYNVCr0oqkJDs0TCkvA=,tag:HGJWiDuntbMalA/ApTo1IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:DMe/3l2niC2mFc0V1/a9eqxui5fEF5NC187R,iv:cASb1J9cuevADZ+li9u4XpYwdVbJwZyvQehbwiAd1os=,tag:ciWfplfu9nt1jp5MD8/gmw==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:rnjcON6vNVl1KxE/6MeJ/h1Armk2YyVPFIVJIgk+Zew=,iv:Y3Rcxo4cBqdLO7vJTm94Uxyu4hxvdlYAor2LwJnvM7M=,tag:EAms8k04YGAs16M9wjuCIA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:C7rdYA3To8fxhLC5KbaHr/E13fGsTEO1Rw7H1nZ0AOg=,iv:Cn1F1tdz9cEIQ31F7f0p4SB2NmEKswTZR7BIv2FTBp0=,tag:eELjIszSER1aPByAZAjoUw==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:Td2id18dsZwHRYg1H7pZThRcHaMKWhBMsxlXRwNtTRTQqyi7EuUTtXlO5C1Xmk2YLrYEMeqiTFt7I7nnA0bCzKO4RIXGnuBgG1ap/85CslJ78vPDCINH1K2uJfNTA+J6O5EjRqUslx/0ZnkvnemCPQh9RJfOjDve36cditFP6qTbo1jQlNDVPK2IDyB6JK0irNQ41ZfksgdJe8HcNaLY0yGiV1LETD5RDsugJ/vot0v2lt6N+s5PrGnE0CJB8Xds2FFXtKdw0g7JVrNMXQ/qucV4i6xzeXE02xHxm/Rb/N6Tz0oRNN34B83uRunc,iv:cSa8TwsKsvgRWV1RPbRkUt1PRQeE7YGg+wTnB99C7p0=,tag:2oQQIS2sxhJnceY0eqLWvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TklCRVpUTlQrTUJwamtG
            N2hKK1UxbGdpRzFkb05aLzIyT0w0Z3FLRnlZCks4TnMrcGtRWGhQKzhSMEdlckhh
            ZnY4U1pQazJiNEFQSFhNbHVlQnVuZ1UKLS0tIEg0K1NtSDc4RzQzZElSSGRYNTd0
            Z0cvSU9QUWZrYStlcjBBUlA3Sit3NjAKEglN547D8wvlpcIDhWb7+7+zMguM3aGP
            9gW5I4gG1Wf9JVctWMLmnZnHHe0DQsk11PYc/42tNUlvlbCljR2sTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T18:02:04Z"
    mac: ENC[AES256_GCM,data:oMqtCc2JjxP8U3wWltdzErPxmvx8L4wBX6UEM1nbmTnbRMlmCafzzzSBNqVs+DFn1HaUnq/qb0PwGp+D79hFS1QFlTvBSVd1N540ifNe3pH5Mw0wh7F/SpbhZQorGhkKitD9uMXGS/hcCpj13dD+54OVmhzzfMdZmqmbGpdl/hA=,iv:zeqJIQM4cF3HWdIA3qWgAZCGuYNVCr0oqkJDs0TCkvA=,tag:HGJWiDuntbMalA/ApTo1IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:R+qlTgJdZw==,iv:jVrsPRCrYIqJ1JS7r43Fe212YoEFF2QwuY8f1YdhHd0=,tag:m7VE2kHXomvJagCmn63Z5w==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:HfLH7pZ+RYuppdjhxuvODZVuhJ0=,iv:1mmgilWXBVvBaKwSQakTLbjQRfxwY1FVnLnmOsFuIlk=,tag:R596R5pCtnAlmEP4hqAmoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TklCRVpUTlQrTUJwamtG
            N2hKK1UxbGdpRzFkb05aLzIyT0w0Z3FLRnlZCks4TnMrcGtRWGhQKzhSMEdlckhh
            ZnY4U1pQazJiNEFQSFhNbHVlQnVuZ1UKLS0tIEg0K1NtSDc4RzQzZElSSGRYNTd0
            Z0cvSU9QUWZrYStlcjBBUlA3Sit3NjAKEglN547D8wvlpcIDhWb7+7+zMguM3aGP
            9gW5I4gG1Wf9JVctWMLmnZnHHe0DQsk11PYc/42tNUlvlbCljR2sTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T18:02:04Z"
    mac: ENC[AES256_GCM,data:oMqtCc2JjxP8U3wWltdzErPxmvx8L4wBX6UEM1nbmTnbRMlmCafzzzSBNqVs+DFn1HaUnq/qb0PwGp+D79hFS1QFlTvBSVd1N540ifNe3pH5Mw0wh7F/SpbhZQorGhkKitD9uMXGS/hcCpj13dD+54OVmhzzfMdZmqmbGpdl/hA=,iv:zeqJIQM4cF3HWdIA3qWgAZCGuYNVCr0oqkJDs0TCkvA=,tag:HGJWiDuntbMalA/ApTo1IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
