apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:xddl,iv:IsV3ra/Evuihx/waH9b0yJdkxfD+AFp7L/tjXo4U+kc=,tag:tYVed/pCvHs4IjAK2KGu0g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:dQNlH6zTCePJm+mFp5RYsvzzBmChYA==,iv:atBnY62fsq7u/UvY3kms1VvssCDTxOzPZ6wGvyERxWM=,tag:Xh73vfqx7IOgdPLq38lczA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:FWGW,iv:1xwoDeK0JUzeNOmIY+wdYmOPPpIn+1Ri/fBL70puJew=,tag:m2nXBoSHO+twv8C2Gx+dIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:BGO8tYSrjU007vSFileazTV+hpu5Nyl8Vhw9ixc3824=,iv:crjRmXg9mOrOw9lVxEJOw3KACalzhqPyuK5heptfXBM=,tag:pHs7p4vI6iVExIgC7tYwXQ==,type:str]
    N8N_URL: ENC[AES256_GCM,data:5/2PkaVruNgDaMJl2MW6Kp7dv+wwdDsepn6cSw==,iv:GTdIiuf1m9WgSNrgQ4iD9tJgcL+rs+JYBMmQZb0TWdE=,tag:KM2aNjht6obSpvDu8TXxKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:CkKvT2JrScIcVJ8/+e1K1ZE3masrNLoKAL0z/CtaI8wjqP3hSQmbl9g+xmzqKAWohTnVjEZGAvItiiyC3mSAaipurG1B9OmjQgl9aSKdZYOglwF60XrvlUcz7qGB2zGouRqMwaZu+/3EKVSwpuOxVLqvR3Lx1j0E/FmAxfK5OMBlUNNtEZFsO94f9AjbwTYom9xYBUE5hBo3eNHbzTGk70S0Bpevyxk7yL7VtKRPiV6d2KiUnkjW8w==,iv:VL+XI5s95xkSR0YXm9zyJ5CND5JNRl5bgyolnufMq9E=,tag:MrngsQGXyL8eB/36Ws6ZNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:ttHlP/isGYWci/B8FHZ3p23NJBRGncJeJCmC,iv:tDXJT0QllRoZNrXaKP29ciwWXbUUK5oQILq4/6AucsA=,tag:o0WpTso09kYeJdGSSBI8Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:rFuzaa9tjvSRXH1ef1z1g4eRx0g8lRQ0u2v7,iv:DNxSIYkj34AKCLY+4PlZgV1tPtB0FQb2ye+3WhkYpo0=,tag:SjkwJ5x/lXwf3r+lMfeonA==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:j9SBv1slbTWJ92/xAyQph8l/gdWiWIsGbRSYfSE9iGg=,iv:WkKrSKuAt5mpEJoDMI5O31DImIw0uhXEa7nNoWfmJis=,tag:0OGHv26FRRnACGHomKJQmA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:iuX1/EfAlN8uYyY8ah67PxYtN6DzLrD0PDkmMIRC8YU=,iv:n6iTVEyacxia5GX98rul9UO/rNSOrZ8/uZf763QJkJU=,tag:xnOM7Cnm5AX7CbU0pV9KQw==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:DHKvaRAwl5X2khRRAcSZsK/MrfHk4z+Nrk29sU7BPqndttYYMeO0Vt/ebqeijdeydiYJieVp6XiezEIpRBtEVJbQB4FtMny1M2MkLRMmHDK1jWQi0J3KDPXVPQwKKLIuT1X2g4dXSLA+/lFPuRto+XLuV2sMYMNMDRNfYn8U4zZ/w7ktl5ihWq5VcGWsi9lBQc0C0kNK2c3E4ld3j4z8pzD2wtGghvw0TUva11IntXWR61z1XDwfIIZHuyEZCwm80BEvR38JTn4w8SGuAGNspyMY9mTfQ5qIH+l3jKx5W62Rb3rypNvxvSbI06fP,iv:y4DtBgLQpgWLuiP6sIUBeTEMMX6MIoF4CbYPLCoPRC4=,tag:VQxZVGC1QSfIGSRcaqRtBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:kw+n7vKMdg==,iv:u1TXLRDuy2rEwe5EbNuJ2dCUYU9HuT4fdlFmS4uycxU=,tag:zSJhpyt199afWmXBvwMStQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:yau0J31E2MHmhFPQGg9BL+2i3xo=,iv:yjeW5+OyfWlykUgpnlPKZqMaw7qfscmC3k78mT7+YKw=,tag:vmo+RBwaVIESDxEyYlgWPQ==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:A83dCVUeYXUR4/uGWgt0a/GjGlASQUrztmegRA7uqQecQGrVdg==,iv:xmuIXnJrRArdm6V2yU0ywmksiZDSVEdrYHnNOBFO2S8=,tag:yJqcmWEM2m0AkOc9oEv3gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:4QNa40bDhkGHv/ebdm8w0mn33lUDmwvBjRuc94Up337S9FScc8YPCZPKvoo=,iv:M+uK57HFeGfy3yzw7WBYa1Ogt/CTsdSOKs+lUo1wDoY=,tag:95B1czRDkEnUn5AstCR0Iw==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:kAmJZzXcNhBm14+63F0qN3S+0hbbobqxHzxR,iv:YxWDRhcyhhCYyE3AzCQAPHcKM+1zHK5/qZ1TiAgcNsA=,tag:Ax/fWo/N7jmlhbTzWaD/ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: default
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:wQsqX3Xr6ZQwblVClruBoonVe2tUHSY5XPv7KV1wLCl5bEkCfLQ7bQ==,iv:phTBMp668g+eYuidW7xN3y6a4aw/Z5vOKSDEgONEpEI=,tag:IhZbtTxgte8hIzrr+KOQug==,type:str]
    RENOVATE_GITHUB_TOKEN: ENC[AES256_GCM,data:t/6hmwPC4WSzJIa/3gy24eUnbxhQLYYNLiPG/jYhrDuzltDtJhEw6w==,iv:rd/yvnmb/tgrO2O3HUNSI/1Gj9aw3vMmhw/RFAUmDn0=,tag:s9JwNLoHFagsa5R94UtIvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-secrets
    namespace: default
type: Opaque
stringData:
    JELLYFIN_KEY: ENC[AES256_GCM,data:c8hoK7J9c721kokSPEgi1YOnmJozkNv6riu3KxkHF7I=,iv:Cn7xbe8DflplEIWzamBdZY/4sriuUxv2aoXpAZMLCLk=,tag:SA3G8Djj63dK6mPAca6o0Q==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:kq2PBmvh0wooZq+vOaP36sm9QuBUdGuyKUc=,iv:3fgj22lE9ij3fzETmN8KSOm5TdrZAlJpNMCvkDXyPRY=,tag:yL08LAMbdqd8x0Ammfw8Gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-secrets
    namespace: default
type: Opaque
stringData:
    HA_TOKEN: ENC[AES256_GCM,data:b5ApaEPScC/8UYePXvolj93j7rsbXh8u6tzz1YsmhDbfyycYClQ2nozflseBgGW/reteoh6zr35MaLI278d3C1PcNk4CDPmcV/DocxQzGlTkT9RboMDNHuhtnb712uFdUrC/sc09OFVTm0cvyiNEWYj3+owiAHSrM6a7awcmu0L5FOU0bpr6yV0MbEeOHoaXTSaNy4XWinCZV8qOoLFvZM9ce9oCVOetY5I+tCmahch9eeKrxmu4,iv:6VanBi9umc1PfzU9Dh4HIPnuxTg6W0of48uLCthhb30=,tag:K6M+xG0UyDFfFA4NsmBH7A==,type:str]
    HA_IP: ENC[AES256_GCM,data:JmoOWbISnsuzd3vc1CBcGGhydOxGAdJBx+s=,iv:huokJxe5sYicluxU0lGsPehKdAXwT/Hk4T/OBH9G3go=,tag:Ujm/CtFfxFTeejMigE4HEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: dograh-secrets
    namespace: default
stringData:
    #ENC[AES256_GCM,data:Plf6pJ6seNUnuNoJya7G1ECSoc7phOfw8w==,iv:nw/FwX/iqZq4FCZtvyspmccSRwYBdWd8dwwLO6oC7bc=,tag:Lr8348kly2pATSoK9Q0Nhg==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ew2AKUqHlV8=,iv:lVkoK8SP22w6WSPXkI+ZHn1XUcN4mNjL2tTCyY5J8fQ=,tag:bf7UqAWgTlVImfv6zl2+aA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:3QUEKbnYqS5iZm4=,iv:1xIswIBUydHIhVKyaJx5CDB3oAOdPPwiy7Nx5XEm9pc=,tag:iD9Y200j1Nu7SVMxo3c9fQ==,type:str]
    #ENC[AES256_GCM,data:YRD5CQrNjMp2fR4mgKfU26AWJwKa1GDGtsMiMyl02xUcG4OR/4jNp68nFzFDFQWlTD2x234dQ8GA,iv:oOxT2igl5nTVAgrUieBL/glVMupgB74qJBfbfeH/va4=,tag:oQFnEV7KOqHqZw8QkrIO/A==,type:comment]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:YIOvLoOhllSPZA==,iv:0lbh+pBSnG/eVyh4VXK+rF9JSrYjut4tEEchK8Wipe0=,tag:XonukmrvVB7MeMO4Cmw4FA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:nBTXjGsL5mKRPg==,iv:RxLiJGgqfGzcgN00v4d4e54G3+ZLccHV/YyhjbuX/tA=,tag:rR5PjBpeNH8kS/54fCTgNA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:MbD+NHw8EhQtMQ==,iv:fPZqxlrT4786RGOMCLDXP7yRapVJ9cQ/5qRR4cKN9Wc=,tag:NLIlXbsY63kj3j4kiDQA5g==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:NmNrgDBttwuIOA==,iv:MMwFY+FgV2KIaNjMJ7VgT1rX4v2xlXONRx3TEuNMCVA=,tag:PiXEbyWHTR9rai6lehPM6A==,type:str]
    #ENC[AES256_GCM,data:cvGRPUydN8C7W77hVcE=,iv:2/Iv+8zWnLbASeuPwnag8RrPOl7B//oEhjIXS2Ltowk=,tag:YC7k74e/5L3Jg/Okw/CyIA==,type:comment]
    GOOGLE_API_KEY: ENC[AES256_GCM,data:Y8CDjClbtYAGaYAs/eBWpe3jl4ZU2g+26T4C9DDfGIfoo48C0wHz,iv:ykRdpHBnr7HHQsZNISHKiUv5/TpSRjwaA2PGLfeSf6I=,tag:vl7j2t3xh+OUvqSlRmDlOw==,type:str]
    TWILIO_ACCOUNT_SID: ENC[AES256_GCM,data:+9/UOW3Kz5SJlrVUO1p/dMK6QgA9T6HVmm/JUrDf3qTfnw==,iv:Ks+XfX+fOpgHCPxWDnwmLfpMmY/hK/vR+IcwVEBaqGE=,tag:E2C1TvFjJVQEgPE9EwE8aQ==,type:str]
    TWILIO_AUTH_TOKEN: ENC[AES256_GCM,data:ptYKqi2+yrb/YLlaUDRF31yKYO2lanyMq7sUZIebP4s=,iv:qhq1+K58uvEq53xaUBv+kcfLoiTpEQqBxLuMj/2614s=,tag:9UBlXgwD7oJHcK3XV8QrFQ==,type:str]
    #ENC[AES256_GCM,data:xD/IYRZIuCW/ByCloCkgixYVjqITeeFVTZgKjl4Rtqu2zW2Kk11vPJLe+l8rHWzF4upLARU3Yq1lRBFluR7x,iv:9ckMHMcIVYKl28vhWAXupuDRWhxgXzD/46xPDwRX4W8=,tag:z+BNhtNS1qS5Ajao2rgdkg==,type:comment]
    #ENC[AES256_GCM,data:7DFDGJ6ACNRWXYyfi9HUD7wT7pE4O641cHnp3IhI+UscgjSzEGw=,iv:h/OhRdsWrCJANFXgvSLPzt045vnosGKvU25ISkOslOo=,tag:6F6aFBe+LlDEvKWX5Uy+2A==,type:comment]
    #ENC[AES256_GCM,data:yogVo6ghn7OYpXsZtpp/h+iS+2LpIL53/PG8+ikkRQ==,iv:4bPCFGFA4iAAWVmOCPdgfGLdvP+pg1REe7PVpS3Xx4s=,tag:WkGvAeUBOESj3PmJ37tOZw==,type:comment]
    #ENC[AES256_GCM,data:VBzKI/igiwYRs8YAjQAdw7iGMnwZLxCX3A==,iv:2KeAI8icQxskrlPzmh1fIoHnX3YQ+KyA/YS9ccj496Q=,tag:aDWPyy5fJeWuaymG3G4UAQ==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:uC4UdGF4DzWfWB4gZcRT3BoumWapOt4VvDsBaZe/QWOWgi4hbrAOY9txDySfLvt6VBNalfAYWOsL5ZnEbJ01faQVC3wVNp7R59X5Ye7hMPUDCfiYh/w=,iv:hxatrWAp/Ellz3CvihyjP4HKy4ghLvh4zUVWHndEM28=,tag:ap19xXMpPfBCQRwsr2DmTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUNGVXF2NzMvbWpqU1BU
            RFVkOHZYZFhHQnFJczYzbEZDM3JMQ0xjbm1FCi96MTg2TzZGcFQ5QUVwWjNFMSs1
            YmdvY3hQQm93Qzc0N0hvYVZHczNtQXMKLS0tIDBmMlJsYnh0TnBFTWdXcnY0ekY4
            RWpUR3lSOUxibmdIM1ZoVzdaTW1nR28KzsYMr5HlaMubU174PCgR+q6T6p1PBiie
            qbNmIbG1EUV2/Wi46BZaDhmvQ4D60VXKbMuYWn0PmEmAqYwy1WEYEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T15:26:21Z"
    mac: ENC[AES256_GCM,data:rRVSQt/3T4pYNyYk/BGfFwZ+Js4uCCEBelk/nvhsl1MtjU7a+PpjOUE/n5J9KO/d6jL07U0h8R9p6XMCZgwLX3DXPzCMX9HFdYZxhE+OzgeY7mQTgFNASMFBuMx+hUhDAEFMYZX8bE9R8osehyZ7WBxsFjU9/yUvZk9sKZL5HlY=,iv:urN2jdCzxdXmiYHFmCsm3rhC9F/BQBkztGqy5QjRj1k=,tag:3eKFzS4NlwriiUaxBZadKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
