apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:4aNv,iv:p7zQBQvAHz0GZ1fD/ndB1XuHJnSmPwSGmdMWVsSMPPY=,tag:WPRTGAjQvtOqVdHe8jpsHQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ilFAI6DW/0B7w6bl/NkTOziz4Pt/5A==,iv:xXgX1O9TrDZ7p3P3A4jdN1XOz7pzAeIkA2JlCT8CXpk=,tag:f1yODQVgteHZ9ml9mELVFQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:GzjM,iv:X2GLG8x7evcBKvVPEC9bQ79LOjQxn8HIqkO9BV4TUZE=,tag:Vcv8HfJGD5uRlzKGI/Nftw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNE5jZ0NDblVXTWpWOG95
            WXhVS2JTdSsyUmlmNE9hUXZOWXFhaGVucUFnCnRNMmFPS3FaSzVpVmhHS3BHbGZz
            OVpIcG1LQ2JuMlovK1V0YmdHcHJ0cDQKLS0tIHpWQmZmb3kvWlRQWDJKN0RDOGdR
            dFBzbmt5K2oxY3l4MG1aaFZWSitERmMK9F42YUaELKLkXti6gx96YckDCw1W0e2K
            LnuGs4r+v8nEcoxMDIMjw+2NqKzNJJbFdFxvPdTncSkRGl9YJ3BouA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:46:50Z"
    mac: ENC[AES256_GCM,data:wulSt6aaMnd6jI3AS7DEJk6tONmDAGbewzkv3QtOHU6x3L6UeR5B9NMRsm3nTthrV+ndldyv+/08McLyrpAj02O7to6YS8csAcmKlGo/qKtOBCVkTScPmQIBPyqHqs2HbrLS2LxDK9sH1iWVoRUeMpY0vZ/OQIsxQiTOZe401jI=,iv:cD2Jpun45rU1i9ONAY8AjUlzvto/dfXVGnsGmqLrY8o=,tag:wB8do2BjhhzWQn97HOvUEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:Oj/fXlvytZ7aVME3z5uHTYMwZO5UOnCNzF+2sYNA0pM=,iv:mvmdi/y4IQkd5zXATD1p7TB68euPKgkbLgIhy/zipeA=,tag:dsAQu1xHz11iGXZlRIbaDA==,type:str]
    N8N_URL: ENC[AES256_GCM,data:Pp6gFT5pTzeP72W59QeEk5YOoTvZQuKu7Eq2dg==,iv:RP76rZQwhF7Zuci0adMPfc8G2qz9AZQSwHYEJmSJAvQ=,tag:KITE1zc/MhDOlD6Dfh/t6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNE5jZ0NDblVXTWpWOG95
            WXhVS2JTdSsyUmlmNE9hUXZOWXFhaGVucUFnCnRNMmFPS3FaSzVpVmhHS3BHbGZz
            OVpIcG1LQ2JuMlovK1V0YmdHcHJ0cDQKLS0tIHpWQmZmb3kvWlRQWDJKN0RDOGdR
            dFBzbmt5K2oxY3l4MG1aaFZWSitERmMK9F42YUaELKLkXti6gx96YckDCw1W0e2K
            LnuGs4r+v8nEcoxMDIMjw+2NqKzNJJbFdFxvPdTncSkRGl9YJ3BouA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:46:50Z"
    mac: ENC[AES256_GCM,data:wulSt6aaMnd6jI3AS7DEJk6tONmDAGbewzkv3QtOHU6x3L6UeR5B9NMRsm3nTthrV+ndldyv+/08McLyrpAj02O7to6YS8csAcmKlGo/qKtOBCVkTScPmQIBPyqHqs2HbrLS2LxDK9sH1iWVoRUeMpY0vZ/OQIsxQiTOZe401jI=,iv:cD2Jpun45rU1i9ONAY8AjUlzvto/dfXVGnsGmqLrY8o=,tag:wB8do2BjhhzWQn97HOvUEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:kiAsRsZ3V/XZ2uJGSLQ3OJEX7PoZFzzyhO1FwiIGMcY1yDSAWmoGml6J8uuHynw7oqrrrlsJ8s6lqAMRIivDll6ZhlJhl0jgh3z94TqdwFga5Gr/7W2JBknopqw/7rfjJ2Ta+qnE5qcDGd/xNbp0d4meZjNzdyCfyDg94sb0cd7iFD00GCwbMl0WvjJ626KcR+uaZBZr4XNU/E5FlU4eE2/uz8QXi1Iq8neIvsA0LwNWv3YoBs2vmw==,iv:BsVc0g16kmZWkJPV16HBnbt1liJ8cmh5jT3BZ7pYSJU=,tag:1/OtOsn5kMCVmOuF/mOlXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNE5jZ0NDblVXTWpWOG95
            WXhVS2JTdSsyUmlmNE9hUXZOWXFhaGVucUFnCnRNMmFPS3FaSzVpVmhHS3BHbGZz
            OVpIcG1LQ2JuMlovK1V0YmdHcHJ0cDQKLS0tIHpWQmZmb3kvWlRQWDJKN0RDOGdR
            dFBzbmt5K2oxY3l4MG1aaFZWSitERmMK9F42YUaELKLkXti6gx96YckDCw1W0e2K
            LnuGs4r+v8nEcoxMDIMjw+2NqKzNJJbFdFxvPdTncSkRGl9YJ3BouA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:46:50Z"
    mac: ENC[AES256_GCM,data:wulSt6aaMnd6jI3AS7DEJk6tONmDAGbewzkv3QtOHU6x3L6UeR5B9NMRsm3nTthrV+ndldyv+/08McLyrpAj02O7to6YS8csAcmKlGo/qKtOBCVkTScPmQIBPyqHqs2HbrLS2LxDK9sH1iWVoRUeMpY0vZ/OQIsxQiTOZe401jI=,iv:cD2Jpun45rU1i9ONAY8AjUlzvto/dfXVGnsGmqLrY8o=,tag:wB8do2BjhhzWQn97HOvUEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:+58hCjATlt65s6e77jjVxV1+5xFKg9Y9/H9qftojO9tflA==,iv:nGQMnir+aseJYRgq78uOw6OSLJ4BWHrEcR/R48tDEUc=,tag:CnQYyKjUxKwaCYexKi9K8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNE5jZ0NDblVXTWpWOG95
            WXhVS2JTdSsyUmlmNE9hUXZOWXFhaGVucUFnCnRNMmFPS3FaSzVpVmhHS3BHbGZz
            OVpIcG1LQ2JuMlovK1V0YmdHcHJ0cDQKLS0tIHpWQmZmb3kvWlRQWDJKN0RDOGdR
            dFBzbmt5K2oxY3l4MG1aaFZWSitERmMK9F42YUaELKLkXti6gx96YckDCw1W0e2K
            LnuGs4r+v8nEcoxMDIMjw+2NqKzNJJbFdFxvPdTncSkRGl9YJ3BouA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:46:50Z"
    mac: ENC[AES256_GCM,data:wulSt6aaMnd6jI3AS7DEJk6tONmDAGbewzkv3QtOHU6x3L6UeR5B9NMRsm3nTthrV+ndldyv+/08McLyrpAj02O7to6YS8csAcmKlGo/qKtOBCVkTScPmQIBPyqHqs2HbrLS2LxDK9sH1iWVoRUeMpY0vZ/OQIsxQiTOZe401jI=,iv:cD2Jpun45rU1i9ONAY8AjUlzvto/dfXVGnsGmqLrY8o=,tag:wB8do2BjhhzWQn97HOvUEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:9aUpBNFEOKFOQ/XRRYUEiuiAA6dpdk2zcOv2,iv:yKc8Ghyt8t0xcrHNYJ+iQ1H86wCfM3BhByV/1ZtUX8U=,tag:wXHm1PZo/H+cwOgSSnEtKA==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:bR3NnwSeksUqBQ5yM1i33EbWhVMpzYc2WiRhi8Hqrq8=,iv:oi1Br7RxuZp162L6w1RlaskTceN/SvWLnY5nIMfPlis=,tag:/uFYqsqipZ5wSbRmXR/E+g==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:R6jvbPs0KGXiPd+5ZftU7YVoY3NWv+XN5g9REz6tQIg=,iv:Gem1kXPwaUFd4t7+TtsxU7JKIV44P9yDtH3qQQIt/dY=,tag:DB1FQIE04JQ1NATtzUCxhA==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:/ZopxbxVpz8+Di71kY6EJBo7cNByhQPlvE3xTerCzMWMs3cJHMnsyWAhBYD4m2C+k39QDqc6dRBy+ikPOVZz9rScVT4zUHzxgkU4g6I4PIZrojMX9woyXxdng0SZdvPQpa6koSAUDvlKb46ZSR9AeNO+vSUvOb4PShgY4pi0ECnX7xFs+4Q5SuDv9t9K0vA2QRWj8NEI3n67gZZcI3EqzIN+2/7eJokUc3I5YG2SKBSpwEx7Vy+xUxucJy1NHMc5eKj8zJKfZrgSpcCDd1BZh6qfDje5P/hlTK5oJEECMwYYtB7xnWNhfL6U42Pk,iv:Kbv4Crr7P41Hsl2HFpgqbIa2GEz1pdAXZaH9syioeGw=,tag:TKy+LoVMOigmL7Hg5cDpqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNE5jZ0NDblVXTWpWOG95
            WXhVS2JTdSsyUmlmNE9hUXZOWXFhaGVucUFnCnRNMmFPS3FaSzVpVmhHS3BHbGZz
            OVpIcG1LQ2JuMlovK1V0YmdHcHJ0cDQKLS0tIHpWQmZmb3kvWlRQWDJKN0RDOGdR
            dFBzbmt5K2oxY3l4MG1aaFZWSitERmMK9F42YUaELKLkXti6gx96YckDCw1W0e2K
            LnuGs4r+v8nEcoxMDIMjw+2NqKzNJJbFdFxvPdTncSkRGl9YJ3BouA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:46:50Z"
    mac: ENC[AES256_GCM,data:wulSt6aaMnd6jI3AS7DEJk6tONmDAGbewzkv3QtOHU6x3L6UeR5B9NMRsm3nTthrV+ndldyv+/08McLyrpAj02O7to6YS8csAcmKlGo/qKtOBCVkTScPmQIBPyqHqs2HbrLS2LxDK9sH1iWVoRUeMpY0vZ/OQIsxQiTOZe401jI=,iv:cD2Jpun45rU1i9ONAY8AjUlzvto/dfXVGnsGmqLrY8o=,tag:wB8do2BjhhzWQn97HOvUEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:LTef5PXBAw==,iv:gAxq+VTATFUJeruXanH5Eaicmxu5nqZgprn5vlvyi4I=,tag:tKG5y9QpGUj5TSnCmUGUJQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:pOj/l7KGTJtWneqJEA5Ml+kZy3E=,iv:imyo7XOMfBPzWaMs0C0V3sVYGn2zVy3ESxc2GH2tN6U=,tag:NzJcZa0JazNat6Zg1SaTFw==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:3ZKv0nm/+rZApPfV+QO2IwB37oX8ygHfBM0xZVNx4r+hpdm5EA==,iv:vdQQKhqtIIZUQ+2JCcQn1/JQXpbkP3NYnMSvFBdWjrY=,tag:VR2Oref0A8qSsiTIgFsvlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNE5jZ0NDblVXTWpWOG95
            WXhVS2JTdSsyUmlmNE9hUXZOWXFhaGVucUFnCnRNMmFPS3FaSzVpVmhHS3BHbGZz
            OVpIcG1LQ2JuMlovK1V0YmdHcHJ0cDQKLS0tIHpWQmZmb3kvWlRQWDJKN0RDOGdR
            dFBzbmt5K2oxY3l4MG1aaFZWSitERmMK9F42YUaELKLkXti6gx96YckDCw1W0e2K
            LnuGs4r+v8nEcoxMDIMjw+2NqKzNJJbFdFxvPdTncSkRGl9YJ3BouA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:46:50Z"
    mac: ENC[AES256_GCM,data:wulSt6aaMnd6jI3AS7DEJk6tONmDAGbewzkv3QtOHU6x3L6UeR5B9NMRsm3nTthrV+ndldyv+/08McLyrpAj02O7to6YS8csAcmKlGo/qKtOBCVkTScPmQIBPyqHqs2HbrLS2LxDK9sH1iWVoRUeMpY0vZ/OQIsxQiTOZe401jI=,iv:cD2Jpun45rU1i9ONAY8AjUlzvto/dfXVGnsGmqLrY8o=,tag:wB8do2BjhhzWQn97HOvUEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: freescout-secrets
    namespace: default
type: Opaque
stringData:
    FREESCOUT_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:ReGDMOh/yHF34AMshG+V7zUAC9w=,iv:NSaSparb948thj1lPGyPjEBlOxpPQyrEwP/akePqRZI=,tag:O7gmVoK5BBMdgA2U6/thNg==,type:str]
    FREESCOUT_DB_PASSWORD: ENC[AES256_GCM,data:dNE5B0ydAH2ROLa9sGHuJhYSHFY=,iv:N8TR0oGw3OjMZRoTIne03Jt1J++mmWBV3dMUEJkuSts=,tag:cUEcXyo32yELc65+5qb7Tg==,type:str]
    FREESCOUT_ADMIN_EMAIL: ENC[AES256_GCM,data:pajPnExgcmEdUVygi6vpTrPHwtojxAs=,iv:utTHWdEXbUViK7UxCXD81Q0aMW/sbV+wdbdRmkvQK3A=,tag:Z5FZVvFm3nXkpnnqJ8/zTQ==,type:str]
    FREESCOUT_ADMIN_PASSWORD: ENC[AES256_GCM,data:ISs9iv6OFQCJYml2wSgGyyI+rEI=,iv:DQ4p775FqfyEeeomj6UHDPYaw1saHNxYMLSXv6iNSGg=,tag:XrD8Ue41V0hCuFSuMyw5Pg==,type:str]
    FREESCOUT_SITE_URL: ENC[AES256_GCM,data:abXABXMXQhhFQj9G7yuI3vW2Y2BSI8U5CyJIJA==,iv:Es8rOXdsALIs/Ms293BNnjqRZRFERcmSSENnF2eMb+w=,tag:HiqYKnjm8neM01Rq6PhJ/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNE5jZ0NDblVXTWpWOG95
            WXhVS2JTdSsyUmlmNE9hUXZOWXFhaGVucUFnCnRNMmFPS3FaSzVpVmhHS3BHbGZz
            OVpIcG1LQ2JuMlovK1V0YmdHcHJ0cDQKLS0tIHpWQmZmb3kvWlRQWDJKN0RDOGdR
            dFBzbmt5K2oxY3l4MG1aaFZWSitERmMK9F42YUaELKLkXti6gx96YckDCw1W0e2K
            LnuGs4r+v8nEcoxMDIMjw+2NqKzNJJbFdFxvPdTncSkRGl9YJ3BouA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:46:50Z"
    mac: ENC[AES256_GCM,data:wulSt6aaMnd6jI3AS7DEJk6tONmDAGbewzkv3QtOHU6x3L6UeR5B9NMRsm3nTthrV+ndldyv+/08McLyrpAj02O7to6YS8csAcmKlGo/qKtOBCVkTScPmQIBPyqHqs2HbrLS2LxDK9sH1iWVoRUeMpY0vZ/OQIsxQiTOZe401jI=,iv:cD2Jpun45rU1i9ONAY8AjUlzvto/dfXVGnsGmqLrY8o=,tag:wB8do2BjhhzWQn97HOvUEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:EiV2XFyftjI7TZxUaHkF1qsj1bWEjlkvjIakrt3eagEpYxXW7Q8opntWwPU=,iv:lOra0swMWfQ4R7ep5nUk+aAf4uTHFLshnDpPYi9iwsA=,tag:njh1UHh6jhXeu2iddPR0Ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNE5jZ0NDblVXTWpWOG95
            WXhVS2JTdSsyUmlmNE9hUXZOWXFhaGVucUFnCnRNMmFPS3FaSzVpVmhHS3BHbGZz
            OVpIcG1LQ2JuMlovK1V0YmdHcHJ0cDQKLS0tIHpWQmZmb3kvWlRQWDJKN0RDOGdR
            dFBzbmt5K2oxY3l4MG1aaFZWSitERmMK9F42YUaELKLkXti6gx96YckDCw1W0e2K
            LnuGs4r+v8nEcoxMDIMjw+2NqKzNJJbFdFxvPdTncSkRGl9YJ3BouA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:46:50Z"
    mac: ENC[AES256_GCM,data:wulSt6aaMnd6jI3AS7DEJk6tONmDAGbewzkv3QtOHU6x3L6UeR5B9NMRsm3nTthrV+ndldyv+/08McLyrpAj02O7to6YS8csAcmKlGo/qKtOBCVkTScPmQIBPyqHqs2HbrLS2LxDK9sH1iWVoRUeMpY0vZ/OQIsxQiTOZe401jI=,iv:cD2Jpun45rU1i9ONAY8AjUlzvto/dfXVGnsGmqLrY8o=,tag:wB8do2BjhhzWQn97HOvUEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
