apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:rfvT,iv:fvpqphuvriAE982GyIKgwrQ9+t+P3TkNpEqsgRexVi8=,tag:ZEtx4x3QZnk7zmvka1ASjQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:wU0UNSRTa5qc3uTv1Rox2AgiS0gepw==,iv:Lw0HNhU4JHOfU4vc16/Yu5vep0WNDNpeot0Ea15+nBg=,tag:97b/nidluReY4q8FLvD//w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:hVeF,iv:b76qIDo7ZUdOWGSL+sv/1bT3SCPUcRazv8Kdgm/5iFY=,tag:SsQ5Bu+lGrBg9+AF5bRCWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRmc5MkFGNjZyOGdhZHda
            cFkzVXc2UklaNkM2L05XUG1DT3hibDEzOVFJClR2dGNCV2FLSXlpWkNNMTE1V1ZP
            RGJyMGpZeDlwTlZWZVVIVzR1dm90aW8KLS0tIDNkUGJlNitSOUl4ZGtQejBVY0pS
            aEZjb2laNFNnWWs2cUtDNHk4cy9kRlEKnQhf7Go136y1j6+M7McvJr94iit6hTJ1
            eA3if5gbLnhy+F/BPXCjZR4yUoQy5+Wn0FL0F9C91PmIHOULv9x37g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T18:20:51Z"
    mac: ENC[AES256_GCM,data:0Vwwt5vPd+QIe20L2TuG2aNCVi0UEFPbWvnNszYcXvo+Ndb4/MRyzY0pwe1FYvhz+VLngqY1w5dB6LXeQ+hog7b3jPHj/2nGOBoG3i90qUE9Nr8Qw36W8A3gVsIyz0MdPjOgm0gKfiXYVzKvXAMqGS0NYLVbZ5+j0bmRWHHhMCs=,iv:CcXn4a8NQjBhcA7YLDhvV+3M5slnqa3WrZ5TQeB1uDw=,tag:XFYiNNCcV/t1spvOYAiATw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:XaUo522cU8mm3XXG5mYkZ/GO2AoAHY3qpTjeAj7Qo7c=,iv:UR8FLne/n10YjvG+A/GQlZ1ZSxR+hwt5QCUHm/nVOVg=,tag:kd/+pyHiOpjJLK+Gbl/xIQ==,type:str]
    N8N_URL: ENC[AES256_GCM,data:uaAkRk+5TcZmkGDVNmmmqAXSuhwO8Vha12oQQA==,iv:Q3EZICjEhidTr2i3jlNr6A1LiGR+QMmu5K6GKEsR0xw=,tag:6VT208wdI5+EzWdBHFKqBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRmc5MkFGNjZyOGdhZHda
            cFkzVXc2UklaNkM2L05XUG1DT3hibDEzOVFJClR2dGNCV2FLSXlpWkNNMTE1V1ZP
            RGJyMGpZeDlwTlZWZVVIVzR1dm90aW8KLS0tIDNkUGJlNitSOUl4ZGtQejBVY0pS
            aEZjb2laNFNnWWs2cUtDNHk4cy9kRlEKnQhf7Go136y1j6+M7McvJr94iit6hTJ1
            eA3if5gbLnhy+F/BPXCjZR4yUoQy5+Wn0FL0F9C91PmIHOULv9x37g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T18:20:51Z"
    mac: ENC[AES256_GCM,data:0Vwwt5vPd+QIe20L2TuG2aNCVi0UEFPbWvnNszYcXvo+Ndb4/MRyzY0pwe1FYvhz+VLngqY1w5dB6LXeQ+hog7b3jPHj/2nGOBoG3i90qUE9Nr8Qw36W8A3gVsIyz0MdPjOgm0gKfiXYVzKvXAMqGS0NYLVbZ5+j0bmRWHHhMCs=,iv:CcXn4a8NQjBhcA7YLDhvV+3M5slnqa3WrZ5TQeB1uDw=,tag:XFYiNNCcV/t1spvOYAiATw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:Yd8W9sEZLnVNddOCK6wJg0hdUaNfXyXl1FmM+SCjkAFpNq+CN84C294+xErhp9zkOWrZ3tLSHHSbdFaIv2jjHupIyb6Knr9ABGscbmRH2I4dwCeqyQ8cLOibYhs2twGSeoZ+FhqN3KQFt7SblThVdNIegmVd0zJsoL3deJuDa50o3vK/ytzaGHuMqlyM17PBeppyKd/71HkFOLITQx0azkaeJPJjMbM1Lug1D56Is5QYZCs4M4iaDg==,iv:W57Db/qWEROOOi06gWeZg2ICaIaCrukrz5dYbjZKjtA=,tag:YejcUSMihp9jWDzzoEXqZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRmc5MkFGNjZyOGdhZHda
            cFkzVXc2UklaNkM2L05XUG1DT3hibDEzOVFJClR2dGNCV2FLSXlpWkNNMTE1V1ZP
            RGJyMGpZeDlwTlZWZVVIVzR1dm90aW8KLS0tIDNkUGJlNitSOUl4ZGtQejBVY0pS
            aEZjb2laNFNnWWs2cUtDNHk4cy9kRlEKnQhf7Go136y1j6+M7McvJr94iit6hTJ1
            eA3if5gbLnhy+F/BPXCjZR4yUoQy5+Wn0FL0F9C91PmIHOULv9x37g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T18:20:51Z"
    mac: ENC[AES256_GCM,data:0Vwwt5vPd+QIe20L2TuG2aNCVi0UEFPbWvnNszYcXvo+Ndb4/MRyzY0pwe1FYvhz+VLngqY1w5dB6LXeQ+hog7b3jPHj/2nGOBoG3i90qUE9Nr8Qw36W8A3gVsIyz0MdPjOgm0gKfiXYVzKvXAMqGS0NYLVbZ5+j0bmRWHHhMCs=,iv:CcXn4a8NQjBhcA7YLDhvV+3M5slnqa3WrZ5TQeB1uDw=,tag:XFYiNNCcV/t1spvOYAiATw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:+1j2T+KacspM+qc3Z6o9m1pHrlGcVuOQsYq/lzflSqE5YA==,iv:hwV78Q+CqNR/wI+nqsKy1ovPObbESj1tcRA5zDY25Jk=,tag:uFk883QUFKsc5v3xi0Lklg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRmc5MkFGNjZyOGdhZHda
            cFkzVXc2UklaNkM2L05XUG1DT3hibDEzOVFJClR2dGNCV2FLSXlpWkNNMTE1V1ZP
            RGJyMGpZeDlwTlZWZVVIVzR1dm90aW8KLS0tIDNkUGJlNitSOUl4ZGtQejBVY0pS
            aEZjb2laNFNnWWs2cUtDNHk4cy9kRlEKnQhf7Go136y1j6+M7McvJr94iit6hTJ1
            eA3if5gbLnhy+F/BPXCjZR4yUoQy5+Wn0FL0F9C91PmIHOULv9x37g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T18:20:51Z"
    mac: ENC[AES256_GCM,data:0Vwwt5vPd+QIe20L2TuG2aNCVi0UEFPbWvnNszYcXvo+Ndb4/MRyzY0pwe1FYvhz+VLngqY1w5dB6LXeQ+hog7b3jPHj/2nGOBoG3i90qUE9Nr8Qw36W8A3gVsIyz0MdPjOgm0gKfiXYVzKvXAMqGS0NYLVbZ5+j0bmRWHHhMCs=,iv:CcXn4a8NQjBhcA7YLDhvV+3M5slnqa3WrZ5TQeB1uDw=,tag:XFYiNNCcV/t1spvOYAiATw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:WlW/d6qlerTmoXd+vAAdkaKZajYIZLRK7vNh,iv:slKqgVBjFzEz8rcGlC+b3QJSq9i6vNnDZhOMqY3HjMw=,tag:45A4VbgjO1/PQS0b80ohDA==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:1RwngR8ONxg5SevounJ2l9iK2ATDSxHL0MsatrgHp/k=,iv:qLQaAQZzhSYZktf7n+ANLPsG82rgyDPjp8cSCyY5f/M=,tag:oQFrO0395strVmDyNI9xhQ==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:qBPjsYlQm9Bh3xCDQ7Xlj5Bbur+HPOdYfRW3u+rljfk=,iv:bypAokd5WcRVmGldBB0/fA4/Da/jLgXGMJjcqJ3HfcQ=,tag:L6a/SXoARS1uPn2CBvZQ1A==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:+m0tb0Xkc0UyjngEokF58oFQORqsOXkvTOBMk2AviKfvQJAwM95nNbjgY71wBs4oQn6E2rTmxcivwYYUvhT//oLzJ45MYLLgYafqAcUtUG/jdOXVqYpLieZdpZZKQJXqh9FgZs9zKBoeyczc8uC987nNW2cLmJ1Zg/rIjnGZizH2IbDmGJJF8OmHymcQn0suwi5EtSAwU4RpG6cHlDfgKv2nRsPuvOyKKuwVEIANfpTgPo+k/Eti/DAAPT2G0pWc3Qq66WeMN+DtXUUW7Flc/dVgUFn05OuR3PyMOxogT09tQcZxPXq6JSGEvFxC,iv:PoKtskjESt327AFJl2+OMN/6/dmBwx1fE3LvTIxDNAg=,tag:zGmGbAy6bXpol6p1rN3+lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRmc5MkFGNjZyOGdhZHda
            cFkzVXc2UklaNkM2L05XUG1DT3hibDEzOVFJClR2dGNCV2FLSXlpWkNNMTE1V1ZP
            RGJyMGpZeDlwTlZWZVVIVzR1dm90aW8KLS0tIDNkUGJlNitSOUl4ZGtQejBVY0pS
            aEZjb2laNFNnWWs2cUtDNHk4cy9kRlEKnQhf7Go136y1j6+M7McvJr94iit6hTJ1
            eA3if5gbLnhy+F/BPXCjZR4yUoQy5+Wn0FL0F9C91PmIHOULv9x37g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T18:20:51Z"
    mac: ENC[AES256_GCM,data:0Vwwt5vPd+QIe20L2TuG2aNCVi0UEFPbWvnNszYcXvo+Ndb4/MRyzY0pwe1FYvhz+VLngqY1w5dB6LXeQ+hog7b3jPHj/2nGOBoG3i90qUE9Nr8Qw36W8A3gVsIyz0MdPjOgm0gKfiXYVzKvXAMqGS0NYLVbZ5+j0bmRWHHhMCs=,iv:CcXn4a8NQjBhcA7YLDhvV+3M5slnqa3WrZ5TQeB1uDw=,tag:XFYiNNCcV/t1spvOYAiATw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:P324Y2vjTA==,iv:OA7Vh5CcK4RZu/WUTat5AKLRZ3ogEpFGe90PhDqefYY=,tag:Y1GEEbyR9WAkN57y1esJ1A==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:r7mC+Ok8jWipVQcBklbC8/Fup1k=,iv:am9v7tHgzjOD0OyUsOKrjKGTXjLJBbHFHjwOQHkGpwg=,tag:E+rUMV2/3xxnsTRGUd0uEg==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:KxokgVIgvrwlolasU6s5+SXbWjWEpdTMKUqLf4QjPa/p0e/Ifg==,iv:/27bC8NT2DrAnyLAypKWTlaI8RcjtGl586JUXvMXc5o=,tag:uAnfbZ1TR3vZGkFng1rqWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRmc5MkFGNjZyOGdhZHda
            cFkzVXc2UklaNkM2L05XUG1DT3hibDEzOVFJClR2dGNCV2FLSXlpWkNNMTE1V1ZP
            RGJyMGpZeDlwTlZWZVVIVzR1dm90aW8KLS0tIDNkUGJlNitSOUl4ZGtQejBVY0pS
            aEZjb2laNFNnWWs2cUtDNHk4cy9kRlEKnQhf7Go136y1j6+M7McvJr94iit6hTJ1
            eA3if5gbLnhy+F/BPXCjZR4yUoQy5+Wn0FL0F9C91PmIHOULv9x37g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T18:20:51Z"
    mac: ENC[AES256_GCM,data:0Vwwt5vPd+QIe20L2TuG2aNCVi0UEFPbWvnNszYcXvo+Ndb4/MRyzY0pwe1FYvhz+VLngqY1w5dB6LXeQ+hog7b3jPHj/2nGOBoG3i90qUE9Nr8Qw36W8A3gVsIyz0MdPjOgm0gKfiXYVzKvXAMqGS0NYLVbZ5+j0bmRWHHhMCs=,iv:CcXn4a8NQjBhcA7YLDhvV+3M5slnqa3WrZ5TQeB1uDw=,tag:XFYiNNCcV/t1spvOYAiATw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:9asd+XhV0pXW4WIA/zbVW4n3VsWDpzzXqXgkFCn1JyHCFKabKIGeFyhv7tw=,iv:l84Zx9eELuRkT4U0DLSI/EKxe0wsPewRgivwrSLP37c=,tag:Bq+8i9uZ1un8ftL/Vx8zzQ==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:iGa262x7MwvllGJV2kFMVVgkYGSpzht+md/7,iv:Hh3IALoDNgiu40xWaJnJimoAI4vcLfpJXh81LxUY+hY=,tag:g+vIxBMqcie6CXqzYaZyCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRmc5MkFGNjZyOGdhZHda
            cFkzVXc2UklaNkM2L05XUG1DT3hibDEzOVFJClR2dGNCV2FLSXlpWkNNMTE1V1ZP
            RGJyMGpZeDlwTlZWZVVIVzR1dm90aW8KLS0tIDNkUGJlNitSOUl4ZGtQejBVY0pS
            aEZjb2laNFNnWWs2cUtDNHk4cy9kRlEKnQhf7Go136y1j6+M7McvJr94iit6hTJ1
            eA3if5gbLnhy+F/BPXCjZR4yUoQy5+Wn0FL0F9C91PmIHOULv9x37g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T18:20:51Z"
    mac: ENC[AES256_GCM,data:0Vwwt5vPd+QIe20L2TuG2aNCVi0UEFPbWvnNszYcXvo+Ndb4/MRyzY0pwe1FYvhz+VLngqY1w5dB6LXeQ+hog7b3jPHj/2nGOBoG3i90qUE9Nr8Qw36W8A3gVsIyz0MdPjOgm0gKfiXYVzKvXAMqGS0NYLVbZ5+j0bmRWHHhMCs=,iv:CcXn4a8NQjBhcA7YLDhvV+3M5slnqa3WrZ5TQeB1uDw=,tag:XFYiNNCcV/t1spvOYAiATw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: default
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:tTZ8WMCzOSgA6Jg7LI3nMnCbGfNNHvpw/+CpxaCxCFIKEIFpLj+A9g==,iv:NMI2zlIRIE0hjANROcXAJ9CIfB5NfKhY+GS4VYCdgtY=,tag:ULznYtzS5NBHxKj0iH1K2g==,type:str]
    RENOVATE_GITHUB_TOKEN: ENC[AES256_GCM,data:HEIkXCniyJ4WnnVzrQIt4p3tTjrOJtMywtk3ncvs8ymZtjyxQ3iWrA==,iv:l2l7aNhcI1RqVuvkg79x5zMHpDv89CmmeMvsgLUdNQw=,tag:ZCjfab8XSjNZidgL2l6a8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRmc5MkFGNjZyOGdhZHda
            cFkzVXc2UklaNkM2L05XUG1DT3hibDEzOVFJClR2dGNCV2FLSXlpWkNNMTE1V1ZP
            RGJyMGpZeDlwTlZWZVVIVzR1dm90aW8KLS0tIDNkUGJlNitSOUl4ZGtQejBVY0pS
            aEZjb2laNFNnWWs2cUtDNHk4cy9kRlEKnQhf7Go136y1j6+M7McvJr94iit6hTJ1
            eA3if5gbLnhy+F/BPXCjZR4yUoQy5+Wn0FL0F9C91PmIHOULv9x37g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T18:20:51Z"
    mac: ENC[AES256_GCM,data:0Vwwt5vPd+QIe20L2TuG2aNCVi0UEFPbWvnNszYcXvo+Ndb4/MRyzY0pwe1FYvhz+VLngqY1w5dB6LXeQ+hog7b3jPHj/2nGOBoG3i90qUE9Nr8Qw36W8A3gVsIyz0MdPjOgm0gKfiXYVzKvXAMqGS0NYLVbZ5+j0bmRWHHhMCs=,iv:CcXn4a8NQjBhcA7YLDhvV+3M5slnqa3WrZ5TQeB1uDw=,tag:XFYiNNCcV/t1spvOYAiATw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
