apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:0yFp,iv:oEluynoeE4XPYND6/dQMCk96uXLo9FuvbNa7pBO7uyA=,tag:cVCUgU/8jTMPWoSPjXb+wg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:a2GS1WWvl6JPgulslUdW9F2ECsPsTw==,iv:Dxa7PAbaaJae6n50WUgYDnGWVQNEbJquDttxhUN18rI=,tag:Sks1pZPmLN3cHpwcP/CRAA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:h49v,iv:r2niiytbIfzwgScd1cAOMFqUCr+kegQy+yrg622+iEM=,tag:xzTYu0cO5CebZx7KIZ7VVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQm9HeTlpT0hsOEVoMTU2
            cnA5ckw4ckZJOGUyWk42bWFTcVlQRkJDYnlNCk1xVlRNMm02RVBLKytoQzFtM3Nm
            RFJMbUxsSmJ4UDFSMzBBS1pZSUI3WU0KLS0tIERtVHF0SnJuUWNIVW5Ua0cwdUhW
            aklUWEg4Wk9uSXRJY1EwYjdKUVdVQmcKMOoZ9WZFRJJ9shVfQBTqPjGWh3Qw+4pB
            7CduZl4mqhAmvn9VvI9LKleTDavo6rq6y+P4FYPoQzPB462cXppK3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T17:36:33Z"
    mac: ENC[AES256_GCM,data:gRcMk12W5hMN0gnlN3dBWA6ww9y5cXZHJ0tLlNKn32Jivy+m5x2NqYlx+8Xjsoubqe8yPyVGSAMyPZddXQGJFp1WhDs+Kk+sr4M/y3znHDspxyp0yFuBQAoD4y+DJBS35JRa1jGqwrOqJnvS99PTeONN8OTHSwb5n5AIQ1oDt2o=,iv:kuXYPJU8yT7Rm0nz8W6WsnMAcF+uPcqaqvPx0U/l3wI=,tag:Z/MhUQIopOG1WayGea82QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:6BbrsyZgUGH9WyhiPaVdrg7TxntApjIahb6wHfHfqyw=,iv:rju78OFb42zF3ewQ4VR+5umN7ymNIS6tAL6N8DB9YrA=,tag:t2Vs6mr/yZd/G6BapiqWTw==,type:str]
    N8N_URL: ENC[AES256_GCM,data:AdZ6dxJCKe0F/5zk1AjhJgLTx9/262mMr8jvtg==,iv:OO/5uiuNlUnHnX05oAe8kh8nmE6OjUJeOTkKE2Z3vbU=,tag:aKkavk4QV06s35ujqxh7cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQm9HeTlpT0hsOEVoMTU2
            cnA5ckw4ckZJOGUyWk42bWFTcVlQRkJDYnlNCk1xVlRNMm02RVBLKytoQzFtM3Nm
            RFJMbUxsSmJ4UDFSMzBBS1pZSUI3WU0KLS0tIERtVHF0SnJuUWNIVW5Ua0cwdUhW
            aklUWEg4Wk9uSXRJY1EwYjdKUVdVQmcKMOoZ9WZFRJJ9shVfQBTqPjGWh3Qw+4pB
            7CduZl4mqhAmvn9VvI9LKleTDavo6rq6y+P4FYPoQzPB462cXppK3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T17:36:33Z"
    mac: ENC[AES256_GCM,data:gRcMk12W5hMN0gnlN3dBWA6ww9y5cXZHJ0tLlNKn32Jivy+m5x2NqYlx+8Xjsoubqe8yPyVGSAMyPZddXQGJFp1WhDs+Kk+sr4M/y3znHDspxyp0yFuBQAoD4y+DJBS35JRa1jGqwrOqJnvS99PTeONN8OTHSwb5n5AIQ1oDt2o=,iv:kuXYPJU8yT7Rm0nz8W6WsnMAcF+uPcqaqvPx0U/l3wI=,tag:Z/MhUQIopOG1WayGea82QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:h/BTui6ddFin/QFfzIvjvX8jR1e8NDRmwGSBS5HgLrfOXOoQPtJC3oq/zGQpx/EkI2jO4my1kHgq0K788NHwkj/cvx2HLqLMoH06nlp8ET7hp61x5tfV3T3Sot/bpM+wPj0WCNTjvyIV8keQnPrKVRqzJnES/gn+2SbQo3WmjaYxIGyE7978s4j5pGhCgw/vx7R8hqgSd8iq/4dqd/plk/x6u/w0uMvgxVEcXMhy0bIrWTU4lkP6IA==,iv:WttbsY0f+GnjPorcTG1k95Q+DS9Tzh3GgZZffD+tTdE=,tag:AMroW9It5P/1wbmWWpCJHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQm9HeTlpT0hsOEVoMTU2
            cnA5ckw4ckZJOGUyWk42bWFTcVlQRkJDYnlNCk1xVlRNMm02RVBLKytoQzFtM3Nm
            RFJMbUxsSmJ4UDFSMzBBS1pZSUI3WU0KLS0tIERtVHF0SnJuUWNIVW5Ua0cwdUhW
            aklUWEg4Wk9uSXRJY1EwYjdKUVdVQmcKMOoZ9WZFRJJ9shVfQBTqPjGWh3Qw+4pB
            7CduZl4mqhAmvn9VvI9LKleTDavo6rq6y+P4FYPoQzPB462cXppK3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T17:36:33Z"
    mac: ENC[AES256_GCM,data:gRcMk12W5hMN0gnlN3dBWA6ww9y5cXZHJ0tLlNKn32Jivy+m5x2NqYlx+8Xjsoubqe8yPyVGSAMyPZddXQGJFp1WhDs+Kk+sr4M/y3znHDspxyp0yFuBQAoD4y+DJBS35JRa1jGqwrOqJnvS99PTeONN8OTHSwb5n5AIQ1oDt2o=,iv:kuXYPJU8yT7Rm0nz8W6WsnMAcF+uPcqaqvPx0U/l3wI=,tag:Z/MhUQIopOG1WayGea82QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:25GGljaIWL86HoGMMXwhQGxejSq7Py7K9TtbLDp5Ezj8gQ==,iv:/vdv56yejf60toj7QdqfBsmfk1QG6/l9ZZgzYCPj6dE=,tag:gJTNQhhLbDdGAMkAYCxZgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQm9HeTlpT0hsOEVoMTU2
            cnA5ckw4ckZJOGUyWk42bWFTcVlQRkJDYnlNCk1xVlRNMm02RVBLKytoQzFtM3Nm
            RFJMbUxsSmJ4UDFSMzBBS1pZSUI3WU0KLS0tIERtVHF0SnJuUWNIVW5Ua0cwdUhW
            aklUWEg4Wk9uSXRJY1EwYjdKUVdVQmcKMOoZ9WZFRJJ9shVfQBTqPjGWh3Qw+4pB
            7CduZl4mqhAmvn9VvI9LKleTDavo6rq6y+P4FYPoQzPB462cXppK3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T17:36:33Z"
    mac: ENC[AES256_GCM,data:gRcMk12W5hMN0gnlN3dBWA6ww9y5cXZHJ0tLlNKn32Jivy+m5x2NqYlx+8Xjsoubqe8yPyVGSAMyPZddXQGJFp1WhDs+Kk+sr4M/y3znHDspxyp0yFuBQAoD4y+DJBS35JRa1jGqwrOqJnvS99PTeONN8OTHSwb5n5AIQ1oDt2o=,iv:kuXYPJU8yT7Rm0nz8W6WsnMAcF+uPcqaqvPx0U/l3wI=,tag:Z/MhUQIopOG1WayGea82QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: siyuan-secrets
    namespace: default
type: Opaque
stringData:
    AUTH_CODE: ENC[AES256_GCM,data:/zfsEIB+XzJ8+sZ3QSA9SNPKN4M=,iv:7C/Y50bYPaChUSGuM66ppWwnw0anyvE4TT4gTXGtCbA=,tag:qW3m3AZtLzpMMACm+hVdLw==,type:str]
    SIYUAN_URL: ENC[AES256_GCM,data:IbYCqFq/zQMFrQfeHIViJigvm6md85qI+dw7uEQ=,iv:22VjzKiX62fBBhdSX33CBPPJk3X9KEXZ5Jr9xRRuvvY=,tag:xUrgUE6hoMGfVOFk6+eZWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQm9HeTlpT0hsOEVoMTU2
            cnA5ckw4ckZJOGUyWk42bWFTcVlQRkJDYnlNCk1xVlRNMm02RVBLKytoQzFtM3Nm
            RFJMbUxsSmJ4UDFSMzBBS1pZSUI3WU0KLS0tIERtVHF0SnJuUWNIVW5Ua0cwdUhW
            aklUWEg4Wk9uSXRJY1EwYjdKUVdVQmcKMOoZ9WZFRJJ9shVfQBTqPjGWh3Qw+4pB
            7CduZl4mqhAmvn9VvI9LKleTDavo6rq6y+P4FYPoQzPB462cXppK3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T17:36:33Z"
    mac: ENC[AES256_GCM,data:gRcMk12W5hMN0gnlN3dBWA6ww9y5cXZHJ0tLlNKn32Jivy+m5x2NqYlx+8Xjsoubqe8yPyVGSAMyPZddXQGJFp1WhDs+Kk+sr4M/y3znHDspxyp0yFuBQAoD4y+DJBS35JRa1jGqwrOqJnvS99PTeONN8OTHSwb5n5AIQ1oDt2o=,iv:kuXYPJU8yT7Rm0nz8W6WsnMAcF+uPcqaqvPx0U/l3wI=,tag:Z/MhUQIopOG1WayGea82QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:x94pt+Zb7DFPCvgtTubIiuihK8rvGTX500I=,iv:NwOHzs/ytPMnAdPiXTl1hTMIHGJi3IJ304vO9jHY7sk=,tag:2amUpfDrhW5vgDYMMVPA3g==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:FkelZQlAsHksK85IZLZr5DdkmkRrEd5mypul2CvOYPU=,iv:LUPOVyACAtkZaH9exY2M9L3NQpXqd9WAcEBM6yfMhIE=,tag:5uglVK3dHfZhPwTv7LcS0A==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:+g4vkoZVQls3izfIucPmL2plDT/pwuscJl8ckXxBXeM=,iv:IJHMf1Y4AmdjUyDAvMSgtcZIevyiU/aHwg2K89XNFZY=,tag:70Im9T+wW/HNERecaNYLeQ==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:3uJWqg96b5jMPvaTuTrkGK5CE3RBA94FXNJWy1HkZ8Seak3K1gzb7TaJlNmGKmMsSPEV9kK9Z0o40IOtznk5aT2q/ivYixTVXHo78OSCgp+kt8SSaJ5S9uGct1uyGUsx7610yjpnDONYBW8PdnB+QyyYYYgzpFwXbL5PoY7WDHLae/UrKpLw+9qh8pH0lFFep7LxiiglrBFbfcvNFNQp6sFzyoZHlOroCZj4FNwXa3tX0XHCa+MxMXcYUjYJQvD1qdTYXnRHq32w1xRW6VEULzZXfWA81YhLsRtq+mNkzlsPYlXkwN743OXxWIaI,iv:E0tdG81e0wLDAclAsJ20myb6dZOojam5Dk9dxKHWGZk=,tag:bIkroqU4Ksj7hcQHwUpW5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQm9HeTlpT0hsOEVoMTU2
            cnA5ckw4ckZJOGUyWk42bWFTcVlQRkJDYnlNCk1xVlRNMm02RVBLKytoQzFtM3Nm
            RFJMbUxsSmJ4UDFSMzBBS1pZSUI3WU0KLS0tIERtVHF0SnJuUWNIVW5Ua0cwdUhW
            aklUWEg4Wk9uSXRJY1EwYjdKUVdVQmcKMOoZ9WZFRJJ9shVfQBTqPjGWh3Qw+4pB
            7CduZl4mqhAmvn9VvI9LKleTDavo6rq6y+P4FYPoQzPB462cXppK3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T17:36:33Z"
    mac: ENC[AES256_GCM,data:gRcMk12W5hMN0gnlN3dBWA6ww9y5cXZHJ0tLlNKn32Jivy+m5x2NqYlx+8Xjsoubqe8yPyVGSAMyPZddXQGJFp1WhDs+Kk+sr4M/y3znHDspxyp0yFuBQAoD4y+DJBS35JRa1jGqwrOqJnvS99PTeONN8OTHSwb5n5AIQ1oDt2o=,iv:kuXYPJU8yT7Rm0nz8W6WsnMAcF+uPcqaqvPx0U/l3wI=,tag:Z/MhUQIopOG1WayGea82QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
