apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:UDUk,iv:jka9aK1Ffx1WsLlTLXYVw7K1XGHZUtzc7h1LRZ9n/nE=,tag:3dgsLyAiU6kiSyTtJqPkZQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PgzyZoQAlIF/X91xh56uWzs5UqYslA==,iv:5V/yznEZB+/iG8bM9CIi3qaCOeUAxDOLu5Ucn1870WI=,tag:khkohdzhOUWgzQbQ5ziQSQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:WHQb,iv:49S/5eltV8Rj04f4xWlcjG9p8MykLQBzV+IvmaGhRg4=,tag:TwJrZEdYcGrCZ3fKYvJeXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYU1CLzg5N0VOUC9ETlE0
            dlpFbmY5dkZkVU81QzUxcW1SV0VreU5UWTBnCk8zNmk1NG9pajhsTk5qa0w2L0tw
            UnppL3c3NVhoVll2UGdsUk5vM3F6YncKLS0tIDd1aExNeFhtbFB0MFFLaWZzSlg2
            cDZwdE4xa2RSbjZxZFRmelYxeFFCZWcKUxLMUuYdpzWAdpnoXLe7ZxVVWPAdxA36
            wBIFNaWpy6K0uz3ZlqHQfEmGD0sYrfPsx08Ju16y5kPYMJt9Ds8+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:28:44Z"
    mac: ENC[AES256_GCM,data:93VoWiYoJPvdYDe1dsQ9DgMpSFNBM8Qn5+QbNDApVbsCs1jVJ6YQ2rCn1ORJs1Zu9gfkLVBmjtde99A/qNhQh0ZNlMY33AnylVb3QVM5tLTRxF2nX5OgyAA9+GVpBokI5QsstJqEwxNAjp7nR+0rsYPh8kfMcOB8S0ECNNYSupk=,iv:toZI8Lk0U2+jcBdKWdyjnLV72/aWoOA822TFkKxMN+0=,tag:zBidL6wsT465GmA+MwX3nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:khv3Qsqid5BrJlg1T/AcShvTsbVBJKeP0h4X7pNwcHA=,iv:xlYxXq7Q11Js2ZIZFRMK7BSatney7ER6uvVlRoE7g2c=,tag:vcdflAUnzByu2b+5MjqQRw==,type:str]
    N8N_URL: ENC[AES256_GCM,data:PNrmIpFGjBrmXPmsgBrpYpVW7nZJ2baM/9Z1lQ==,iv:DNj7IfeieuSJriqgImYXHxcWH8tCSYH3dBveKvIPPiA=,tag:Ed+E4xkTrAF1bwVyZ6Tadg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYU1CLzg5N0VOUC9ETlE0
            dlpFbmY5dkZkVU81QzUxcW1SV0VreU5UWTBnCk8zNmk1NG9pajhsTk5qa0w2L0tw
            UnppL3c3NVhoVll2UGdsUk5vM3F6YncKLS0tIDd1aExNeFhtbFB0MFFLaWZzSlg2
            cDZwdE4xa2RSbjZxZFRmelYxeFFCZWcKUxLMUuYdpzWAdpnoXLe7ZxVVWPAdxA36
            wBIFNaWpy6K0uz3ZlqHQfEmGD0sYrfPsx08Ju16y5kPYMJt9Ds8+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:28:44Z"
    mac: ENC[AES256_GCM,data:93VoWiYoJPvdYDe1dsQ9DgMpSFNBM8Qn5+QbNDApVbsCs1jVJ6YQ2rCn1ORJs1Zu9gfkLVBmjtde99A/qNhQh0ZNlMY33AnylVb3QVM5tLTRxF2nX5OgyAA9+GVpBokI5QsstJqEwxNAjp7nR+0rsYPh8kfMcOB8S0ECNNYSupk=,iv:toZI8Lk0U2+jcBdKWdyjnLV72/aWoOA822TFkKxMN+0=,tag:zBidL6wsT465GmA+MwX3nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:VYF6oO7IH6CDhOt7yn6OotvznwnNqk7iKEZAClIPd7ibWuR80lPMFWdLcvCIMYCwVMzerVGaFHOcwLHtWQJUYl7uPfF5ajCWxjejoQWIe6BxpbBtc+YRFoYtaK+QJT/LT4A8j4vbA1SBbHZKQFhiBHHnKHWdl/86A6EJiGDpJqgNwWAZfmeo/BUETFJpEWJ+UBl4DAyCvl1HvlYo+Yk+uB4DKL6c7wq6KMVX/jxPL7hdVbAsYLLTZA==,iv:km7auN4rL4z/eHLtEkWNvsVZieic+thu1CQUs5/wlUk=,tag:RVx5CarZxfvScDWk+talpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYU1CLzg5N0VOUC9ETlE0
            dlpFbmY5dkZkVU81QzUxcW1SV0VreU5UWTBnCk8zNmk1NG9pajhsTk5qa0w2L0tw
            UnppL3c3NVhoVll2UGdsUk5vM3F6YncKLS0tIDd1aExNeFhtbFB0MFFLaWZzSlg2
            cDZwdE4xa2RSbjZxZFRmelYxeFFCZWcKUxLMUuYdpzWAdpnoXLe7ZxVVWPAdxA36
            wBIFNaWpy6K0uz3ZlqHQfEmGD0sYrfPsx08Ju16y5kPYMJt9Ds8+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:28:44Z"
    mac: ENC[AES256_GCM,data:93VoWiYoJPvdYDe1dsQ9DgMpSFNBM8Qn5+QbNDApVbsCs1jVJ6YQ2rCn1ORJs1Zu9gfkLVBmjtde99A/qNhQh0ZNlMY33AnylVb3QVM5tLTRxF2nX5OgyAA9+GVpBokI5QsstJqEwxNAjp7nR+0rsYPh8kfMcOB8S0ECNNYSupk=,iv:toZI8Lk0U2+jcBdKWdyjnLV72/aWoOA822TFkKxMN+0=,tag:zBidL6wsT465GmA+MwX3nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:E7w8k0+4L1owYOHMO/Heg+gtPj00qhuUYHTE,iv:of7b6dpxsickh4qUTQK63UbvyeR/YmNfSdxsTxCgmHo=,tag:qoqLbvmlne7tRtfxR6IvwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYU1CLzg5N0VOUC9ETlE0
            dlpFbmY5dkZkVU81QzUxcW1SV0VreU5UWTBnCk8zNmk1NG9pajhsTk5qa0w2L0tw
            UnppL3c3NVhoVll2UGdsUk5vM3F6YncKLS0tIDd1aExNeFhtbFB0MFFLaWZzSlg2
            cDZwdE4xa2RSbjZxZFRmelYxeFFCZWcKUxLMUuYdpzWAdpnoXLe7ZxVVWPAdxA36
            wBIFNaWpy6K0uz3ZlqHQfEmGD0sYrfPsx08Ju16y5kPYMJt9Ds8+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:28:44Z"
    mac: ENC[AES256_GCM,data:93VoWiYoJPvdYDe1dsQ9DgMpSFNBM8Qn5+QbNDApVbsCs1jVJ6YQ2rCn1ORJs1Zu9gfkLVBmjtde99A/qNhQh0ZNlMY33AnylVb3QVM5tLTRxF2nX5OgyAA9+GVpBokI5QsstJqEwxNAjp7nR+0rsYPh8kfMcOB8S0ECNNYSupk=,iv:toZI8Lk0U2+jcBdKWdyjnLV72/aWoOA822TFkKxMN+0=,tag:zBidL6wsT465GmA+MwX3nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:AMgRnK4XXKCqoRiChmO80CSOxpDcPIx7fnQY,iv:7BVM3LaAxAQeiQ/NqGQaTSOk8ysXpD17qLcfghtOp/Y=,tag:yJyJl1kbC/OdNWDG/HcGgQ==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:uFv/ddBf/DNgdYKJILp1v14C5KOVR1BHSmhcoo+GeXU=,iv:5iMuzZMd16yok129wvCv4jwxpZuaSt1+2QaJvXgiFQA=,tag:INBDHeoCrevJ4emIzAzVMg==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:cT110+Dmj2ceJp2Lkam8QfofpH0PX+fygk/BceAq2Go=,iv:h6gDajLg6+RLv89PpADRdZUVUy0FKD0lC3CIhVOqMlo=,tag:XoNa5ysm0HaCrlIykoDHQQ==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:9PjL1RPxxMk8ryYIvY9PL3FtMr+kQiDCrvnbikR2fdH62QKND+MF8B3q0MYvSo7nHxbE0rnmyr/r3SNvMiVUcIAletBivB7K+MgmPB6xjWbtgog8+JHFULbFqgHJ2mUeq0sn6xiz7Xf00UrnjbTUKCHnydNVOwaoTNx4SAXg3OIe1JKN4PosMpY7t3LduHGevMO22cjSHpGHLuBRA7blD2MDNadSC79rJ+6R4RCMzCCCvc9Ek/1tiMB+LAlFgsu/8QD9zCc13dS1uF4PxxopcGxP3vKi8OVT/LMs3rrEZm5327BFmtAEl1qCMAr9,iv:TjnPse4vriKTDTQf2gUBWVIqXbeqaNFIHVzCA6+PdB0=,tag:0r199QI8XiI62fujol2F1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYU1CLzg5N0VOUC9ETlE0
            dlpFbmY5dkZkVU81QzUxcW1SV0VreU5UWTBnCk8zNmk1NG9pajhsTk5qa0w2L0tw
            UnppL3c3NVhoVll2UGdsUk5vM3F6YncKLS0tIDd1aExNeFhtbFB0MFFLaWZzSlg2
            cDZwdE4xa2RSbjZxZFRmelYxeFFCZWcKUxLMUuYdpzWAdpnoXLe7ZxVVWPAdxA36
            wBIFNaWpy6K0uz3ZlqHQfEmGD0sYrfPsx08Ju16y5kPYMJt9Ds8+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:28:44Z"
    mac: ENC[AES256_GCM,data:93VoWiYoJPvdYDe1dsQ9DgMpSFNBM8Qn5+QbNDApVbsCs1jVJ6YQ2rCn1ORJs1Zu9gfkLVBmjtde99A/qNhQh0ZNlMY33AnylVb3QVM5tLTRxF2nX5OgyAA9+GVpBokI5QsstJqEwxNAjp7nR+0rsYPh8kfMcOB8S0ECNNYSupk=,iv:toZI8Lk0U2+jcBdKWdyjnLV72/aWoOA822TFkKxMN+0=,tag:zBidL6wsT465GmA+MwX3nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:ypnTWvBnbA==,iv:u3feMhH/fahXj3rtyOuG9SBuCMbwmWlm5Pfu7wyxtyw=,tag:v/7Iv4JUihBKW1p5GSiH7w==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:KndqIfV3wbVBDa+6JeUIv0vrGIo=,iv:QomIkmrhEJmlNkOKoS6nFm3XaZjRfSubmWz84c5NeVA=,tag:KXVcExk8vkGw7uqrJ8O3jw==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:n++fUcWgvveV1MZq+ZrKhRkHh3qmYXuTUh1O5F9/npRXyp6XGw==,iv:HAKQTTTpRghBDVAXXr614CkfRiCfqQfQPF/nfusadiM=,tag:8cuQ4aQDKTQBtCFk/K7RzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYU1CLzg5N0VOUC9ETlE0
            dlpFbmY5dkZkVU81QzUxcW1SV0VreU5UWTBnCk8zNmk1NG9pajhsTk5qa0w2L0tw
            UnppL3c3NVhoVll2UGdsUk5vM3F6YncKLS0tIDd1aExNeFhtbFB0MFFLaWZzSlg2
            cDZwdE4xa2RSbjZxZFRmelYxeFFCZWcKUxLMUuYdpzWAdpnoXLe7ZxVVWPAdxA36
            wBIFNaWpy6K0uz3ZlqHQfEmGD0sYrfPsx08Ju16y5kPYMJt9Ds8+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:28:44Z"
    mac: ENC[AES256_GCM,data:93VoWiYoJPvdYDe1dsQ9DgMpSFNBM8Qn5+QbNDApVbsCs1jVJ6YQ2rCn1ORJs1Zu9gfkLVBmjtde99A/qNhQh0ZNlMY33AnylVb3QVM5tLTRxF2nX5OgyAA9+GVpBokI5QsstJqEwxNAjp7nR+0rsYPh8kfMcOB8S0ECNNYSupk=,iv:toZI8Lk0U2+jcBdKWdyjnLV72/aWoOA822TFkKxMN+0=,tag:zBidL6wsT465GmA+MwX3nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:VzQXd5RGKbxHquKU8EuGWVQWCNPfIJTuzSYZnJOFUqGLOu7OfTP8OhEYnq8=,iv:GNjjJgKfr0Iu20yGfXTArodU+DFvGYQL20/PZ9V1pts=,tag:KYurZ0fkvZ0POVhISER5jg==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:5mAi/cx/oUmiPghUX0vm0KSroYLwYt0BhGhz,iv:f6BxfvGg3iuby1e92y0ULTs2NuBlPaPgUYq29TLVhDQ=,tag:OJN+g9M1N4huFoNoRR2fUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYU1CLzg5N0VOUC9ETlE0
            dlpFbmY5dkZkVU81QzUxcW1SV0VreU5UWTBnCk8zNmk1NG9pajhsTk5qa0w2L0tw
            UnppL3c3NVhoVll2UGdsUk5vM3F6YncKLS0tIDd1aExNeFhtbFB0MFFLaWZzSlg2
            cDZwdE4xa2RSbjZxZFRmelYxeFFCZWcKUxLMUuYdpzWAdpnoXLe7ZxVVWPAdxA36
            wBIFNaWpy6K0uz3ZlqHQfEmGD0sYrfPsx08Ju16y5kPYMJt9Ds8+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:28:44Z"
    mac: ENC[AES256_GCM,data:93VoWiYoJPvdYDe1dsQ9DgMpSFNBM8Qn5+QbNDApVbsCs1jVJ6YQ2rCn1ORJs1Zu9gfkLVBmjtde99A/qNhQh0ZNlMY33AnylVb3QVM5tLTRxF2nX5OgyAA9+GVpBokI5QsstJqEwxNAjp7nR+0rsYPh8kfMcOB8S0ECNNYSupk=,iv:toZI8Lk0U2+jcBdKWdyjnLV72/aWoOA822TFkKxMN+0=,tag:zBidL6wsT465GmA+MwX3nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: default
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:jRe8ZPbwmbuYdC+/HHl8Irgalwaqj3HzBs08mmWwUarKVAGyPvku1w==,iv:CQOL6ComgSugKJKnZz3ZI3RpTdOeAFP+jGLNgyhP5HM=,tag:LsHSDmGh78uzP3TSiornCA==,type:str]
    RENOVATE_GITHUB_TOKEN: ENC[AES256_GCM,data:j1SHJMGtgBeSLujH8PmOt41bMZfu5uSbGr83LDwCopPrBcAjvR8sHQ==,iv:IlMsjHF/5RLWEZk1qZqGssJwKZB8hyxx9xr46KST98k=,tag:J9Iwu5sQLYLy64MrBar9uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYU1CLzg5N0VOUC9ETlE0
            dlpFbmY5dkZkVU81QzUxcW1SV0VreU5UWTBnCk8zNmk1NG9pajhsTk5qa0w2L0tw
            UnppL3c3NVhoVll2UGdsUk5vM3F6YncKLS0tIDd1aExNeFhtbFB0MFFLaWZzSlg2
            cDZwdE4xa2RSbjZxZFRmelYxeFFCZWcKUxLMUuYdpzWAdpnoXLe7ZxVVWPAdxA36
            wBIFNaWpy6K0uz3ZlqHQfEmGD0sYrfPsx08Ju16y5kPYMJt9Ds8+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:28:44Z"
    mac: ENC[AES256_GCM,data:93VoWiYoJPvdYDe1dsQ9DgMpSFNBM8Qn5+QbNDApVbsCs1jVJ6YQ2rCn1ORJs1Zu9gfkLVBmjtde99A/qNhQh0ZNlMY33AnylVb3QVM5tLTRxF2nX5OgyAA9+GVpBokI5QsstJqEwxNAjp7nR+0rsYPh8kfMcOB8S0ECNNYSupk=,iv:toZI8Lk0U2+jcBdKWdyjnLV72/aWoOA822TFkKxMN+0=,tag:zBidL6wsT465GmA+MwX3nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-secrets
    namespace: default
type: Opaque
stringData:
    JELLYFIN_KEY: ENC[AES256_GCM,data:0Um8VTnS7JaR1sJR3TGT+AFJX3wMw8GIEw7QQl+lYb8=,iv:14XrkXEjZnJE7E/6FoK+isTN8OSTWD9DOfbaeRm/LZk=,tag:5dWq1FDBNmVeFdRCfdFUZg==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:GxznL7dje6kxgwTS/ofHC0Uj34MNr7/QoNc=,iv:ca2yrHXn7YLcW+mboVB0ENKUT8AmGuJ8E9LdyVYyNLM=,tag:L60UNPp87uO5OSfKoR5YZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYU1CLzg5N0VOUC9ETlE0
            dlpFbmY5dkZkVU81QzUxcW1SV0VreU5UWTBnCk8zNmk1NG9pajhsTk5qa0w2L0tw
            UnppL3c3NVhoVll2UGdsUk5vM3F6YncKLS0tIDd1aExNeFhtbFB0MFFLaWZzSlg2
            cDZwdE4xa2RSbjZxZFRmelYxeFFCZWcKUxLMUuYdpzWAdpnoXLe7ZxVVWPAdxA36
            wBIFNaWpy6K0uz3ZlqHQfEmGD0sYrfPsx08Ju16y5kPYMJt9Ds8+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:28:44Z"
    mac: ENC[AES256_GCM,data:93VoWiYoJPvdYDe1dsQ9DgMpSFNBM8Qn5+QbNDApVbsCs1jVJ6YQ2rCn1ORJs1Zu9gfkLVBmjtde99A/qNhQh0ZNlMY33AnylVb3QVM5tLTRxF2nX5OgyAA9+GVpBokI5QsstJqEwxNAjp7nR+0rsYPh8kfMcOB8S0ECNNYSupk=,iv:toZI8Lk0U2+jcBdKWdyjnLV72/aWoOA822TFkKxMN+0=,tag:zBidL6wsT465GmA+MwX3nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-secrets
    namespace: default
type: Opaque
stringData:
    HA_TOKEN: ENC[AES256_GCM,data:XooYc32GBaMJsrcfwsVAn5M3NvbFZ3AVvIcf7l8Dvldz+p+o4g0/qKdPnS55B9A8ZFJB+RS8fcPG41gOiNvqWLoDuF8HdI3mLKABt96B79QdvgzkWETyylv1N0v8xZv/nIrYqMvEvRUs2CwF4I5B0+ZqvrDNxr9/PbdipcFRdMMU0LSFbwzXwO1C6tQD5wAZOoGY6ADMCiELh9PstSsLCvpZpR0uQvB89clIqr1R5kydSIgemHuy,iv:Hzck47KX6aUUYyLa4cb/C4OaidrWZqsAK7hxM6eX1/8=,tag:E6uNmFJyy8fBamOQraSotA==,type:str]
    HA_IP: ENC[AES256_GCM,data:lVsh9SVaSyNjcsdmwMcdnpF8JG3Eo56vwy4=,iv:rsJQsfIjEMrHFdHyOfoEUsGz9CfwEK4XGnhZ9YZlFps=,tag:yDpUCx9F+bOUUlQec/CGfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYU1CLzg5N0VOUC9ETlE0
            dlpFbmY5dkZkVU81QzUxcW1SV0VreU5UWTBnCk8zNmk1NG9pajhsTk5qa0w2L0tw
            UnppL3c3NVhoVll2UGdsUk5vM3F6YncKLS0tIDd1aExNeFhtbFB0MFFLaWZzSlg2
            cDZwdE4xa2RSbjZxZFRmelYxeFFCZWcKUxLMUuYdpzWAdpnoXLe7ZxVVWPAdxA36
            wBIFNaWpy6K0uz3ZlqHQfEmGD0sYrfPsx08Ju16y5kPYMJt9Ds8+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:28:44Z"
    mac: ENC[AES256_GCM,data:93VoWiYoJPvdYDe1dsQ9DgMpSFNBM8Qn5+QbNDApVbsCs1jVJ6YQ2rCn1ORJs1Zu9gfkLVBmjtde99A/qNhQh0ZNlMY33AnylVb3QVM5tLTRxF2nX5OgyAA9+GVpBokI5QsstJqEwxNAjp7nR+0rsYPh8kfMcOB8S0ECNNYSupk=,iv:toZI8Lk0U2+jcBdKWdyjnLV72/aWoOA822TFkKxMN+0=,tag:zBidL6wsT465GmA+MwX3nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
