apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:IdkU,iv:j5kK8G4isOmMmxTAVecUO3QM2lACoOx9BRC4hjEOHRE=,tag:jviCkNmkd1TMPPsYXYvjhg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:pIlOPtf1w3mJDmLWlI55iGrzBZ8ekw==,iv:7W4yrHyQhCCtms+MIyQAKpaj0EEoKaw4bRGK0QgufW4=,tag:3Ae07QAZw0eCmNLbE4RopQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:/Rh0,iv:pPzLfVeYZu3yPe7gQLx7aRvR4F9QQjc29eeWJj3St1k=,tag:Dm93O8qTAQY0si1rJi5HIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcEMrdnZiQkNTcUFmcDFh
            LzBiNURYVkhpWU1oeE1kcVB4cndNbGUxQmlJCmFnaTB6RmpKM0M1WlpBQ1R6SjB0
            MGZjdXlwUytISHNWT3V0Z3Q4SW5OemsKLS0tIHR5eENGd01BVWR5RzV6WVZMa2tu
            dUNmei92VXVBN0JnVmozVUlFMVdqUXMKmdrHGw7FY93ER3TozNWQ+7M5GA1miHPx
            yNvgeLH+Iwx6r3DfgcOXvxcgbpDhxtUvZ5AkCbg/pZYh7c1aFiBFdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:31:02Z"
    mac: ENC[AES256_GCM,data:9uBvH2tDNb5WshQV34uWb/3yJCnbS5iER6kSf59W2g1rjc6OswFQqGdhSs8wG6P9MUFG0T++ojbsS2Hvj0eafetIyq2JDdkHZdWO4LFoEkKy9YAj3k9CCQMawyTZHT8wHy+cbQ5+TTiMUMh6ZLwFEGzrv/zbHsAxkBJbkMqYoRQ=,iv:2zomqoggm/PocBCR0ZnLUtN9wns5DFGoU7gsENe0QFs=,tag:pXy7tfQo68Pr8tcD63DkHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:CFNMJuDI8mHZzExqCLqonPYQTmJ6edq8EalUIEJPVI0=,iv:6wPjl8m68GIIZwz9RwFAGvaqDJkHEOcF3lA1S6yPJUU=,tag:FfqYe1lazAV3Fc7c4OQjOg==,type:str]
    N8N_URL: ENC[AES256_GCM,data:XHebs21dq2Uu4YN10pLYZnumrto/fmJzLY0lZQ==,iv:WT9rrVueg+wPElovVqvVMO8IhLUJGozM3e74FAg1WgI=,tag:F5SpzGzkC2KE3d0RDw5zjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcEMrdnZiQkNTcUFmcDFh
            LzBiNURYVkhpWU1oeE1kcVB4cndNbGUxQmlJCmFnaTB6RmpKM0M1WlpBQ1R6SjB0
            MGZjdXlwUytISHNWT3V0Z3Q4SW5OemsKLS0tIHR5eENGd01BVWR5RzV6WVZMa2tu
            dUNmei92VXVBN0JnVmozVUlFMVdqUXMKmdrHGw7FY93ER3TozNWQ+7M5GA1miHPx
            yNvgeLH+Iwx6r3DfgcOXvxcgbpDhxtUvZ5AkCbg/pZYh7c1aFiBFdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:31:02Z"
    mac: ENC[AES256_GCM,data:9uBvH2tDNb5WshQV34uWb/3yJCnbS5iER6kSf59W2g1rjc6OswFQqGdhSs8wG6P9MUFG0T++ojbsS2Hvj0eafetIyq2JDdkHZdWO4LFoEkKy9YAj3k9CCQMawyTZHT8wHy+cbQ5+TTiMUMh6ZLwFEGzrv/zbHsAxkBJbkMqYoRQ=,iv:2zomqoggm/PocBCR0ZnLUtN9wns5DFGoU7gsENe0QFs=,tag:pXy7tfQo68Pr8tcD63DkHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:4YzOTROb8jIOjtYVUbuZ+cR0uh9PHc3rVz0mYIfaNESn6+cmwPxSPkL0gBoyWjDQ+SyJkv2KyBK/FSj+9FLycVELAXPzrAR66ogzpLzVqc/7pTX79/nn15Xotv9rMn5lODpI+C3pR+mEfMOCVed+WjazvxAOsdO5n+pZT+2y4qX5oRA5FyCXrOU0F82sJ7ZLYDlxr+SRJyNbZjEgjkOXyv3R+7lz0DCv9f5DmgLeOZMH9n0Bi7jclA==,iv:mC4XuhQ/xcnB/gTzSc2x3U3dNFbFlOUDajAOLSM++mw=,tag:05uRa3XsI4xJU4soF0+PdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcEMrdnZiQkNTcUFmcDFh
            LzBiNURYVkhpWU1oeE1kcVB4cndNbGUxQmlJCmFnaTB6RmpKM0M1WlpBQ1R6SjB0
            MGZjdXlwUytISHNWT3V0Z3Q4SW5OemsKLS0tIHR5eENGd01BVWR5RzV6WVZMa2tu
            dUNmei92VXVBN0JnVmozVUlFMVdqUXMKmdrHGw7FY93ER3TozNWQ+7M5GA1miHPx
            yNvgeLH+Iwx6r3DfgcOXvxcgbpDhxtUvZ5AkCbg/pZYh7c1aFiBFdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:31:02Z"
    mac: ENC[AES256_GCM,data:9uBvH2tDNb5WshQV34uWb/3yJCnbS5iER6kSf59W2g1rjc6OswFQqGdhSs8wG6P9MUFG0T++ojbsS2Hvj0eafetIyq2JDdkHZdWO4LFoEkKy9YAj3k9CCQMawyTZHT8wHy+cbQ5+TTiMUMh6ZLwFEGzrv/zbHsAxkBJbkMqYoRQ=,iv:2zomqoggm/PocBCR0ZnLUtN9wns5DFGoU7gsENe0QFs=,tag:pXy7tfQo68Pr8tcD63DkHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:K6OQOcldGxivG//FUqwMMZwNCSVLttnAr7YXRbOYHQr6uQ==,iv:hzOyy0+uC9JBrvwDSrGNaw/dm3va5/0k1esxrHP8oHM=,tag:SnSGgEbqE8bXoeERKfvKnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcEMrdnZiQkNTcUFmcDFh
            LzBiNURYVkhpWU1oeE1kcVB4cndNbGUxQmlJCmFnaTB6RmpKM0M1WlpBQ1R6SjB0
            MGZjdXlwUytISHNWT3V0Z3Q4SW5OemsKLS0tIHR5eENGd01BVWR5RzV6WVZMa2tu
            dUNmei92VXVBN0JnVmozVUlFMVdqUXMKmdrHGw7FY93ER3TozNWQ+7M5GA1miHPx
            yNvgeLH+Iwx6r3DfgcOXvxcgbpDhxtUvZ5AkCbg/pZYh7c1aFiBFdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:31:02Z"
    mac: ENC[AES256_GCM,data:9uBvH2tDNb5WshQV34uWb/3yJCnbS5iER6kSf59W2g1rjc6OswFQqGdhSs8wG6P9MUFG0T++ojbsS2Hvj0eafetIyq2JDdkHZdWO4LFoEkKy9YAj3k9CCQMawyTZHT8wHy+cbQ5+TTiMUMh6ZLwFEGzrv/zbHsAxkBJbkMqYoRQ=,iv:2zomqoggm/PocBCR0ZnLUtN9wns5DFGoU7gsENe0QFs=,tag:pXy7tfQo68Pr8tcD63DkHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: siyuan-secrets
    namespace: default
type: Opaque
stringData:
    AUTH_CODE: ENC[AES256_GCM,data:h0rQYeWZUHGA0Fr8xnunFLeVCV4=,iv:JPTbz3pMifdDKSAPAOXZgSX+6ElY4C2c6GvyES5meRQ=,tag:S138I4Ar8myJOj02k/lhUA==,type:str]
    SIYUAN_URL: ENC[AES256_GCM,data:+36Oz9yT8d9rfO/rdifeAQtPNZRctJ6LpYgUgHs=,iv:NNJjFVZRwcukR2XowbzaunkqJG+TyYxC2Ztk0Hjl8Wk=,tag:pmAeLExoqf6ku13R0Cavxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcEMrdnZiQkNTcUFmcDFh
            LzBiNURYVkhpWU1oeE1kcVB4cndNbGUxQmlJCmFnaTB6RmpKM0M1WlpBQ1R6SjB0
            MGZjdXlwUytISHNWT3V0Z3Q4SW5OemsKLS0tIHR5eENGd01BVWR5RzV6WVZMa2tu
            dUNmei92VXVBN0JnVmozVUlFMVdqUXMKmdrHGw7FY93ER3TozNWQ+7M5GA1miHPx
            yNvgeLH+Iwx6r3DfgcOXvxcgbpDhxtUvZ5AkCbg/pZYh7c1aFiBFdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:31:02Z"
    mac: ENC[AES256_GCM,data:9uBvH2tDNb5WshQV34uWb/3yJCnbS5iER6kSf59W2g1rjc6OswFQqGdhSs8wG6P9MUFG0T++ojbsS2Hvj0eafetIyq2JDdkHZdWO4LFoEkKy9YAj3k9CCQMawyTZHT8wHy+cbQ5+TTiMUMh6ZLwFEGzrv/zbHsAxkBJbkMqYoRQ=,iv:2zomqoggm/PocBCR0ZnLUtN9wns5DFGoU7gsENe0QFs=,tag:pXy7tfQo68Pr8tcD63DkHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:vh080uGVd8hjLuFQuN2yRzyXKnM3fK7Q6w06,iv:nXCi0gfW2QP6Qg0aZUF2nyPlsGAmYcQkjVtn6RY65uE=,tag:kfNCBQEgyL9VMZDnCufjbQ==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:pFbRxBLWJuH029ANTiIt7m+TV3o9CoyOud0vdKOLe6E=,iv:W+h1udvojbcDd1gnuw8mNkjh6TtCkpwn/j5KTP29lWM=,tag:KJknhNFBDImSl4TC+Jt1lA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:67cwYOtREKXKFeBtue0G+j2zqjF6vyva7owRl+iMUmI=,iv:lHCHJMVIBzpwxlKtrBGgEvNEc6ncuzEeQft2FFzsmgs=,tag:NV/yXONK6p23pbQVHkQQfQ==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:o1SucA+EQ1x2CIp6kLCSXpO0TBfeRViJBZa0bNvqTG3NWEpYBtu61faeOE+U27hN8pbQyYzixu1J5xJCGu+/XBQhgGjySioTyKLwQ8SMa/7GxZPomK0YNc8rlMVF8DOaM5AcC3HXS0R9eQdJ50uhpq0sC8qXwFdOdUJv9AD4sQmLbxXJQgYyuSDFBHpiX9BBwmHe2MctXa5MMYEFeUGCtsC9bbgSH1QwrdyZLN3wAoMmq81KxjH45SBYwsJTrfxQVddxeuWP8I97KOw58D3/01VfLR4vsG7yF+5l9LEbE5gYGlJuz/gZS4YnaqeR,iv:fRHzYiMVnV/mE9NkpaZ9Gq8tVSd6TyQdBmf+wuFBe8o=,tag:DsaolR++nXyGWimAfi6KIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcEMrdnZiQkNTcUFmcDFh
            LzBiNURYVkhpWU1oeE1kcVB4cndNbGUxQmlJCmFnaTB6RmpKM0M1WlpBQ1R6SjB0
            MGZjdXlwUytISHNWT3V0Z3Q4SW5OemsKLS0tIHR5eENGd01BVWR5RzV6WVZMa2tu
            dUNmei92VXVBN0JnVmozVUlFMVdqUXMKmdrHGw7FY93ER3TozNWQ+7M5GA1miHPx
            yNvgeLH+Iwx6r3DfgcOXvxcgbpDhxtUvZ5AkCbg/pZYh7c1aFiBFdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:31:02Z"
    mac: ENC[AES256_GCM,data:9uBvH2tDNb5WshQV34uWb/3yJCnbS5iER6kSf59W2g1rjc6OswFQqGdhSs8wG6P9MUFG0T++ojbsS2Hvj0eafetIyq2JDdkHZdWO4LFoEkKy9YAj3k9CCQMawyTZHT8wHy+cbQ5+TTiMUMh6ZLwFEGzrv/zbHsAxkBJbkMqYoRQ=,iv:2zomqoggm/PocBCR0ZnLUtN9wns5DFGoU7gsENe0QFs=,tag:pXy7tfQo68Pr8tcD63DkHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:K1vAbgF4mg==,iv:M3WY3q/8FS6fki+TchHwd3hfOa8OlND2W3fF5W1CxHw=,tag:49p5X2gyZMlvQp1/Uxjp+g==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:tMquMOQQQvmhG/Lss8pn2ucbhig=,iv:OhclaSt6yt//Amggm9YcpGkQ7hNPXBcyZSdNhlibhKA=,tag:YZMYviXWWL/MA1ElLQxYjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcEMrdnZiQkNTcUFmcDFh
            LzBiNURYVkhpWU1oeE1kcVB4cndNbGUxQmlJCmFnaTB6RmpKM0M1WlpBQ1R6SjB0
            MGZjdXlwUytISHNWT3V0Z3Q4SW5OemsKLS0tIHR5eENGd01BVWR5RzV6WVZMa2tu
            dUNmei92VXVBN0JnVmozVUlFMVdqUXMKmdrHGw7FY93ER3TozNWQ+7M5GA1miHPx
            yNvgeLH+Iwx6r3DfgcOXvxcgbpDhxtUvZ5AkCbg/pZYh7c1aFiBFdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:31:02Z"
    mac: ENC[AES256_GCM,data:9uBvH2tDNb5WshQV34uWb/3yJCnbS5iER6kSf59W2g1rjc6OswFQqGdhSs8wG6P9MUFG0T++ojbsS2Hvj0eafetIyq2JDdkHZdWO4LFoEkKy9YAj3k9CCQMawyTZHT8wHy+cbQ5+TTiMUMh6ZLwFEGzrv/zbHsAxkBJbkMqYoRQ=,iv:2zomqoggm/PocBCR0ZnLUtN9wns5DFGoU7gsENe0QFs=,tag:pXy7tfQo68Pr8tcD63DkHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
