apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ihir,iv:ISHHQ0AFSDOpjkNDrCKHSuowp4i3PZtqpzYbQxAgTpw=,tag:brfx4vI5b7I3AbLUu6rJqQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:sCC7JtRn9Lzry5mfRzBnJS6Yf/3coQ==,iv:BhB+iYDvwWG4yTtwWoXq7kBwLaR42D+ajxcth/c0+jA=,tag:+x4S9+U0M8cKdZmJ+lkz4w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:PnqX,iv:CYHs6KzufEemjOEJvol9LxMmdKSu7GwGpUSj3Dt0ZH4=,tag:bNWoR0hxPIHZ+PyA/YcncQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZUhJZE40RktWbDdPUlJr
            YkhTc3lxd2h5ZEIreXpJZUlUN3EzaGdKcVFRCitmL2VxYXVCbjFvQ0VXTXZGQUsy
            VnZMNng4anJObWRLdFNIZEZQNFdWRlEKLS0tIFZmUG93QmdaeWhDYzJxSDFGNysv
            clJzZzhVWlFvY1FpdWJqMDJuUjBjQWsK02DDAG+fDY0HBl0u4Cp73Y66XUZ4eDLP
            xsvZF6iWOCkBRKgF1As9dxBLrrZIkP3tw0M7WuWl+NqxDeZ88lOZqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:45:29Z"
    mac: ENC[AES256_GCM,data:5FyZT22smhmu+LpdTF1PVLTcS9joouRCc37D1VZ04grqUOpx1WmHXbkTyvHogAypTRa7nU/4FYP6BubZ+ZqfxlwiYxOUDKGQyM4t6SDVHK2PP8sqdydmmG6jOD6wHsNbqS8kbaxvuKyWV2H3BNQ5hFsEuhom7A4zbmOFVtJkL+c=,iv:9CJSSIA5ke8s77FHqSh3hi9gaHSpI4flhafrlENZ49s=,tag:eWayDbPVcxjldyhtvqHEcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:uCNL3ipECnmKYMhB1gqFGk6n4CHMMQnQaDLoVoDhwyY=,iv:sn+bANeMvj29QU5Hhbmx3INdT5d8/WolkywcvIQZYes=,tag:BGi1JzB6keKcvx5VX/RYvw==,type:str]
    N8N_URL: ENC[AES256_GCM,data:u0BxjUUHAFFnnOD0soTkoAJqbH7chi2xahitxw==,iv:OY7bpKAs++P9b7rONel32g/9TL8EdN68+aLK2f0vffc=,tag:YuRfMy5xEDLii0l3NQGNew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZUhJZE40RktWbDdPUlJr
            YkhTc3lxd2h5ZEIreXpJZUlUN3EzaGdKcVFRCitmL2VxYXVCbjFvQ0VXTXZGQUsy
            VnZMNng4anJObWRLdFNIZEZQNFdWRlEKLS0tIFZmUG93QmdaeWhDYzJxSDFGNysv
            clJzZzhVWlFvY1FpdWJqMDJuUjBjQWsK02DDAG+fDY0HBl0u4Cp73Y66XUZ4eDLP
            xsvZF6iWOCkBRKgF1As9dxBLrrZIkP3tw0M7WuWl+NqxDeZ88lOZqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:45:29Z"
    mac: ENC[AES256_GCM,data:5FyZT22smhmu+LpdTF1PVLTcS9joouRCc37D1VZ04grqUOpx1WmHXbkTyvHogAypTRa7nU/4FYP6BubZ+ZqfxlwiYxOUDKGQyM4t6SDVHK2PP8sqdydmmG6jOD6wHsNbqS8kbaxvuKyWV2H3BNQ5hFsEuhom7A4zbmOFVtJkL+c=,iv:9CJSSIA5ke8s77FHqSh3hi9gaHSpI4flhafrlENZ49s=,tag:eWayDbPVcxjldyhtvqHEcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:NRv9hf1eUpMdt6oGxeXnp+G/unotVfsLh7WJxTS/xPnQKwGs3Mjtkfq7HEWO2/UFPhN4NsyXsSjZwL7lM+Knac13l0/OudhqOtTc/RGANNrXL0PR+a0ZDvEAPOFeUvQF8kDTFpmUXvOh0+e+19fDuPceA+HMGnd9BaoGNz6TYQTZ/0Z/DbBaUAUrfMVywFfE8XKGRZRisawmzUYPDq3VZLyae+MMksMoAJ6wgHemD+IEUXcz8hu7Dw==,iv:t2aO2PqaikBpVGXXCvhDWPw+3dNKMbYUkcRfx62kdow=,tag:4TrJZAf1Z9MgMtwNnPprzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZUhJZE40RktWbDdPUlJr
            YkhTc3lxd2h5ZEIreXpJZUlUN3EzaGdKcVFRCitmL2VxYXVCbjFvQ0VXTXZGQUsy
            VnZMNng4anJObWRLdFNIZEZQNFdWRlEKLS0tIFZmUG93QmdaeWhDYzJxSDFGNysv
            clJzZzhVWlFvY1FpdWJqMDJuUjBjQWsK02DDAG+fDY0HBl0u4Cp73Y66XUZ4eDLP
            xsvZF6iWOCkBRKgF1As9dxBLrrZIkP3tw0M7WuWl+NqxDeZ88lOZqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:45:29Z"
    mac: ENC[AES256_GCM,data:5FyZT22smhmu+LpdTF1PVLTcS9joouRCc37D1VZ04grqUOpx1WmHXbkTyvHogAypTRa7nU/4FYP6BubZ+ZqfxlwiYxOUDKGQyM4t6SDVHK2PP8sqdydmmG6jOD6wHsNbqS8kbaxvuKyWV2H3BNQ5hFsEuhom7A4zbmOFVtJkL+c=,iv:9CJSSIA5ke8s77FHqSh3hi9gaHSpI4flhafrlENZ49s=,tag:eWayDbPVcxjldyhtvqHEcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:iWvrSTE3uhWdp+9PuBQvFHrq5OOct/lv2VIFczjmAmqVAA==,iv:2T6HcQLu+KLsnNcUGHT8wSw2nHaEH1VDH4jbdcdxzTo=,tag:YCy68ua1owoKRL6/1rOjbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZUhJZE40RktWbDdPUlJr
            YkhTc3lxd2h5ZEIreXpJZUlUN3EzaGdKcVFRCitmL2VxYXVCbjFvQ0VXTXZGQUsy
            VnZMNng4anJObWRLdFNIZEZQNFdWRlEKLS0tIFZmUG93QmdaeWhDYzJxSDFGNysv
            clJzZzhVWlFvY1FpdWJqMDJuUjBjQWsK02DDAG+fDY0HBl0u4Cp73Y66XUZ4eDLP
            xsvZF6iWOCkBRKgF1As9dxBLrrZIkP3tw0M7WuWl+NqxDeZ88lOZqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:45:29Z"
    mac: ENC[AES256_GCM,data:5FyZT22smhmu+LpdTF1PVLTcS9joouRCc37D1VZ04grqUOpx1WmHXbkTyvHogAypTRa7nU/4FYP6BubZ+ZqfxlwiYxOUDKGQyM4t6SDVHK2PP8sqdydmmG6jOD6wHsNbqS8kbaxvuKyWV2H3BNQ5hFsEuhom7A4zbmOFVtJkL+c=,iv:9CJSSIA5ke8s77FHqSh3hi9gaHSpI4flhafrlENZ49s=,tag:eWayDbPVcxjldyhtvqHEcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:OzzRHxnxbNi/a7rcsoJqbIMmPg2ukyrTQzui,iv:CUPV99jGKuo1jF6AXz0XhUEoN6NbC3MmazXLP6LsT+Q=,tag:mC32nAnQ+9i57Y2p6twr9w==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:RGvTQZLPRcbcKBQ8Zqb8KeGq02kdJOB/ydUmEfk0JpU=,iv:qalH5PgdEfU6v13ph1LXu5Jat2sGeZCQg32D86ImX0o=,tag:lGHr1m1JXTa7aTwPXdzAhw==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:dKOJl2UnFmYwGV2Ti8u6abl1tXAzA0IY5yCUffktTDc=,iv:Nv6iGfag1bZH/2im+OEARHAyyBqT0kG1EPKz00s/2po=,tag:ZB2oGaO+BSWdNVUsji0chA==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:ewe9AvyZLB7XEE9yRVcmTn+9w2cwUm0ludpkrdkV+XrW8f+KdYBhBVOMVh0H7AaqQK2RSq2eJR/EhMQzXH72IjajZR/EpQYk6S09szOAJawUpkF1UYPmYwubg21h36U9SfjTykdsSREvYtEvP72rfj8kQlY+rsMmHv1oDgrpr5sazHZBNRarOsdagEj7Ai6U7zjtTw2o4Oclab1UVzMIkKd9JikQKx8ymkZkxbhYyfdVAYsSOwAhRnVnxPAOaY8gu+9agIQjiZof05Gnr+wKtrekdcgMrTFR9fUYQCpm2lm5BnM6ZS6x7b1ZtrWQ,iv:niEN/C+DoT/rweiaK7HWK/D0b3vW3QNzXJ7LU+nUZGk=,tag:lIpsATyiy/2+vx7DXrxE4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZUhJZE40RktWbDdPUlJr
            YkhTc3lxd2h5ZEIreXpJZUlUN3EzaGdKcVFRCitmL2VxYXVCbjFvQ0VXTXZGQUsy
            VnZMNng4anJObWRLdFNIZEZQNFdWRlEKLS0tIFZmUG93QmdaeWhDYzJxSDFGNysv
            clJzZzhVWlFvY1FpdWJqMDJuUjBjQWsK02DDAG+fDY0HBl0u4Cp73Y66XUZ4eDLP
            xsvZF6iWOCkBRKgF1As9dxBLrrZIkP3tw0M7WuWl+NqxDeZ88lOZqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:45:29Z"
    mac: ENC[AES256_GCM,data:5FyZT22smhmu+LpdTF1PVLTcS9joouRCc37D1VZ04grqUOpx1WmHXbkTyvHogAypTRa7nU/4FYP6BubZ+ZqfxlwiYxOUDKGQyM4t6SDVHK2PP8sqdydmmG6jOD6wHsNbqS8kbaxvuKyWV2H3BNQ5hFsEuhom7A4zbmOFVtJkL+c=,iv:9CJSSIA5ke8s77FHqSh3hi9gaHSpI4flhafrlENZ49s=,tag:eWayDbPVcxjldyhtvqHEcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:6UyjnCzDxA==,iv:ZLlm7vL2t9WCXSdBOPP7vXJyczclrdpfCjNjStCcV+I=,tag:A4rQpZlPTDTWlyjBvbh2Zg==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:mhzu0Lf8YX+praNxa+2PuKW2mzE=,iv:dIN2baGQ3Ts5I766LkP4zNhSuZd1s43175pFKjJdWoA=,tag:WypekAh5xdEJUWqgb55N0g==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:Nlj6uv6zNxs5KzJUhBxVsboudjKqwnkfPL6QAhbBAQn08ESsPA==,iv:DpS/oWbCg0zGGoid2Eczlqxso+cNohMi4PevQmEdE6c=,tag:edEQTTnzfVRbaFLNkQTJVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZUhJZE40RktWbDdPUlJr
            YkhTc3lxd2h5ZEIreXpJZUlUN3EzaGdKcVFRCitmL2VxYXVCbjFvQ0VXTXZGQUsy
            VnZMNng4anJObWRLdFNIZEZQNFdWRlEKLS0tIFZmUG93QmdaeWhDYzJxSDFGNysv
            clJzZzhVWlFvY1FpdWJqMDJuUjBjQWsK02DDAG+fDY0HBl0u4Cp73Y66XUZ4eDLP
            xsvZF6iWOCkBRKgF1As9dxBLrrZIkP3tw0M7WuWl+NqxDeZ88lOZqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:45:29Z"
    mac: ENC[AES256_GCM,data:5FyZT22smhmu+LpdTF1PVLTcS9joouRCc37D1VZ04grqUOpx1WmHXbkTyvHogAypTRa7nU/4FYP6BubZ+ZqfxlwiYxOUDKGQyM4t6SDVHK2PP8sqdydmmG6jOD6wHsNbqS8kbaxvuKyWV2H3BNQ5hFsEuhom7A4zbmOFVtJkL+c=,iv:9CJSSIA5ke8s77FHqSh3hi9gaHSpI4flhafrlENZ49s=,tag:eWayDbPVcxjldyhtvqHEcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: freescout-secrets
    namespace: default
type: Opaque
stringData:
    FREESCOUT_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:uOpp+gk1dX7gFsY9O6n72OfI+Wc=,iv:cKAASTLEmZY89kHK0LIwU3es1ioaf6/FnStf2JqIuNA=,tag:gTgLcceVmiSNld8FEHPgFw==,type:str]
    FREESCOUT_DB_PASSWORD: ENC[AES256_GCM,data:0ZkYjhP6giW6GyRVrH1Nmy7r6SE=,iv:eYpFwW2dDh5qqNKLhXmzXZEX2JdkOAGkTPAgg/t0zik=,tag:wESHtLM1mZiA+K0MCbwwvw==,type:str]
    FREESCOUT_ADMIN_EMAIL: ENC[AES256_GCM,data:yHBQU9m/03mEQ9+HtUeZA4aMuHfYIJA=,iv:oRmV8hVkHWhhEpneWFOj/LdoRcANNnrM+bfAXQLPzF8=,tag:XBSBkDwEx9YMDH3trhLUUg==,type:str]
    FREESCOUT_ADMIN_PASSWORD: ENC[AES256_GCM,data:lNcKlCjxKqm0V81Y0BiKoQtR35I=,iv:F6k4WLj0T3mRIzkdMfJq8bupd4QpkJo+TzqTeFjz0yA=,tag:83Sd8BQfLrB1XjNtzrKd4g==,type:str]
    FREESCOUT_SITE_URL: ENC[AES256_GCM,data:UeCr7aVMay+Fe4rhQ8jrI8VFPTv4QDeXGYLTGg==,iv:ycioA1J4FGpj1MX4/n0iuW5OYXFhtM09V7j2Xbl+Q58=,tag:swhEEsQ6TjKq9DkAMAPUpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZUhJZE40RktWbDdPUlJr
            YkhTc3lxd2h5ZEIreXpJZUlUN3EzaGdKcVFRCitmL2VxYXVCbjFvQ0VXTXZGQUsy
            VnZMNng4anJObWRLdFNIZEZQNFdWRlEKLS0tIFZmUG93QmdaeWhDYzJxSDFGNysv
            clJzZzhVWlFvY1FpdWJqMDJuUjBjQWsK02DDAG+fDY0HBl0u4Cp73Y66XUZ4eDLP
            xsvZF6iWOCkBRKgF1As9dxBLrrZIkP3tw0M7WuWl+NqxDeZ88lOZqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:45:29Z"
    mac: ENC[AES256_GCM,data:5FyZT22smhmu+LpdTF1PVLTcS9joouRCc37D1VZ04grqUOpx1WmHXbkTyvHogAypTRa7nU/4FYP6BubZ+ZqfxlwiYxOUDKGQyM4t6SDVHK2PP8sqdydmmG6jOD6wHsNbqS8kbaxvuKyWV2H3BNQ5hFsEuhom7A4zbmOFVtJkL+c=,iv:9CJSSIA5ke8s77FHqSh3hi9gaHSpI4flhafrlENZ49s=,tag:eWayDbPVcxjldyhtvqHEcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:h0OTah0V+CYKcZL4mwSQhSPyC6zWRiwm,iv:V+Xn+fatHXzLNuYerGwKQ70YgtlUFrQsgTUagcJaOmU=,tag:KA9bKUxqrN+ypUS8lXZdLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZUhJZE40RktWbDdPUlJr
            YkhTc3lxd2h5ZEIreXpJZUlUN3EzaGdKcVFRCitmL2VxYXVCbjFvQ0VXTXZGQUsy
            VnZMNng4anJObWRLdFNIZEZQNFdWRlEKLS0tIFZmUG93QmdaeWhDYzJxSDFGNysv
            clJzZzhVWlFvY1FpdWJqMDJuUjBjQWsK02DDAG+fDY0HBl0u4Cp73Y66XUZ4eDLP
            xsvZF6iWOCkBRKgF1As9dxBLrrZIkP3tw0M7WuWl+NqxDeZ88lOZqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:45:29Z"
    mac: ENC[AES256_GCM,data:5FyZT22smhmu+LpdTF1PVLTcS9joouRCc37D1VZ04grqUOpx1WmHXbkTyvHogAypTRa7nU/4FYP6BubZ+ZqfxlwiYxOUDKGQyM4t6SDVHK2PP8sqdydmmG6jOD6wHsNbqS8kbaxvuKyWV2H3BNQ5hFsEuhom7A4zbmOFVtJkL+c=,iv:9CJSSIA5ke8s77FHqSh3hi9gaHSpI4flhafrlENZ49s=,tag:eWayDbPVcxjldyhtvqHEcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
