apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:6Cwv+/5JdrlDb/VqUNZq/bwd8J2Lcr79GVOIHln7lRYZMw==,iv:tBGg42gYGTq0kz9Wzdee4eCgKo8Kk8v0bAXqS1kuats=,tag:PPbAGl0cq00M4mgPi9iS0w==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:eukM,iv:kOQKasPD/xumxgffoWv6uSzmbRdTSOrTKivooLi/hiQ=,tag:fQvdo/3t0wLYxbCfv+ZSKA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:NpdoaWkvvPU72KfEbS1m2YuUJ0Emkw==,iv:aNlW7OPEyYLGJCekWfN4zhT3k7z9s9Rx+mvncVnEFek=,tag:XYWCpve6Z7EMOnF4/IeoOQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:gjJv,iv:mhxjZJQ9OZFj7efbBjVpoRlU8QjMSZvhJEk/QfyZJEw=,tag:2JTa/WD7rGXlAwjCvE+HGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMk9NVkN0Q01SZ3pFR2pS
            eHJSakhZT2J1aVpuclhFdlhzanRldE1VOGlnCmNVTmZSaFA0TUV3Mng1d2dDakJi
            bnhoREhmMHhKNTlYeksxVTBLREhETDAKLS0tIG9DTEhHblBtbDBkSTAzTjVLTHJw
            SVpQaldzZU03dzlSUzU5M2ZFa0xIT2sKj4SLTa6+t7M4KKhm/RqjBHJimErhR60h
            c61ZoUn/79+LqAP6xc6UbmcZxhzRKdeb3al1Tj4sZBSDDdAyFvAQVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T18:27:57Z"
    mac: ENC[AES256_GCM,data:Q6/SfNT8d87HLlgYo0A/FfgqKRIrlcfzTdtpSiLpG8paZPP3petnmGFJkLy2OLmi3QIutW6yuPYyldyEHqW5K8/ZGQqQcc7ONvPkJlY17CM3u1/OPQqjZwIAgdY56Y8TTQJalcHewekWXwQaErPCG9wNwgpLjhw2q7YVzjzAhYo=,iv:NFn/O2rLKMtGtDunYXL2xbtp0XFqsc1x9jrP2VMZRhw=,tag:aD891yD3X6EbMwxOI+BDgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:E/WFfwol52I4rwKkwGzGhf6wIqxXHfvI2K0d01n7xKU=,iv:wI5lrvQPcLUFBWv30+P1WicI4KD4wZVIMCO5h+eR9Js=,tag:FweUUlxO7iZzHyWSkcqKnQ==,type:str]
    N8N_URL: ENC[AES256_GCM,data:1GDLVO/wt3AqJQqYnif48C3LxLdvY4XbBiOBsQ==,iv:OzZBHb/GnbDTX+196ieT/fj+8z9i6rask4Ha5kYAjt4=,tag:ZRcOBKRYbhbA1ZAoyIme4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMk9NVkN0Q01SZ3pFR2pS
            eHJSakhZT2J1aVpuclhFdlhzanRldE1VOGlnCmNVTmZSaFA0TUV3Mng1d2dDakJi
            bnhoREhmMHhKNTlYeksxVTBLREhETDAKLS0tIG9DTEhHblBtbDBkSTAzTjVLTHJw
            SVpQaldzZU03dzlSUzU5M2ZFa0xIT2sKj4SLTa6+t7M4KKhm/RqjBHJimErhR60h
            c61ZoUn/79+LqAP6xc6UbmcZxhzRKdeb3al1Tj4sZBSDDdAyFvAQVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T18:27:57Z"
    mac: ENC[AES256_GCM,data:Q6/SfNT8d87HLlgYo0A/FfgqKRIrlcfzTdtpSiLpG8paZPP3petnmGFJkLy2OLmi3QIutW6yuPYyldyEHqW5K8/ZGQqQcc7ONvPkJlY17CM3u1/OPQqjZwIAgdY56Y8TTQJalcHewekWXwQaErPCG9wNwgpLjhw2q7YVzjzAhYo=,iv:NFn/O2rLKMtGtDunYXL2xbtp0XFqsc1x9jrP2VMZRhw=,tag:aD891yD3X6EbMwxOI+BDgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:2zEly5YxpC2DyIfhke3xr+ByDAsXcOOwW5H4YeD4dYGUlm5wg/mXrhROnLNbi79iC4dbweciEK3abVC/jcjgzwdq6+4PLIW+Xzxq0oaO3RRh3gZCqoQH2yOAkXhnCH2JKeoBS1a1D2GGR28zj7AwCpcC5BxfekuGPKM2XhrfR/JKdmAGs5fvQhbKkzYkXK44xWNqqL2MARbv/3/H5NZYy7Za3Pau7J9ffFKIyBD/WKk23H83/n/aZw==,iv:2q46ApTvEhIv1tjf1nPHH0YNtxOTSGYCHun6PY/f+u4=,tag:56CkyEcw5Fgmz0UL/uvlkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMk9NVkN0Q01SZ3pFR2pS
            eHJSakhZT2J1aVpuclhFdlhzanRldE1VOGlnCmNVTmZSaFA0TUV3Mng1d2dDakJi
            bnhoREhmMHhKNTlYeksxVTBLREhETDAKLS0tIG9DTEhHblBtbDBkSTAzTjVLTHJw
            SVpQaldzZU03dzlSUzU5M2ZFa0xIT2sKj4SLTa6+t7M4KKhm/RqjBHJimErhR60h
            c61ZoUn/79+LqAP6xc6UbmcZxhzRKdeb3al1Tj4sZBSDDdAyFvAQVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T18:27:57Z"
    mac: ENC[AES256_GCM,data:Q6/SfNT8d87HLlgYo0A/FfgqKRIrlcfzTdtpSiLpG8paZPP3petnmGFJkLy2OLmi3QIutW6yuPYyldyEHqW5K8/ZGQqQcc7ONvPkJlY17CM3u1/OPQqjZwIAgdY56Y8TTQJalcHewekWXwQaErPCG9wNwgpLjhw2q7YVzjzAhYo=,iv:NFn/O2rLKMtGtDunYXL2xbtp0XFqsc1x9jrP2VMZRhw=,tag:aD891yD3X6EbMwxOI+BDgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:JzL2YDBB8TP6UvyCKvz0toSnpT25yZb2qPbwv2/bL/V91Q==,iv:P0d/MVuAKKwB/UjImKsF4rMvmepKANLM3kvJisQI6hg=,tag:tmiug2/l601OJoD8/j0uSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMk9NVkN0Q01SZ3pFR2pS
            eHJSakhZT2J1aVpuclhFdlhzanRldE1VOGlnCmNVTmZSaFA0TUV3Mng1d2dDakJi
            bnhoREhmMHhKNTlYeksxVTBLREhETDAKLS0tIG9DTEhHblBtbDBkSTAzTjVLTHJw
            SVpQaldzZU03dzlSUzU5M2ZFa0xIT2sKj4SLTa6+t7M4KKhm/RqjBHJimErhR60h
            c61ZoUn/79+LqAP6xc6UbmcZxhzRKdeb3al1Tj4sZBSDDdAyFvAQVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T18:27:57Z"
    mac: ENC[AES256_GCM,data:Q6/SfNT8d87HLlgYo0A/FfgqKRIrlcfzTdtpSiLpG8paZPP3petnmGFJkLy2OLmi3QIutW6yuPYyldyEHqW5K8/ZGQqQcc7ONvPkJlY17CM3u1/OPQqjZwIAgdY56Y8TTQJalcHewekWXwQaErPCG9wNwgpLjhw2q7YVzjzAhYo=,iv:NFn/O2rLKMtGtDunYXL2xbtp0XFqsc1x9jrP2VMZRhw=,tag:aD891yD3X6EbMwxOI+BDgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: reolink-secrets
type: Opaque
stringData:
    RL_BACKDOOR: ENC[AES256_GCM,data:RhjPVY438S4AEzMl,iv:qwl4YwswowShtkkn2U8vBKO1GxyWC7C35vJ/bmBRt20=,tag:CVmnUXW90K6xZ9oDkxtH4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMk9NVkN0Q01SZ3pFR2pS
            eHJSakhZT2J1aVpuclhFdlhzanRldE1VOGlnCmNVTmZSaFA0TUV3Mng1d2dDakJi
            bnhoREhmMHhKNTlYeksxVTBLREhETDAKLS0tIG9DTEhHblBtbDBkSTAzTjVLTHJw
            SVpQaldzZU03dzlSUzU5M2ZFa0xIT2sKj4SLTa6+t7M4KKhm/RqjBHJimErhR60h
            c61ZoUn/79+LqAP6xc6UbmcZxhzRKdeb3al1Tj4sZBSDDdAyFvAQVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T18:27:57Z"
    mac: ENC[AES256_GCM,data:Q6/SfNT8d87HLlgYo0A/FfgqKRIrlcfzTdtpSiLpG8paZPP3petnmGFJkLy2OLmi3QIutW6yuPYyldyEHqW5K8/ZGQqQcc7ONvPkJlY17CM3u1/OPQqjZwIAgdY56Y8TTQJalcHewekWXwQaErPCG9wNwgpLjhw2q7YVzjzAhYo=,iv:NFn/O2rLKMtGtDunYXL2xbtp0XFqsc1x9jrP2VMZRhw=,tag:aD891yD3X6EbMwxOI+BDgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: siyuan-secrets
type: Opaque
stringData:
    AUTH_CODE: ENC[AES256_GCM,data:nRa6+0jzn2GgcUMxcSN9zk8k9BU=,iv:cBmohN459CiQuA25uo5ikZy7BaikfEWTdIMuervHst4=,tag:BxRmVYzwgyyLNHprt90FAQ==,type:str]
    SIYUAN_URL: ENC[AES256_GCM,data:MXlemlMRNHqKz99Un4eZrSa0148NoinHUXnZfC0=,iv:6YaBRbnMTfqZ276LbD9IYJmjLWrBeGH5VWlq69bgB0k=,tag:SBnocvPWMOivKPxJq0Td/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMk9NVkN0Q01SZ3pFR2pS
            eHJSakhZT2J1aVpuclhFdlhzanRldE1VOGlnCmNVTmZSaFA0TUV3Mng1d2dDakJi
            bnhoREhmMHhKNTlYeksxVTBLREhETDAKLS0tIG9DTEhHblBtbDBkSTAzTjVLTHJw
            SVpQaldzZU03dzlSUzU5M2ZFa0xIT2sKj4SLTa6+t7M4KKhm/RqjBHJimErhR60h
            c61ZoUn/79+LqAP6xc6UbmcZxhzRKdeb3al1Tj4sZBSDDdAyFvAQVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T18:27:57Z"
    mac: ENC[AES256_GCM,data:Q6/SfNT8d87HLlgYo0A/FfgqKRIrlcfzTdtpSiLpG8paZPP3petnmGFJkLy2OLmi3QIutW6yuPYyldyEHqW5K8/ZGQqQcc7ONvPkJlY17CM3u1/OPQqjZwIAgdY56Y8TTQJalcHewekWXwQaErPCG9wNwgpLjhw2q7YVzjzAhYo=,iv:NFn/O2rLKMtGtDunYXL2xbtp0XFqsc1x9jrP2VMZRhw=,tag:aD891yD3X6EbMwxOI+BDgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMk9NVkN0Q01SZ3pFR2pS
            eHJSakhZT2J1aVpuclhFdlhzanRldE1VOGlnCmNVTmZSaFA0TUV3Mng1d2dDakJi
            bnhoREhmMHhKNTlYeksxVTBLREhETDAKLS0tIG9DTEhHblBtbDBkSTAzTjVLTHJw
            SVpQaldzZU03dzlSUzU5M2ZFa0xIT2sKj4SLTa6+t7M4KKhm/RqjBHJimErhR60h
            c61ZoUn/79+LqAP6xc6UbmcZxhzRKdeb3al1Tj4sZBSDDdAyFvAQVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T18:27:57Z"
    mac: ENC[AES256_GCM,data:Q6/SfNT8d87HLlgYo0A/FfgqKRIrlcfzTdtpSiLpG8paZPP3petnmGFJkLy2OLmi3QIutW6yuPYyldyEHqW5K8/ZGQqQcc7ONvPkJlY17CM3u1/OPQqjZwIAgdY56Y8TTQJalcHewekWXwQaErPCG9wNwgpLjhw2q7YVzjzAhYo=,iv:NFn/O2rLKMtGtDunYXL2xbtp0XFqsc1x9jrP2VMZRhw=,tag:aD891yD3X6EbMwxOI+BDgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
