apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:5HMC,iv:E//diNW2FQbepkBb4gbYD8WdGdKqsjDDoWrBFmTRZA4=,tag:TfJR8oJigDTQRDy7x/PE1A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:looNxh/ywvUdK4JfkqoMOU2btddSOg==,iv:WAosei8iZkZgp3wctwi5n9UAC66cDerfHL6XJzAwJNI=,tag:Mv6ax+OrAQ6b/NISLJsZ+A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:KMEz,iv:weVUfCLbGrHG4w9MZh3wucnVsa9ysELclUKnIuKnQXY=,tag:JeX/wGNv/raA9YpyUFZgTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUx6MHpYWHNsUEZ3NDkr
            aUJIQzNLOUtyOTAxZ1JtZ25tejdjV1krNzE4CmZOUk84bXhmVU51cTNHdEZaa1JO
            MHdkUlEzN05pU3ltd1djVEV5dTdnTWsKLS0tIDltS2U0UERhWGJlMm4wNlVsUFhC
            bWI1bUQveFZJMlBCb0FNMkZ5YzZkbWsKknOmvAjtADzRXxklzk0UJ8YmfN1LZ3XH
            rrNtymltzzZtTZYJVum/UJm2XlaNQUEuIn5pMAb/MM1xUJg7WPKAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:58:47Z"
    mac: ENC[AES256_GCM,data:wRmQoo+fH/fdUX4FrhneqLThaRrQtLEhrHxCL9lOsMEZqp0BxglkuyExE12sNzQI1BDv/BrHWOyiXNMu8C8G10xZEGcEEUqrt3jQcz2dcxs0cACP8Gc+fpF9AOhplyZ/myGts08w07Xg5ACsdRZy1x75HsxFqKZLtLrpNButdkQ=,iv:kSXjbvkO8cDzB4VurB88Dav3vGFqwlfJXuAg3ew8BJA=,tag:uYsaFgWZrexco38Pt0htBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:lyW3gPKN1ktt28/cSSwwzIkOPVWXtoWqb9dYCgaqAbg=,iv:jv0Nq3w51eYPXJtVS4zWB88mr+fdN8l5+qmd0cPwJVM=,tag:mFBMeWR9GX5yTvpOvWGvUQ==,type:str]
    N8N_URL: ENC[AES256_GCM,data:1mpSa1qkH3djJQ1etO3Q1CWcM1wQKgQoUJN6NA==,iv:8Ayd+8MAIdjaE0I9lmM230aVKD+645T0NKOpNfr7uxI=,tag:8EE5wsjulGOcVDgKmcrEmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUx6MHpYWHNsUEZ3NDkr
            aUJIQzNLOUtyOTAxZ1JtZ25tejdjV1krNzE4CmZOUk84bXhmVU51cTNHdEZaa1JO
            MHdkUlEzN05pU3ltd1djVEV5dTdnTWsKLS0tIDltS2U0UERhWGJlMm4wNlVsUFhC
            bWI1bUQveFZJMlBCb0FNMkZ5YzZkbWsKknOmvAjtADzRXxklzk0UJ8YmfN1LZ3XH
            rrNtymltzzZtTZYJVum/UJm2XlaNQUEuIn5pMAb/MM1xUJg7WPKAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:58:47Z"
    mac: ENC[AES256_GCM,data:wRmQoo+fH/fdUX4FrhneqLThaRrQtLEhrHxCL9lOsMEZqp0BxglkuyExE12sNzQI1BDv/BrHWOyiXNMu8C8G10xZEGcEEUqrt3jQcz2dcxs0cACP8Gc+fpF9AOhplyZ/myGts08w07Xg5ACsdRZy1x75HsxFqKZLtLrpNButdkQ=,iv:kSXjbvkO8cDzB4VurB88Dav3vGFqwlfJXuAg3ew8BJA=,tag:uYsaFgWZrexco38Pt0htBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:ySw0x+z+leiGSR3fnFzQGCpCFYrrqmV/N6Nx/5NNUps68PTTrJ7fCUeggJV1/jc+t7HAnrEImWKZ2qLPS+DykDcH3iYLywOXS9hbI7IvFMIRjGp8XwMiwONG03yJRL8pVi27kdR/9KPcI7g10dJ4nGamIGi2JnGOGT6bJ7qfYTXWiipsC1NOdweQbB2qaInhYT6LsvgipbKR4VbZtYOOMsraofbqkchg36PqZtBnlK46hpzTGEr0OA==,iv:Wuwo3ag/QPJup7Eafu5zYfgxdX8NfDfLvcyWHpXwNlg=,tag:1RzuN8wBcMVbiFeAVbsb2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUx6MHpYWHNsUEZ3NDkr
            aUJIQzNLOUtyOTAxZ1JtZ25tejdjV1krNzE4CmZOUk84bXhmVU51cTNHdEZaa1JO
            MHdkUlEzN05pU3ltd1djVEV5dTdnTWsKLS0tIDltS2U0UERhWGJlMm4wNlVsUFhC
            bWI1bUQveFZJMlBCb0FNMkZ5YzZkbWsKknOmvAjtADzRXxklzk0UJ8YmfN1LZ3XH
            rrNtymltzzZtTZYJVum/UJm2XlaNQUEuIn5pMAb/MM1xUJg7WPKAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:58:47Z"
    mac: ENC[AES256_GCM,data:wRmQoo+fH/fdUX4FrhneqLThaRrQtLEhrHxCL9lOsMEZqp0BxglkuyExE12sNzQI1BDv/BrHWOyiXNMu8C8G10xZEGcEEUqrt3jQcz2dcxs0cACP8Gc+fpF9AOhplyZ/myGts08w07Xg5ACsdRZy1x75HsxFqKZLtLrpNButdkQ=,iv:kSXjbvkO8cDzB4VurB88Dav3vGFqwlfJXuAg3ew8BJA=,tag:uYsaFgWZrexco38Pt0htBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:6es9gSCbfhP7psveg4aCaiJBtupNkpgbraOMDm6/y8guGQ==,iv:AWOOYJwF/fTZTttSbsaWCfwzsTWM1fyTW9QX64o4edU=,tag:19HS5KSpoNZPFKFjHU7Crw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUx6MHpYWHNsUEZ3NDkr
            aUJIQzNLOUtyOTAxZ1JtZ25tejdjV1krNzE4CmZOUk84bXhmVU51cTNHdEZaa1JO
            MHdkUlEzN05pU3ltd1djVEV5dTdnTWsKLS0tIDltS2U0UERhWGJlMm4wNlVsUFhC
            bWI1bUQveFZJMlBCb0FNMkZ5YzZkbWsKknOmvAjtADzRXxklzk0UJ8YmfN1LZ3XH
            rrNtymltzzZtTZYJVum/UJm2XlaNQUEuIn5pMAb/MM1xUJg7WPKAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:58:47Z"
    mac: ENC[AES256_GCM,data:wRmQoo+fH/fdUX4FrhneqLThaRrQtLEhrHxCL9lOsMEZqp0BxglkuyExE12sNzQI1BDv/BrHWOyiXNMu8C8G10xZEGcEEUqrt3jQcz2dcxs0cACP8Gc+fpF9AOhplyZ/myGts08w07Xg5ACsdRZy1x75HsxFqKZLtLrpNButdkQ=,iv:kSXjbvkO8cDzB4VurB88Dav3vGFqwlfJXuAg3ew8BJA=,tag:uYsaFgWZrexco38Pt0htBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:bdf7cN0p1RooRsomTnJgZ+XXJsiRTnSEOX7p,iv:DphdqnlrhrKcDU2/Av4yC3I4xSDGQzz2rnhBmQf3WAo=,tag:Hy2uZ7Hz+ApcKuYyGdcKgw==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:IzbQ2Q5ILZ5EZrE1Hm2uTMonhIg/9Qj+llkp5HGc7dY=,iv:xsmPSHbyc2OqahieBv+1V+e5RaHJplDKjHg7htpPo1Q=,tag:tH4wpsZAUwpQ22rfyehKZA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:nn9IixWapxOPp4Ro44BlxKwqCT1woQVtIe9YW5gieHE=,iv:TwAH0j3m+la/Ckgnm4vOEY/jPGz37f91HYnfBkN0rdg=,tag:X8ukBeU4gaMvMZoKqvdGzQ==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:0450moNsPFa439psua/i+5G85JkIJr3elzEgKY7TWug+OuZRbn1AwDyM69/AjUAgF+KIaC2X7lesIZXviC/2Xg4ROMdMbb+eczGzH0LmDzLwWrVt9jv+kVL0zOsQZrReb2N5EincAWmgg1ST6PI6ZFLP+uPZOPJLbV7IND1IkMq0BICNroSKtrZqz4flPW1FrPtpL4kphMJBuKsNCJmFQLDXJV+l/a81s7HEcPOLo/6MmWMPHTgYi4Rl7xeUyr6vQFg9q6ZJAFX/7ysDEMFWj2m2IzBmJiSzcLm1feWXh1R+ZPvoRUJ0+kGx5NMY,iv:41kfkBeCxDGavDu/cso26pHdOTmupcUeBdXjWVZbknA=,tag:8uM+k+lkxDxOxei0MpI8Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUx6MHpYWHNsUEZ3NDkr
            aUJIQzNLOUtyOTAxZ1JtZ25tejdjV1krNzE4CmZOUk84bXhmVU51cTNHdEZaa1JO
            MHdkUlEzN05pU3ltd1djVEV5dTdnTWsKLS0tIDltS2U0UERhWGJlMm4wNlVsUFhC
            bWI1bUQveFZJMlBCb0FNMkZ5YzZkbWsKknOmvAjtADzRXxklzk0UJ8YmfN1LZ3XH
            rrNtymltzzZtTZYJVum/UJm2XlaNQUEuIn5pMAb/MM1xUJg7WPKAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:58:47Z"
    mac: ENC[AES256_GCM,data:wRmQoo+fH/fdUX4FrhneqLThaRrQtLEhrHxCL9lOsMEZqp0BxglkuyExE12sNzQI1BDv/BrHWOyiXNMu8C8G10xZEGcEEUqrt3jQcz2dcxs0cACP8Gc+fpF9AOhplyZ/myGts08w07Xg5ACsdRZy1x75HsxFqKZLtLrpNButdkQ=,iv:kSXjbvkO8cDzB4VurB88Dav3vGFqwlfJXuAg3ew8BJA=,tag:uYsaFgWZrexco38Pt0htBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:blp2DI+cbA==,iv:CzC8Zt0x7JcPH6sdDQG8jeWqhk1WbAl5sGysfRWTrw8=,tag:rV8zIGuYFE/9SxgQJ7F2VQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:5yY2bZecQnM+NiO9AcyTXxVGlbw=,iv:fbO92XSeTEtusfHZ1K3+Ff1f7TsenpJGTNRTjTSRphE=,tag:tLedIUF7rmhmYDcCfWWzYQ==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:0shFi3UdcpcIOlgZgUd12Poowdtx8x4C6VGEG3uI7NPrFhRpHw==,iv:jn3KYJ2qrPodoEuFAwjBvLh2kx+qb0rhgx2suze5I7o=,tag:2KRVquLrldcmPggKnoRrcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUx6MHpYWHNsUEZ3NDkr
            aUJIQzNLOUtyOTAxZ1JtZ25tejdjV1krNzE4CmZOUk84bXhmVU51cTNHdEZaa1JO
            MHdkUlEzN05pU3ltd1djVEV5dTdnTWsKLS0tIDltS2U0UERhWGJlMm4wNlVsUFhC
            bWI1bUQveFZJMlBCb0FNMkZ5YzZkbWsKknOmvAjtADzRXxklzk0UJ8YmfN1LZ3XH
            rrNtymltzzZtTZYJVum/UJm2XlaNQUEuIn5pMAb/MM1xUJg7WPKAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:58:47Z"
    mac: ENC[AES256_GCM,data:wRmQoo+fH/fdUX4FrhneqLThaRrQtLEhrHxCL9lOsMEZqp0BxglkuyExE12sNzQI1BDv/BrHWOyiXNMu8C8G10xZEGcEEUqrt3jQcz2dcxs0cACP8Gc+fpF9AOhplyZ/myGts08w07Xg5ACsdRZy1x75HsxFqKZLtLrpNButdkQ=,iv:kSXjbvkO8cDzB4VurB88Dav3vGFqwlfJXuAg3ew8BJA=,tag:uYsaFgWZrexco38Pt0htBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:yY7m+X7WGHSB5Pv18Z4iv0m1q0Ia88B514Hp3toifdcDAyTyxUPCu1DBG9o=,iv:Dc9TBq+nAsPgx2sKl26tKS/uw0i+bkg4r9coluaNj10=,tag:p2AmAzdh4K7HvjrInlqnZw==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:5n9nibYJNxG9SVqRyMWEETHY2DuTGWAxaKch,iv:9nqeqYkSbIMi90VW7C84srOAyfqDIldzEVuoAUI7FaA=,tag:N9XwtzkJqXF6mj8St39gzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUx6MHpYWHNsUEZ3NDkr
            aUJIQzNLOUtyOTAxZ1JtZ25tejdjV1krNzE4CmZOUk84bXhmVU51cTNHdEZaa1JO
            MHdkUlEzN05pU3ltd1djVEV5dTdnTWsKLS0tIDltS2U0UERhWGJlMm4wNlVsUFhC
            bWI1bUQveFZJMlBCb0FNMkZ5YzZkbWsKknOmvAjtADzRXxklzk0UJ8YmfN1LZ3XH
            rrNtymltzzZtTZYJVum/UJm2XlaNQUEuIn5pMAb/MM1xUJg7WPKAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:58:47Z"
    mac: ENC[AES256_GCM,data:wRmQoo+fH/fdUX4FrhneqLThaRrQtLEhrHxCL9lOsMEZqp0BxglkuyExE12sNzQI1BDv/BrHWOyiXNMu8C8G10xZEGcEEUqrt3jQcz2dcxs0cACP8Gc+fpF9AOhplyZ/myGts08w07Xg5ACsdRZy1x75HsxFqKZLtLrpNButdkQ=,iv:kSXjbvkO8cDzB4VurB88Dav3vGFqwlfJXuAg3ew8BJA=,tag:uYsaFgWZrexco38Pt0htBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: default
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:AlYnTp2WFidj0nvO3yeCJTIpF6e+2oNd9fBGgKAuD1ZUDZnVKsBaUA==,iv:CGqtzOh+Cbj1AHN4EERU6FNV87HyEQhm5oQS0T+NiSo=,tag:iSm0xsdm2qnO4K1UBgZSeA==,type:str]
    RENOVATE_GITHUB_TOKEN: ENC[AES256_GCM,data:ZvJQIoqo2mAg2wtRkb4NqHdvCgcuIj3hDwM4k1U0sfk0nfHrEfkK0Q==,iv:TdcpSILmlclLA6+lS64T8qeIEBkD48ZCAibSRTuLop4=,tag:OqgGaRvrp8QjjQpqvAfa+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUx6MHpYWHNsUEZ3NDkr
            aUJIQzNLOUtyOTAxZ1JtZ25tejdjV1krNzE4CmZOUk84bXhmVU51cTNHdEZaa1JO
            MHdkUlEzN05pU3ltd1djVEV5dTdnTWsKLS0tIDltS2U0UERhWGJlMm4wNlVsUFhC
            bWI1bUQveFZJMlBCb0FNMkZ5YzZkbWsKknOmvAjtADzRXxklzk0UJ8YmfN1LZ3XH
            rrNtymltzzZtTZYJVum/UJm2XlaNQUEuIn5pMAb/MM1xUJg7WPKAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:58:47Z"
    mac: ENC[AES256_GCM,data:wRmQoo+fH/fdUX4FrhneqLThaRrQtLEhrHxCL9lOsMEZqp0BxglkuyExE12sNzQI1BDv/BrHWOyiXNMu8C8G10xZEGcEEUqrt3jQcz2dcxs0cACP8Gc+fpF9AOhplyZ/myGts08w07Xg5ACsdRZy1x75HsxFqKZLtLrpNButdkQ=,iv:kSXjbvkO8cDzB4VurB88Dav3vGFqwlfJXuAg3ew8BJA=,tag:uYsaFgWZrexco38Pt0htBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-secrets
    namespace: default
type: Opaque
stringData:
    JELLYFIN_KEY: ENC[AES256_GCM,data:UF2M5gS377yxmdZgbJBg/CSc4RAVn0XZfZYMC9EV8wA=,iv:PR5heDKN9EQM4bMlk8OPI0a6JCE38bepK05i1Xwk8jg=,tag:hIkmKJTXuqVOWV9JCzfw8g==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:OPqELyTF8BMCtfZYM58up3Jif7TtmEmncNU=,iv:NjL5l9SIa6LGWwjozpk8Jd4oMzCVOecth82RULtoqX4=,tag:hgKJ2ThRk0V933AOHjsaSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUx6MHpYWHNsUEZ3NDkr
            aUJIQzNLOUtyOTAxZ1JtZ25tejdjV1krNzE4CmZOUk84bXhmVU51cTNHdEZaa1JO
            MHdkUlEzN05pU3ltd1djVEV5dTdnTWsKLS0tIDltS2U0UERhWGJlMm4wNlVsUFhC
            bWI1bUQveFZJMlBCb0FNMkZ5YzZkbWsKknOmvAjtADzRXxklzk0UJ8YmfN1LZ3XH
            rrNtymltzzZtTZYJVum/UJm2XlaNQUEuIn5pMAb/MM1xUJg7WPKAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:58:47Z"
    mac: ENC[AES256_GCM,data:wRmQoo+fH/fdUX4FrhneqLThaRrQtLEhrHxCL9lOsMEZqp0BxglkuyExE12sNzQI1BDv/BrHWOyiXNMu8C8G10xZEGcEEUqrt3jQcz2dcxs0cACP8Gc+fpF9AOhplyZ/myGts08w07Xg5ACsdRZy1x75HsxFqKZLtLrpNButdkQ=,iv:kSXjbvkO8cDzB4VurB88Dav3vGFqwlfJXuAg3ew8BJA=,tag:uYsaFgWZrexco38Pt0htBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-secrets
    namespace: default
type: Opaque
stringData:
    HA_TOKEN: ENC[AES256_GCM,data:TifvpCFovzvb0B/jt3jpWiAGwtmiHzWoEJESBrloHTxvt71wQLDlv3gFFVYFUQfPQF4mXaISnCp+hpDEhBBZAX4xFa+5Tqv4O8tplQc1i0+mMCDMshowgfNQ4WSf8Zmdvd2KmXAzpoar11EYlL6rhr2zPcgxZm8ekZnvhPt16viBj/wTuBmeUoa7MxQJF+bpkyFEZKwn4Q1HsXbS9VZB3AP1oH/EL3S258/gDIoYQ6NLgqhVkoO4,iv:QNBtYHKHisNED8BZ/mzNqhTmO6aOeEgzUFOOvqdW6Xw=,tag:ZmrK4rwJmAcaHH/bfZeKYQ==,type:str]
    HA_IP: ENC[AES256_GCM,data:cTUuVdaq3jOrk1Am3YoD4TrzHXbLEHMSSog=,iv:T2e6WLPxO1S6WmibgEJZqGJ8r/nQTqmi6FRrJT2Yq4M=,tag:n0GEd6pFAzsFgR+ypJkwkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWUx6MHpYWHNsUEZ3NDkr
            aUJIQzNLOUtyOTAxZ1JtZ25tejdjV1krNzE4CmZOUk84bXhmVU51cTNHdEZaa1JO
            MHdkUlEzN05pU3ltd1djVEV5dTdnTWsKLS0tIDltS2U0UERhWGJlMm4wNlVsUFhC
            bWI1bUQveFZJMlBCb0FNMkZ5YzZkbWsKknOmvAjtADzRXxklzk0UJ8YmfN1LZ3XH
            rrNtymltzzZtTZYJVum/UJm2XlaNQUEuIn5pMAb/MM1xUJg7WPKAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:58:47Z"
    mac: ENC[AES256_GCM,data:wRmQoo+fH/fdUX4FrhneqLThaRrQtLEhrHxCL9lOsMEZqp0BxglkuyExE12sNzQI1BDv/BrHWOyiXNMu8C8G10xZEGcEEUqrt3jQcz2dcxs0cACP8Gc+fpF9AOhplyZ/myGts08w07Xg5ACsdRZy1x75HsxFqKZLtLrpNButdkQ=,iv:kSXjbvkO8cDzB4VurB88Dav3vGFqwlfJXuAg3ew8BJA=,tag:uYsaFgWZrexco38Pt0htBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
