apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:QmOb,iv:1+GvOgRdfzYwjs0vB5iNbVTfDRhGLQlZA/5Q/SktVPk=,tag:1hxQ96PGbSdFpjup5JIrpw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:dAddAi5TeW2fjkEZGbxnMhAyHYdIvA==,iv:fpeD2n4DPeRbVNKK9rJ3jqWNiaKaTf9nwaBgwEl26ZU=,tag:crA6gapR5zTCspoHH04jnw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:u/46,iv:sxHf61WsDQTRlkywoBINE+biU1yi0+XgokzQRaEYm0o=,tag:6rnbU8vvSUHMT7cO9hJtBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dm5XWGkzWTMyRjJwNWlI
            WWt0RHVMZ2s1ZksraXJpZ09uWjBBamVob2tRCkdHclo1UytZYmVyNzhlSFg0bzRQ
            N2l4YmlsK1lDSm9OcEpuRG5RU2IvZVkKLS0tIGZpWFRDREsrSlQ2SWsybW1IYmNC
            TDRHSDExWkx4bVFZSHIwQ1FiTy83SlkKE7C7VUEwjAsxk06FzLIHv8RIT0owBM21
            Bm/KrwXo/cU77Lz1EKVaRhEflCLDBa9YjNL/lsl63597GlYuh4LQyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:46:49Z"
    mac: ENC[AES256_GCM,data:KJ+AJFoJMjJuDJ0khwJwiVnSpkIBJ9ebEgVY2tazQGkKKjz/+yIWz+ENsREu+WcjF2KE96GDBsbNrWKaZhpecyLTEWz29PcwPw1D5uD8J1aEJWFSceYjr6NYYgb15+d/M3/LVT/7qJqCEfvueKiwy0S4xy5J+OnJNI461YR+WyM=,iv:J93YXT2qs5HtBKsyL2nSplXqob3dSVGrJPsGNzpH7sc=,tag:/iE70l2RUUhetdj+ag/O0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:WwMd7uUNwHU+o5Kdb9KtmcbyldchbJEZHAS+NAkGyb4=,iv:Zv/ntMCcBzOH4//Ey8kBr0WfFoWaP9dCBsNgpVah368=,tag:mzi5B1uqWO5kobddxHcmWw==,type:str]
    N8N_URL: ENC[AES256_GCM,data:Hfef9EhPxQErshEkNyFnG9L2xKwFdKhmOUg6Ig==,iv:BynfEXuCn0CimRr5ZsGMyoKtUiWBkZeBL2/uEqtaTj4=,tag:3CfdbssgbE+3xWx1y8J+5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dm5XWGkzWTMyRjJwNWlI
            WWt0RHVMZ2s1ZksraXJpZ09uWjBBamVob2tRCkdHclo1UytZYmVyNzhlSFg0bzRQ
            N2l4YmlsK1lDSm9OcEpuRG5RU2IvZVkKLS0tIGZpWFRDREsrSlQ2SWsybW1IYmNC
            TDRHSDExWkx4bVFZSHIwQ1FiTy83SlkKE7C7VUEwjAsxk06FzLIHv8RIT0owBM21
            Bm/KrwXo/cU77Lz1EKVaRhEflCLDBa9YjNL/lsl63597GlYuh4LQyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:46:49Z"
    mac: ENC[AES256_GCM,data:KJ+AJFoJMjJuDJ0khwJwiVnSpkIBJ9ebEgVY2tazQGkKKjz/+yIWz+ENsREu+WcjF2KE96GDBsbNrWKaZhpecyLTEWz29PcwPw1D5uD8J1aEJWFSceYjr6NYYgb15+d/M3/LVT/7qJqCEfvueKiwy0S4xy5J+OnJNI461YR+WyM=,iv:J93YXT2qs5HtBKsyL2nSplXqob3dSVGrJPsGNzpH7sc=,tag:/iE70l2RUUhetdj+ag/O0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:m6xpRp77fFDVrnksTKBkYoihwi3vQ1a+ZC2Jobg9CsS86fs0/+Ha9+x8FbiQfd4ROIHJMDM26NrniS84POSavcoUtAZd+6XlIeeR555i/zWF3jt5qPb16jKpOFFWfNY4yietGs2lgdQXyxk1p37QnjA2nRqFU3iCMi1DLpC44f/BgzghneH1+Acb6WRYTadTtdmZmrJhvztVhFsYZgW6yx8QtrNijGrm2555r/j6utnG3C2sr25TWg==,iv:7qqfIzNtoIbreFMiqeKHu3MFuoHJUrZAvXhDxcJWob8=,tag:RJ5LKi8bOoLrZqLhNeb/6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dm5XWGkzWTMyRjJwNWlI
            WWt0RHVMZ2s1ZksraXJpZ09uWjBBamVob2tRCkdHclo1UytZYmVyNzhlSFg0bzRQ
            N2l4YmlsK1lDSm9OcEpuRG5RU2IvZVkKLS0tIGZpWFRDREsrSlQ2SWsybW1IYmNC
            TDRHSDExWkx4bVFZSHIwQ1FiTy83SlkKE7C7VUEwjAsxk06FzLIHv8RIT0owBM21
            Bm/KrwXo/cU77Lz1EKVaRhEflCLDBa9YjNL/lsl63597GlYuh4LQyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:46:49Z"
    mac: ENC[AES256_GCM,data:KJ+AJFoJMjJuDJ0khwJwiVnSpkIBJ9ebEgVY2tazQGkKKjz/+yIWz+ENsREu+WcjF2KE96GDBsbNrWKaZhpecyLTEWz29PcwPw1D5uD8J1aEJWFSceYjr6NYYgb15+d/M3/LVT/7qJqCEfvueKiwy0S4xy5J+OnJNI461YR+WyM=,iv:J93YXT2qs5HtBKsyL2nSplXqob3dSVGrJPsGNzpH7sc=,tag:/iE70l2RUUhetdj+ag/O0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:mIrry3nisupoZnsrV7MLKQBtGmTWQ45at+ImqAxm40qqJQ==,iv:u0CObaFMCQ/HE5Dqc1K5fRaoGDelKR1lSayJmzn3dSM=,tag:o9zWcICsOGdtn4kw0y7smw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dm5XWGkzWTMyRjJwNWlI
            WWt0RHVMZ2s1ZksraXJpZ09uWjBBamVob2tRCkdHclo1UytZYmVyNzhlSFg0bzRQ
            N2l4YmlsK1lDSm9OcEpuRG5RU2IvZVkKLS0tIGZpWFRDREsrSlQ2SWsybW1IYmNC
            TDRHSDExWkx4bVFZSHIwQ1FiTy83SlkKE7C7VUEwjAsxk06FzLIHv8RIT0owBM21
            Bm/KrwXo/cU77Lz1EKVaRhEflCLDBa9YjNL/lsl63597GlYuh4LQyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:46:49Z"
    mac: ENC[AES256_GCM,data:KJ+AJFoJMjJuDJ0khwJwiVnSpkIBJ9ebEgVY2tazQGkKKjz/+yIWz+ENsREu+WcjF2KE96GDBsbNrWKaZhpecyLTEWz29PcwPw1D5uD8J1aEJWFSceYjr6NYYgb15+d/M3/LVT/7qJqCEfvueKiwy0S4xy5J+OnJNI461YR+WyM=,iv:J93YXT2qs5HtBKsyL2nSplXqob3dSVGrJPsGNzpH7sc=,tag:/iE70l2RUUhetdj+ag/O0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: siyuan-secrets
    namespace: default
type: Opaque
stringData:
    AUTH_CODE: ENC[AES256_GCM,data:oE6czHbhwvAZRTfpmLNOFz2T6RI=,iv:x8TQMJ7KRXdiEsWLWjBkvIjezQMWNJ56/M98o4SEbdc=,tag:oQuXucy7M46kdekGNN+YEA==,type:str]
    SIYUAN_URL: ENC[AES256_GCM,data:R24VXj3KIPeil2Cq6zmCh6sNRe2XJYmVwR8PigI=,iv:dDqu2+jVXP/sG/C6hFZE8YCXhsi+9Nja0BloXdMC10Y=,tag:xqaJdEmRolucLmG/bUy5BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dm5XWGkzWTMyRjJwNWlI
            WWt0RHVMZ2s1ZksraXJpZ09uWjBBamVob2tRCkdHclo1UytZYmVyNzhlSFg0bzRQ
            N2l4YmlsK1lDSm9OcEpuRG5RU2IvZVkKLS0tIGZpWFRDREsrSlQ2SWsybW1IYmNC
            TDRHSDExWkx4bVFZSHIwQ1FiTy83SlkKE7C7VUEwjAsxk06FzLIHv8RIT0owBM21
            Bm/KrwXo/cU77Lz1EKVaRhEflCLDBa9YjNL/lsl63597GlYuh4LQyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:46:49Z"
    mac: ENC[AES256_GCM,data:KJ+AJFoJMjJuDJ0khwJwiVnSpkIBJ9ebEgVY2tazQGkKKjz/+yIWz+ENsREu+WcjF2KE96GDBsbNrWKaZhpecyLTEWz29PcwPw1D5uD8J1aEJWFSceYjr6NYYgb15+d/M3/LVT/7qJqCEfvueKiwy0S4xy5J+OnJNI461YR+WyM=,iv:J93YXT2qs5HtBKsyL2nSplXqob3dSVGrJPsGNzpH7sc=,tag:/iE70l2RUUhetdj+ag/O0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
