apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:QXwSwbEyFyYzSRWOhY5PkUBoWm+tbNqBae1Zmy8PBKlNDg==,iv:g1mS2+p35GE4iBoRHY/K8cpUmjC+FyLPXuojcCGxJLE=,tag:0sSzprC84UitEnHJhggfEA==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:wvhi,iv:fKkeSJ3m1sFkNmLNsCq2imocLOAsCARy4NnEHBpXheY=,tag:re1ImfluMXULBQzOLTDDiQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lr8emdxjrvxJINW+z9I/36mf9fxp8A==,iv:l/GZLAJU3gta6qnpbycaqAbKzXyVHkjGQqnbx3BAUhU=,tag:H+GTuinChag8f1plYnTuyA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:gqc7,iv:rUHIZXO4iMpn4oSUkFdqCuWu0lhoBijcuH7f5cAbz/M=,tag:uG8h7fgKWI0P4cmbrgTUwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bENkeWJDL2VBTGhWaWNw
            N3RjRWRGZVE3b1pOU1ZOODBHYVNJeXg4M1RvCjZUNTgrZWdzNExPcDlGSGJFWURV
            eENCang0WVVhTE5zMWw4ZTA3ZHgzQk0KLS0tIFBaL2ozN003UHUzN3k2dldGOVEx
            dkwwMURUNm9rQ3N0NFVRSGFhelNFODAKiUdcryZ+SJdNCdUH769/Rfd9JaMiMOXV
            g+ILcsciIh1EDu1sD51cftuiTld3RiSuMccOQBPSmE7mBS4ekunJ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:31:51Z"
    mac: ENC[AES256_GCM,data:X0qLs0EAZw129iWZNALmTboHyxp2AllCafjN0K9+vjAohsEF5gsI6AzJiO9BHLLpwWpuoAh6kOqp35mdTPRIz8JrfiPGGaFqJWL83ai5YJvJs9pwPEnVHK/UQeM36zJFxbjAQyAroge05iSvusOFF3FVIUGiPkZbF9wQOqFxa00=,iv:PeE6CHCyGnxmCUKnLhQjEoTv0yCQ7HOc58AhfO/j5mY=,tag:StFOBOiXWNes5Sx2WP602g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:/9VIfc7n4fFqwL9sbHu9gFC9+gVqDy6eHs/KH7OHAeo=,iv:/YkS+0tA3Ipyz1hkRDEGjKCS/O2Oal4eUy0a3ZrS52c=,tag:gzP3EL+QF8yqo+ssjWXzBQ==,type:str]
    N8N_URL: ENC[AES256_GCM,data:nmkW55OlmyIgtIKEWesQ8PKx14CNAqYZCxD3Gg==,iv:Elbl74JCAUdwUO4p2sOJ1AfRv98veoyv73D8OIpk9MY=,tag:uM5TvrHg7Gu+99KQaSULDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bENkeWJDL2VBTGhWaWNw
            N3RjRWRGZVE3b1pOU1ZOODBHYVNJeXg4M1RvCjZUNTgrZWdzNExPcDlGSGJFWURV
            eENCang0WVVhTE5zMWw4ZTA3ZHgzQk0KLS0tIFBaL2ozN003UHUzN3k2dldGOVEx
            dkwwMURUNm9rQ3N0NFVRSGFhelNFODAKiUdcryZ+SJdNCdUH769/Rfd9JaMiMOXV
            g+ILcsciIh1EDu1sD51cftuiTld3RiSuMccOQBPSmE7mBS4ekunJ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:31:51Z"
    mac: ENC[AES256_GCM,data:X0qLs0EAZw129iWZNALmTboHyxp2AllCafjN0K9+vjAohsEF5gsI6AzJiO9BHLLpwWpuoAh6kOqp35mdTPRIz8JrfiPGGaFqJWL83ai5YJvJs9pwPEnVHK/UQeM36zJFxbjAQyAroge05iSvusOFF3FVIUGiPkZbF9wQOqFxa00=,iv:PeE6CHCyGnxmCUKnLhQjEoTv0yCQ7HOc58AhfO/j5mY=,tag:StFOBOiXWNes5Sx2WP602g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:yNdbIJgAf4eKM3L7O7z4yQUovFjoKhhdzQeip+TSwiaHWmRCQpyHqt/Sdr57esWS1rdQtSJcW19gIA63s2hx4Xiv62de95RaNQeo4YT0gEe+0KHnGDSghRqIwyOyr7lce4jVSY9uMKUq9eihsJBwcCicTqj2dwPPn6tqKdyb9rBCa0cZVNuUxeWm1ET6n4k39RDYbk5jpGrL75H4o6RUpioTLLo1BIlQDnQCFGa1upa+mT9hYM0CEA==,iv:z+9ci8EemfCjNTd4jbFB+FZjNSx0ZeKMrNJtn0nE7xU=,tag:1vd0/Ei2z35r6jIuXHT94A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bENkeWJDL2VBTGhWaWNw
            N3RjRWRGZVE3b1pOU1ZOODBHYVNJeXg4M1RvCjZUNTgrZWdzNExPcDlGSGJFWURV
            eENCang0WVVhTE5zMWw4ZTA3ZHgzQk0KLS0tIFBaL2ozN003UHUzN3k2dldGOVEx
            dkwwMURUNm9rQ3N0NFVRSGFhelNFODAKiUdcryZ+SJdNCdUH769/Rfd9JaMiMOXV
            g+ILcsciIh1EDu1sD51cftuiTld3RiSuMccOQBPSmE7mBS4ekunJ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:31:51Z"
    mac: ENC[AES256_GCM,data:X0qLs0EAZw129iWZNALmTboHyxp2AllCafjN0K9+vjAohsEF5gsI6AzJiO9BHLLpwWpuoAh6kOqp35mdTPRIz8JrfiPGGaFqJWL83ai5YJvJs9pwPEnVHK/UQeM36zJFxbjAQyAroge05iSvusOFF3FVIUGiPkZbF9wQOqFxa00=,iv:PeE6CHCyGnxmCUKnLhQjEoTv0yCQ7HOc58AhfO/j5mY=,tag:StFOBOiXWNes5Sx2WP602g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:RvCc7KtJWCIYAQ+k9AHxJBSsqLjaVs//2A6TYNJPWVP6Og==,iv:KQQYtqyblXzZCmEuXlbj0Pl30HPKRiBv1H224x4GO+0=,tag:axJKtrdt4KA94LYABRYcvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bENkeWJDL2VBTGhWaWNw
            N3RjRWRGZVE3b1pOU1ZOODBHYVNJeXg4M1RvCjZUNTgrZWdzNExPcDlGSGJFWURV
            eENCang0WVVhTE5zMWw4ZTA3ZHgzQk0KLS0tIFBaL2ozN003UHUzN3k2dldGOVEx
            dkwwMURUNm9rQ3N0NFVRSGFhelNFODAKiUdcryZ+SJdNCdUH769/Rfd9JaMiMOXV
            g+ILcsciIh1EDu1sD51cftuiTld3RiSuMccOQBPSmE7mBS4ekunJ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:31:51Z"
    mac: ENC[AES256_GCM,data:X0qLs0EAZw129iWZNALmTboHyxp2AllCafjN0K9+vjAohsEF5gsI6AzJiO9BHLLpwWpuoAh6kOqp35mdTPRIz8JrfiPGGaFqJWL83ai5YJvJs9pwPEnVHK/UQeM36zJFxbjAQyAroge05iSvusOFF3FVIUGiPkZbF9wQOqFxa00=,iv:PeE6CHCyGnxmCUKnLhQjEoTv0yCQ7HOc58AhfO/j5mY=,tag:StFOBOiXWNes5Sx2WP602g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: siyuan-secrets
namespace: default
type: Opaque
stringData:
    AUTH_CODE: ENC[AES256_GCM,data:T0eCEM89b0/ucULB8Bndhb2S7tY=,iv:igf3F5enCYFjN+qdEd+U89z6dHinzM50l6enqR3IiKk=,tag:u9u9np0B6nYs7+IAbyNGGA==,type:str]
    SIYUAN_URL: ENC[AES256_GCM,data:GisIrqPbgfE4DVJcKs6+HYvt9rbqRJ+3uHtV28E=,iv:hjPKV1LrkmgfUOYzbhleQmtUN2o60yHEdaaLr/nsG2w=,tag:QIJhEbNusZyMf/OVMxwEgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bENkeWJDL2VBTGhWaWNw
            N3RjRWRGZVE3b1pOU1ZOODBHYVNJeXg4M1RvCjZUNTgrZWdzNExPcDlGSGJFWURV
            eENCang0WVVhTE5zMWw4ZTA3ZHgzQk0KLS0tIFBaL2ozN003UHUzN3k2dldGOVEx
            dkwwMURUNm9rQ3N0NFVRSGFhelNFODAKiUdcryZ+SJdNCdUH769/Rfd9JaMiMOXV
            g+ILcsciIh1EDu1sD51cftuiTld3RiSuMccOQBPSmE7mBS4ekunJ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:31:51Z"
    mac: ENC[AES256_GCM,data:X0qLs0EAZw129iWZNALmTboHyxp2AllCafjN0K9+vjAohsEF5gsI6AzJiO9BHLLpwWpuoAh6kOqp35mdTPRIz8JrfiPGGaFqJWL83ai5YJvJs9pwPEnVHK/UQeM36zJFxbjAQyAroge05iSvusOFF3FVIUGiPkZbF9wQOqFxa00=,iv:PeE6CHCyGnxmCUKnLhQjEoTv0yCQ7HOc58AhfO/j5mY=,tag:StFOBOiXWNes5Sx2WP602g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bENkeWJDL2VBTGhWaWNw
            N3RjRWRGZVE3b1pOU1ZOODBHYVNJeXg4M1RvCjZUNTgrZWdzNExPcDlGSGJFWURV
            eENCang0WVVhTE5zMWw4ZTA3ZHgzQk0KLS0tIFBaL2ozN003UHUzN3k2dldGOVEx
            dkwwMURUNm9rQ3N0NFVRSGFhelNFODAKiUdcryZ+SJdNCdUH769/Rfd9JaMiMOXV
            g+ILcsciIh1EDu1sD51cftuiTld3RiSuMccOQBPSmE7mBS4ekunJ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:31:51Z"
    mac: ENC[AES256_GCM,data:X0qLs0EAZw129iWZNALmTboHyxp2AllCafjN0K9+vjAohsEF5gsI6AzJiO9BHLLpwWpuoAh6kOqp35mdTPRIz8JrfiPGGaFqJWL83ai5YJvJs9pwPEnVHK/UQeM36zJFxbjAQyAroge05iSvusOFF3FVIUGiPkZbF9wQOqFxa00=,iv:PeE6CHCyGnxmCUKnLhQjEoTv0yCQ7HOc58AhfO/j5mY=,tag:StFOBOiXWNes5Sx2WP602g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
