apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ByGQ,iv:HRnfp9wa+MxDyIc+iky+YFAyjErJ/OpuSwRe3HgUvyM=,tag:rr2ADBwODO1uVhVrXrkJfQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rTc9Xi0QEUMolVhQOUEaGBaAIBmzTg==,iv:xxEATUOCZkWSGC1hKYJE2wK+9ovn3jmn3nNtR1pT9Ic=,tag:HX9wPAmFCDoXiYmuNkvq/Q==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Acqb,iv:/omZ3Aw+CFIvthCr+fii92PBTsJSjXSopze/+HUZu7E=,tag:7fMbmfMkDcFzLaa7OkHGSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YnQwQVpWM2c1eFgrdERt
            TW0zTHNtTG80cDV2dVdXamZqVnpGemliS1NjCnpEajIybWJ1Z3VsdGg2WUdKUDlt
            ek5ScDhxVzA3Vm1jVjNNaDFJVTVlSmMKLS0tIEZaa1grOWs0U0ZnVGJHN2U5eFFu
            cmFuYnRNUW1SVE9XeFFub1Z5c2ZGbW8K9IQL0uRkCipZ6U9hBWR71/MpAIwlDDa3
            BVv98hgAt3iBOpyxseMKFXmR3KPbDnzf1qASB7WI2AVpdiDfrMEUlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:33:29Z"
    mac: ENC[AES256_GCM,data:INCx36IC/SBCUkL/rgbVBJ8Xz3V2Sx4GWXKNGQhf1pqSsJ1fuMpVPZEP31xgTcp+gtgb06gy4q8ei1hxErj3CAc5M9ZffhDNND9CQ+Oh9OHcWoJPum4krLb/eYVUsbtZZoV/GAPr1QpXT4EdUaf5j4d576tZIroxxE9hNP8uX20=,iv:0tNReVKoiZ1M8A/dxYmSPjDyrMyVaGUNXvF/oBM0+FI=,tag:loNKbt87vTC5hXzrDmJfrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:wkuLQLkWq2urFFe7rPCltCnrj0OMSHm/BxPZrdLN2wU=,iv:Y/IKS6mcvzqK6eyWPj7KMmtUBV8DmFsp9rT4pPBQTNY=,tag:cbIh/nDBnsJjJMiVE8NLWQ==,type:str]
    N8N_URL: ENC[AES256_GCM,data:MR37+U70YNGLkoofT3DdyT39uHvPecojKvziyg==,iv:+IYPImzhLGb6KspgYvSVAHAp9nrO5/Ue0EL5SpSw5l0=,tag:vcX2IfkRuVq4KmvdoV8f/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YnQwQVpWM2c1eFgrdERt
            TW0zTHNtTG80cDV2dVdXamZqVnpGemliS1NjCnpEajIybWJ1Z3VsdGg2WUdKUDlt
            ek5ScDhxVzA3Vm1jVjNNaDFJVTVlSmMKLS0tIEZaa1grOWs0U0ZnVGJHN2U5eFFu
            cmFuYnRNUW1SVE9XeFFub1Z5c2ZGbW8K9IQL0uRkCipZ6U9hBWR71/MpAIwlDDa3
            BVv98hgAt3iBOpyxseMKFXmR3KPbDnzf1qASB7WI2AVpdiDfrMEUlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:33:29Z"
    mac: ENC[AES256_GCM,data:INCx36IC/SBCUkL/rgbVBJ8Xz3V2Sx4GWXKNGQhf1pqSsJ1fuMpVPZEP31xgTcp+gtgb06gy4q8ei1hxErj3CAc5M9ZffhDNND9CQ+Oh9OHcWoJPum4krLb/eYVUsbtZZoV/GAPr1QpXT4EdUaf5j4d576tZIroxxE9hNP8uX20=,iv:0tNReVKoiZ1M8A/dxYmSPjDyrMyVaGUNXvF/oBM0+FI=,tag:loNKbt87vTC5hXzrDmJfrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:bhfhpynDTNLZPveIPIrCmLvnaPxM1VyxcDCb3Z5L3xyWidPYeOIeQPGRO4y8k0u1mVdjxcx8Pkq/SRmxQgzh/Op8TRjLBvCapnHY+u0f/qNrFG3HgEBJEX5NMx50B1jMmWwjP8Qq51uWt7GCm+4DmLvCMwhHpih/dFdWHlRRQ/9sGYys17WS0EIjRPx+eeQtEiB+DIA9X9V+pmUhjo9svTIjmqyUiSYcGZ4cJa+AU/bmnDKlnXXVJQ==,iv:KPdID6mcXwUeMHqHDM5bh+eT/T3QGf08Z9AkumOARD8=,tag:mPEHIkq3T9oxKuEfm8b6Fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YnQwQVpWM2c1eFgrdERt
            TW0zTHNtTG80cDV2dVdXamZqVnpGemliS1NjCnpEajIybWJ1Z3VsdGg2WUdKUDlt
            ek5ScDhxVzA3Vm1jVjNNaDFJVTVlSmMKLS0tIEZaa1grOWs0U0ZnVGJHN2U5eFFu
            cmFuYnRNUW1SVE9XeFFub1Z5c2ZGbW8K9IQL0uRkCipZ6U9hBWR71/MpAIwlDDa3
            BVv98hgAt3iBOpyxseMKFXmR3KPbDnzf1qASB7WI2AVpdiDfrMEUlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:33:29Z"
    mac: ENC[AES256_GCM,data:INCx36IC/SBCUkL/rgbVBJ8Xz3V2Sx4GWXKNGQhf1pqSsJ1fuMpVPZEP31xgTcp+gtgb06gy4q8ei1hxErj3CAc5M9ZffhDNND9CQ+Oh9OHcWoJPum4krLb/eYVUsbtZZoV/GAPr1QpXT4EdUaf5j4d576tZIroxxE9hNP8uX20=,iv:0tNReVKoiZ1M8A/dxYmSPjDyrMyVaGUNXvF/oBM0+FI=,tag:loNKbt87vTC5hXzrDmJfrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:OGigYsOEYBpjOXwbnA/aOOc9POvHIKCKRwE5w57adDPGRQ==,iv:XTaGHxHbgQ3XI9ZsKnKlveSZdG5k6VOSOSVYuWFXMvI=,tag:WBeD301UuTGSTr4iWkk9Wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YnQwQVpWM2c1eFgrdERt
            TW0zTHNtTG80cDV2dVdXamZqVnpGemliS1NjCnpEajIybWJ1Z3VsdGg2WUdKUDlt
            ek5ScDhxVzA3Vm1jVjNNaDFJVTVlSmMKLS0tIEZaa1grOWs0U0ZnVGJHN2U5eFFu
            cmFuYnRNUW1SVE9XeFFub1Z5c2ZGbW8K9IQL0uRkCipZ6U9hBWR71/MpAIwlDDa3
            BVv98hgAt3iBOpyxseMKFXmR3KPbDnzf1qASB7WI2AVpdiDfrMEUlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:33:29Z"
    mac: ENC[AES256_GCM,data:INCx36IC/SBCUkL/rgbVBJ8Xz3V2Sx4GWXKNGQhf1pqSsJ1fuMpVPZEP31xgTcp+gtgb06gy4q8ei1hxErj3CAc5M9ZffhDNND9CQ+Oh9OHcWoJPum4krLb/eYVUsbtZZoV/GAPr1QpXT4EdUaf5j4d576tZIroxxE9hNP8uX20=,iv:0tNReVKoiZ1M8A/dxYmSPjDyrMyVaGUNXvF/oBM0+FI=,tag:loNKbt87vTC5hXzrDmJfrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:TnZtrVfVYj0W3zVQRtndPD+iNm3Tyy1L0kx5,iv:U7NwoHWScBfTdHSzcLlggGjdVuk3ic+B7NOKDuaTEAg=,tag:MhZjlC9r3qhIYG+QM0IwbA==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:8EhMnOhXsAOa5u2Fj19qjCxqfAdhXwMgSjJdBnRyBok=,iv:yKd01sfeRYAUslBSzCRudZBmN6P+81LVhx3K8NB0pdI=,tag:QNWOclRhkuUkONmEtB2Nrw==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:vsN2A9is7u39B0r3Ip0fU52NK1ahgW95kcR/ESaNSy8=,iv:G6ilEV3T056K3QOI7UzW4M1nunnJCxlQUlUZoDor6D4=,tag:B6uxkw8/FnbaWzuQXbi64w==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:1WQgd1EQ0OiW0h7xU5m0E1e/RibmwRRwXQXr5oiux2xw50/1I/238I4OtVBN0EWx/aPt/z32YPXc3jHB3fJPbuM/rwSyiuSf09yGKdNiRtnuvir9zYyDN1z8J9f+CyqONsLNwGwI61snikId5EcDyV17bEPYu0XaVLie+st1ShukMwyQk65KZOKVsZ8vTF0aMNw3oZ6s/HU4H/2OzrgGyZ/5Moh0cbFeEFNTYd68KPUO+4p4Z9DvqK2V7nuWp9CBSkACCJHbIik9CZ7OOVsmJe/qUT3azwJOipgryTU5utLTMzeqFtW0axbJYEPn,iv:ll0LbnUuo4BFwr8aHS4nTGBAdv4G7WaGdFNGV6k3SX8=,tag:A5QCYYnjABOD8JKRp1Tg4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YnQwQVpWM2c1eFgrdERt
            TW0zTHNtTG80cDV2dVdXamZqVnpGemliS1NjCnpEajIybWJ1Z3VsdGg2WUdKUDlt
            ek5ScDhxVzA3Vm1jVjNNaDFJVTVlSmMKLS0tIEZaa1grOWs0U0ZnVGJHN2U5eFFu
            cmFuYnRNUW1SVE9XeFFub1Z5c2ZGbW8K9IQL0uRkCipZ6U9hBWR71/MpAIwlDDa3
            BVv98hgAt3iBOpyxseMKFXmR3KPbDnzf1qASB7WI2AVpdiDfrMEUlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:33:29Z"
    mac: ENC[AES256_GCM,data:INCx36IC/SBCUkL/rgbVBJ8Xz3V2Sx4GWXKNGQhf1pqSsJ1fuMpVPZEP31xgTcp+gtgb06gy4q8ei1hxErj3CAc5M9ZffhDNND9CQ+Oh9OHcWoJPum4krLb/eYVUsbtZZoV/GAPr1QpXT4EdUaf5j4d576tZIroxxE9hNP8uX20=,iv:0tNReVKoiZ1M8A/dxYmSPjDyrMyVaGUNXvF/oBM0+FI=,tag:loNKbt87vTC5hXzrDmJfrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:3QZuDXYxqg==,iv:3cEiX6jiwDXKMkZoas6zgKHdN2Bka2FofSdjN3i6KtM=,tag:gQNC6gSosTMP5mkGGYAKng==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:0cA3ZRficZlJ2qHKFiqgbQc7PSQ=,iv:03NfD/5f7k8u/WPTgCsieOEo5011qxbbv7ARXmxJReA=,tag:gy+IwsQcVTUvJo2ZjDjovQ==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:iQdLaSNgjrDwYrKMFi9Vp7bzndaVMNAMmpjz/nKVuZ4NbQdbEA==,iv:fDVHxWW+m5EBc30iz+dejDdNqpv88oQopRCmsxGZSY8=,tag:Bw34En/VCdPI3zQBNuiEQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YnQwQVpWM2c1eFgrdERt
            TW0zTHNtTG80cDV2dVdXamZqVnpGemliS1NjCnpEajIybWJ1Z3VsdGg2WUdKUDlt
            ek5ScDhxVzA3Vm1jVjNNaDFJVTVlSmMKLS0tIEZaa1grOWs0U0ZnVGJHN2U5eFFu
            cmFuYnRNUW1SVE9XeFFub1Z5c2ZGbW8K9IQL0uRkCipZ6U9hBWR71/MpAIwlDDa3
            BVv98hgAt3iBOpyxseMKFXmR3KPbDnzf1qASB7WI2AVpdiDfrMEUlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:33:29Z"
    mac: ENC[AES256_GCM,data:INCx36IC/SBCUkL/rgbVBJ8Xz3V2Sx4GWXKNGQhf1pqSsJ1fuMpVPZEP31xgTcp+gtgb06gy4q8ei1hxErj3CAc5M9ZffhDNND9CQ+Oh9OHcWoJPum4krLb/eYVUsbtZZoV/GAPr1QpXT4EdUaf5j4d576tZIroxxE9hNP8uX20=,iv:0tNReVKoiZ1M8A/dxYmSPjDyrMyVaGUNXvF/oBM0+FI=,tag:loNKbt87vTC5hXzrDmJfrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:1dEcgcGUE2DUGeqnaL+SoJh0S2NVD/cx3fhknVdwTV1/gSQ/Jcm47jqsxSM=,iv:9PFmBYyeXqzFkGnM1KbgiocRpAg8D9j2Yanb3iUsGL0=,tag:k98ormA6dXrxsOJTFBzazg==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:9P5ztXudx/ts/Xg+K5Vluo+DjXZtH2tUFzNP,iv:wiKANywPO0vvc60YmxS6feyzv4S8L6icrIAh/v92BRM=,tag:Ql+Ld9IE4021W4fkVKDLDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YnQwQVpWM2c1eFgrdERt
            TW0zTHNtTG80cDV2dVdXamZqVnpGemliS1NjCnpEajIybWJ1Z3VsdGg2WUdKUDlt
            ek5ScDhxVzA3Vm1jVjNNaDFJVTVlSmMKLS0tIEZaa1grOWs0U0ZnVGJHN2U5eFFu
            cmFuYnRNUW1SVE9XeFFub1Z5c2ZGbW8K9IQL0uRkCipZ6U9hBWR71/MpAIwlDDa3
            BVv98hgAt3iBOpyxseMKFXmR3KPbDnzf1qASB7WI2AVpdiDfrMEUlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:33:29Z"
    mac: ENC[AES256_GCM,data:INCx36IC/SBCUkL/rgbVBJ8Xz3V2Sx4GWXKNGQhf1pqSsJ1fuMpVPZEP31xgTcp+gtgb06gy4q8ei1hxErj3CAc5M9ZffhDNND9CQ+Oh9OHcWoJPum4krLb/eYVUsbtZZoV/GAPr1QpXT4EdUaf5j4d576tZIroxxE9hNP8uX20=,iv:0tNReVKoiZ1M8A/dxYmSPjDyrMyVaGUNXvF/oBM0+FI=,tag:loNKbt87vTC5hXzrDmJfrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
