apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:SVcu,iv:6fTn87nDZOXKTuO3Ets07s7o9aLushbdgU1/OospWaI=,tag:SPSlJFwovUEIedbAz7+G2A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:jm52mvaB+26McGN4JyCOaivPyS1glw==,iv:QfW7OtEgGa639QP0BXZmmnjOR3xfUONG02V5AzUBJfY=,tag:4jkFDWVjq3ceuilOakSIGQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:YvU+,iv:NyZ0RJwe/BrQXV8/YV/GRlNHQQT6NS+L1j7Vi5YNvXs=,tag:V7Cf1yNNPdi0hX7vqHTloQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVnBhdXorM2ZUZWFkVzBh
              VWJHZUc2ZGRuNUwzRnQvdHVWL3JiczNpWUhvCjN5TGxkSnkyYVFNTTVXSUlEQis3
              Ni8rNWdPZHAyaktaL1YwVGFQUnNDRUEKLS0tIHZiMWtyT0dQRng3ejRiRzc1VEFr
              RUtabUVLTzkyY2NIV1VVS3g1WndBYVEK+WaVJgzaio6ER3ctoVY0qNAfFG6OXh7Y
              d9DHrziHC92BPVqGwl5FUfk9+EzoCTrq+FD9AuoX/yMRXHKSFXaheQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T03:48:33Z"
    mac: ENC[AES256_GCM,data:j0FAEin8b4VojcPPQkaQzDA2dOrOddfdU40GxeNcOJZxxCZQ5ZVUffvdD2jIUYKzVi1m3FU2K3bB8kg5N4VbfxN+e0z02fLm2NE5Y5OTjyhpT6L0fLpaDFyJnRaexDVoely3oyt2hJ0DMg9X41ic+X8Eo0xyQTS1TtuAiG6k6Ac=,iv:EiDn9C169vpVEEfdMQBUmemY/ApQb3R9rBIhxMdZuAk=,tag:64wY2EftOo7y9zs99vEuWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:CWo5sKXzX74uztxpzhvF77V+60PBzsYvChSX3gSu4C4=,iv:iRyE+TY2S9A+OJacuf2AoS2Sa8Lbx7bTZwblPriOUXM=,tag:j/Cl3DkkCvAVCOel2bcSWA==,type:str]
    N8N_URL: ENC[AES256_GCM,data:46uUcHLzmEAOFNbHlcoRuMYolMSaPcpWikkItw==,iv:f9R24DBbPmJq/L+8Y4iaa1dhYFE1MxhBzMRU0XKzqzU=,tag:BaSxo1f1I5zVv3K6quExnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVnBhdXorM2ZUZWFkVzBh
              VWJHZUc2ZGRuNUwzRnQvdHVWL3JiczNpWUhvCjN5TGxkSnkyYVFNTTVXSUlEQis3
              Ni8rNWdPZHAyaktaL1YwVGFQUnNDRUEKLS0tIHZiMWtyT0dQRng3ejRiRzc1VEFr
              RUtabUVLTzkyY2NIV1VVS3g1WndBYVEK+WaVJgzaio6ER3ctoVY0qNAfFG6OXh7Y
              d9DHrziHC92BPVqGwl5FUfk9+EzoCTrq+FD9AuoX/yMRXHKSFXaheQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T03:48:33Z"
    mac: ENC[AES256_GCM,data:j0FAEin8b4VojcPPQkaQzDA2dOrOddfdU40GxeNcOJZxxCZQ5ZVUffvdD2jIUYKzVi1m3FU2K3bB8kg5N4VbfxN+e0z02fLm2NE5Y5OTjyhpT6L0fLpaDFyJnRaexDVoely3oyt2hJ0DMg9X41ic+X8Eo0xyQTS1TtuAiG6k6Ac=,iv:EiDn9C169vpVEEfdMQBUmemY/ApQb3R9rBIhxMdZuAk=,tag:64wY2EftOo7y9zs99vEuWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:JaKmu02TVkFmoMPEHORA03f0PXxbRiuMmqy7/1Eusx8hiqwY2CRTVCxVKSFOU34uuZuRJHo7rL7fWrHgVEeoIaPtp2Cv8sZLrpSfyW8PGSWRisB2Kur9wjKhsPrNv3oZqzJ/YCYH/v2+ppKtkMeF6qc9WkvWYDh4O6+qXMqI9CC8bhOyB1wyfp2apGfLJh4RtCyBvV3eqqHlsdVR7kZhKVoU9PwR35yX2WzgfDLL4mueSgvlflzYLQ==,iv:PxoWWHeHsyF80VJ6Ad0Mm/TyCArATj/QcwdG6h3HkfM=,tag:burxkboFdMxgJ6eq9iXqpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVnBhdXorM2ZUZWFkVzBh
              VWJHZUc2ZGRuNUwzRnQvdHVWL3JiczNpWUhvCjN5TGxkSnkyYVFNTTVXSUlEQis3
              Ni8rNWdPZHAyaktaL1YwVGFQUnNDRUEKLS0tIHZiMWtyT0dQRng3ejRiRzc1VEFr
              RUtabUVLTzkyY2NIV1VVS3g1WndBYVEK+WaVJgzaio6ER3ctoVY0qNAfFG6OXh7Y
              d9DHrziHC92BPVqGwl5FUfk9+EzoCTrq+FD9AuoX/yMRXHKSFXaheQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T03:48:33Z"
    mac: ENC[AES256_GCM,data:j0FAEin8b4VojcPPQkaQzDA2dOrOddfdU40GxeNcOJZxxCZQ5ZVUffvdD2jIUYKzVi1m3FU2K3bB8kg5N4VbfxN+e0z02fLm2NE5Y5OTjyhpT6L0fLpaDFyJnRaexDVoely3oyt2hJ0DMg9X41ic+X8Eo0xyQTS1TtuAiG6k6Ac=,iv:EiDn9C169vpVEEfdMQBUmemY/ApQb3R9rBIhxMdZuAk=,tag:64wY2EftOo7y9zs99vEuWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:dGDhrpmZs6i3DXd5M1DnehdIQpKza99IhHxonZelyGAKfw==,iv:ex2pKFspenA981F2N5GxZq79A3Lk3aVE5sZcM5z3Ie8=,tag:Ae2F6CLFauCvusQxIS25VA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVnBhdXorM2ZUZWFkVzBh
              VWJHZUc2ZGRuNUwzRnQvdHVWL3JiczNpWUhvCjN5TGxkSnkyYVFNTTVXSUlEQis3
              Ni8rNWdPZHAyaktaL1YwVGFQUnNDRUEKLS0tIHZiMWtyT0dQRng3ejRiRzc1VEFr
              RUtabUVLTzkyY2NIV1VVS3g1WndBYVEK+WaVJgzaio6ER3ctoVY0qNAfFG6OXh7Y
              d9DHrziHC92BPVqGwl5FUfk9+EzoCTrq+FD9AuoX/yMRXHKSFXaheQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T03:48:33Z"
    mac: ENC[AES256_GCM,data:j0FAEin8b4VojcPPQkaQzDA2dOrOddfdU40GxeNcOJZxxCZQ5ZVUffvdD2jIUYKzVi1m3FU2K3bB8kg5N4VbfxN+e0z02fLm2NE5Y5OTjyhpT6L0fLpaDFyJnRaexDVoely3oyt2hJ0DMg9X41ic+X8Eo0xyQTS1TtuAiG6k6Ac=,iv:EiDn9C169vpVEEfdMQBUmemY/ApQb3R9rBIhxMdZuAk=,tag:64wY2EftOo7y9zs99vEuWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:yzImRRTZ1D2rEUNNicsk2uwG1XyvDfyJ3Oot,iv:bOaU4P5eJE7/TZwB4+XARL5y3lWTR73LHI278g8u/XY=,tag:FFfkqzP21Yvw7O4CpwjgDg==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:7umh7F96x/V0nrRYFpTvrOV1yL7yVPOpz7adK0qzeBg=,iv:oCt32+5WRXQ5BV5005I5uZdTATzSu//2dD7N87aK/2Y=,tag:fEGbbIgeX7tcjgvMzcSmdQ==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:9+FWVm8iMqc287M08fyQSuECeJI4o65L7yZy1MeCWw8=,iv:ybimTseecFZR/j4epIj3k8gfU/nfH5P+3Wsgs2hGdU4=,tag:LZgk+gvvXoyxbiWBoswP6Q==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:xaWAhN3JBMpU//OT1OCHMsQ1MPUml/SkmQPhjVcOyiPNgkd92lu72eppPeficWVKf6W9argDbniAcZBzFXelwuvwcOAW5wP9e11OxIJwFmT7x005opjfh9k3sSvfWws9U2hr5qu3FDQEMoTHn+IJcU9yMFrcuc4Ys5L7bNnQEqRnhgkk/ZUq+0JKRyu6gV1fm87y52q9Q20+U8LG0yBjZDv6qbmXpY5NHAkWHfy6CUEVITDS+JTvrLDa6slSaBLFGU55TOcS9U5P1gqafGm9YqqtqPsjFRzqIby1wmD8JTJnU3/1ppmMcUN8s7q2,iv:DYHFHf/fLry85+gKz/XlOZyi0O0NbZKZpUGavYIiyv0=,tag:QblJEKeRASl3NRBVRCYSpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVnBhdXorM2ZUZWFkVzBh
              VWJHZUc2ZGRuNUwzRnQvdHVWL3JiczNpWUhvCjN5TGxkSnkyYVFNTTVXSUlEQis3
              Ni8rNWdPZHAyaktaL1YwVGFQUnNDRUEKLS0tIHZiMWtyT0dQRng3ejRiRzc1VEFr
              RUtabUVLTzkyY2NIV1VVS3g1WndBYVEK+WaVJgzaio6ER3ctoVY0qNAfFG6OXh7Y
              d9DHrziHC92BPVqGwl5FUfk9+EzoCTrq+FD9AuoX/yMRXHKSFXaheQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T03:48:33Z"
    mac: ENC[AES256_GCM,data:j0FAEin8b4VojcPPQkaQzDA2dOrOddfdU40GxeNcOJZxxCZQ5ZVUffvdD2jIUYKzVi1m3FU2K3bB8kg5N4VbfxN+e0z02fLm2NE5Y5OTjyhpT6L0fLpaDFyJnRaexDVoely3oyt2hJ0DMg9X41ic+X8Eo0xyQTS1TtuAiG6k6Ac=,iv:EiDn9C169vpVEEfdMQBUmemY/ApQb3R9rBIhxMdZuAk=,tag:64wY2EftOo7y9zs99vEuWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:d7gFBLsbAQ==,iv:YZ7kNf1ekMf4tpv1EMq2zWD0T7vYFgFrkWBbuCAjYLs=,tag:KkNkE2hoae61s/0XT2M3Lg==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:eSlpl7rVYT1A2KDFyv61cR64jI0=,iv:XbTGv333g34Poj81MQBkDydl8fogt8fjZq6VJ2ndu5c=,tag:U2Jp24ERJNbJoMnr4Q4G5Q==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:SCTi6tuST/e9mHDInAjwzYiQqGwWqsWGx6bjwkr1tAsb0ksCvA==,iv:xBrWK4f3bngTASTrrlteoZNgCI8fpmuYj1FBBDFlUus=,tag:W/1OJuGs/taROrhw4SvRhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVnBhdXorM2ZUZWFkVzBh
              VWJHZUc2ZGRuNUwzRnQvdHVWL3JiczNpWUhvCjN5TGxkSnkyYVFNTTVXSUlEQis3
              Ni8rNWdPZHAyaktaL1YwVGFQUnNDRUEKLS0tIHZiMWtyT0dQRng3ejRiRzc1VEFr
              RUtabUVLTzkyY2NIV1VVS3g1WndBYVEK+WaVJgzaio6ER3ctoVY0qNAfFG6OXh7Y
              d9DHrziHC92BPVqGwl5FUfk9+EzoCTrq+FD9AuoX/yMRXHKSFXaheQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T03:48:33Z"
    mac: ENC[AES256_GCM,data:j0FAEin8b4VojcPPQkaQzDA2dOrOddfdU40GxeNcOJZxxCZQ5ZVUffvdD2jIUYKzVi1m3FU2K3bB8kg5N4VbfxN+e0z02fLm2NE5Y5OTjyhpT6L0fLpaDFyJnRaexDVoely3oyt2hJ0DMg9X41ic+X8Eo0xyQTS1TtuAiG6k6Ac=,iv:EiDn9C169vpVEEfdMQBUmemY/ApQb3R9rBIhxMdZuAk=,tag:64wY2EftOo7y9zs99vEuWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: 1
kind: Secret
metadata:
    name: freescout-secrets
    namespace: default
type: Opage
stringData:
    FREESCOUT_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:5HtJ3Fk5rYab96JX+tySfB5KUJo=,iv:YZdH6cVCEXH2ZpFZCectsbS17RPFoD97TiB+RM57xAA=,tag:JKbxXYrpqao/xKSH8h2MYg==,type:str]
    FREESCOUT_DB_PASSWORD: ENC[AES256_GCM,data:ucbxKCcrNDvJjZcJrRKqRs05uAs=,iv:IB+f8jMkWRokTYrrI3J6XNMaKHaPskHrIHNX7gq0kQw=,tag:xZcWxU5obQDpu0fDJMaILQ==,type:str]
    FREESCOUT_ADMIN_EMAIL: ENC[AES256_GCM,data:n5jlSUcGZ2WCgRSvhRAIls+8MwAkcnA=,iv:QlArapKjWekQlgpN3v8BBSvwcCB/TXgGgdaDB/9LPTU=,tag:74mtei10wlMK2Ikr1bEw3g==,type:str]
    FREESCOUT_ADMIN_PASSWORD: ENC[AES256_GCM,data:EMaffARELymu2MzxxTtW36YAtqc=,iv:21cm0CoHr5KRIRHydJZmPdL5cdPHsgv0QNYzCm0prtI=,tag:O7tSn7tubh74UhnSds1o9w==,type:str]
    FREESCOUT_SITE_URL: ENC[AES256_GCM,data:Hr4N7qdyYjLZTtCMmK2taSWHfKsNzajD7R95ZQ==,iv:7ukf+7SoHXhTgYu+nTX/jyIVqOqEkbj+VwDryLFTro8=,tag:0UPs6jF1hdc4YAHjXFjREg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVnBhdXorM2ZUZWFkVzBh
              VWJHZUc2ZGRuNUwzRnQvdHVWL3JiczNpWUhvCjN5TGxkSnkyYVFNTTVXSUlEQis3
              Ni8rNWdPZHAyaktaL1YwVGFQUnNDRUEKLS0tIHZiMWtyT0dQRng3ejRiRzc1VEFr
              RUtabUVLTzkyY2NIV1VVS3g1WndBYVEK+WaVJgzaio6ER3ctoVY0qNAfFG6OXh7Y
              d9DHrziHC92BPVqGwl5FUfk9+EzoCTrq+FD9AuoX/yMRXHKSFXaheQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T03:48:33Z"
    mac: ENC[AES256_GCM,data:j0FAEin8b4VojcPPQkaQzDA2dOrOddfdU40GxeNcOJZxxCZQ5ZVUffvdD2jIUYKzVi1m3FU2K3bB8kg5N4VbfxN+e0z02fLm2NE5Y5OTjyhpT6L0fLpaDFyJnRaexDVoely3oyt2hJ0DMg9X41ic+X8Eo0xyQTS1TtuAiG6k6Ac=,iv:EiDn9C169vpVEEfdMQBUmemY/ApQb3R9rBIhxMdZuAk=,tag:64wY2EftOo7y9zs99vEuWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
