apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:7YqY,iv:aJEi472Nb1nBuG7pivrusvLle8CmJTCARdc/qFbv/Qo=,tag:3wrPYHMFq5ubejK9coL/hQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PYV1wcTymarEkLU6YyjPjcbT0tLTbg==,iv:2muX/NNOB2tCC5SQ6sCW7ve5htiSCkYJNaCa+cID26c=,tag:/nQOHl8RjpCF6w/LF1waBw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:MsP7,iv:ZmH8jPSc2sb2wavs7DnAly3Szu6BfGnD4vnKs1AQ0bY=,tag:cs+jHyhiikm6YMJfQgi6EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtemVHL3NZRkpSQ3J5SDVZ
            bi83YUd5UU5jYUUzZDlNUktjallLQ1A5ZjF3CmZaUFBhdlpjSDJrNTk2YXpVbS93
            cFNVNVRzTGowVWFGNDVuMndkMVdsUjgKLS0tIG8xMzEwMjlnTjRJQ1JzbTJlQkpr
            c2NFekR4dGtKZFIvZkNRVWpLTS96UEEKQpLxoqIfBUWG7cUkDCRBbUK+QlgjTAo5
            qKub219QFjsUb+JhM9H+hKwLPhiyq5x9rdNeHp7/KrCdLkhyPKWthQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T16:19:03Z"
    mac: ENC[AES256_GCM,data:+mWGLbv11tm6eNLSzo5FG7fPqGsNWj9v9tQ0Qc7/rugE6L/sI1m3WJ8QgCOc3pT28De+RdlluWdt5L3+GWj2ccB13nwPWF3cmzR14+cwYwYxA/rWqUSL+ra+8WGqL0kkHj6Ey1ZC14Hl93/aIus/0t+p7ar/9jeIOzGYRNVKwaE=,iv:41w2ee7oYSfQJglYyOOIiwn+GeC2G9Ex0UFP+yVTNrg=,tag:J8dxmraP5sB39rIlsIkvkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:K1Wca4CnXxBM1RcffMGIu8MhIuWBue2aJ5U5/VlTwRM=,iv:435E6a+bBTzXqJ9gohVAk4XWq62HaAGs6T9unn2e5XU=,tag:Ny5CAt9ZmJvxWW+dGpVXyw==,type:str]
    N8N_URL: ENC[AES256_GCM,data:jf+Nz2gI0jCO17iIhCF2U34cKL1x64on7Aepag==,iv:MqIcvUqzRnR7Dv0NHKqTBuzKH3jGtnIm4e9P1Pfkfk4=,tag:ZP88un+tBM7QAhehnj59uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtemVHL3NZRkpSQ3J5SDVZ
            bi83YUd5UU5jYUUzZDlNUktjallLQ1A5ZjF3CmZaUFBhdlpjSDJrNTk2YXpVbS93
            cFNVNVRzTGowVWFGNDVuMndkMVdsUjgKLS0tIG8xMzEwMjlnTjRJQ1JzbTJlQkpr
            c2NFekR4dGtKZFIvZkNRVWpLTS96UEEKQpLxoqIfBUWG7cUkDCRBbUK+QlgjTAo5
            qKub219QFjsUb+JhM9H+hKwLPhiyq5x9rdNeHp7/KrCdLkhyPKWthQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T16:19:03Z"
    mac: ENC[AES256_GCM,data:+mWGLbv11tm6eNLSzo5FG7fPqGsNWj9v9tQ0Qc7/rugE6L/sI1m3WJ8QgCOc3pT28De+RdlluWdt5L3+GWj2ccB13nwPWF3cmzR14+cwYwYxA/rWqUSL+ra+8WGqL0kkHj6Ey1ZC14Hl93/aIus/0t+p7ar/9jeIOzGYRNVKwaE=,iv:41w2ee7oYSfQJglYyOOIiwn+GeC2G9Ex0UFP+yVTNrg=,tag:J8dxmraP5sB39rIlsIkvkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:igU4yDSGFClSuRm7AwCmr5L5AQS1hB7q6r9EU4e0fQcCP2jLJZZy6nl75IpHkophMUBbU0AcGJO3txmnNO5/7cg+lUpTztjL7kzqZdONF8wGwWHvQccZdwbcUeKye0AfMvNn60Sr3C/1qweeV0QGgt+/McJzrP5szPmODxO1hVHXyXouM8zeeBeuBisk7FYxvjFxcEivD3GzTxJDHSR1YTPCKvFXMZKg7j2Heb9K9V2odRQ5uIzz5w==,iv:tVr4mkt8WkWrKzcuU8MQ+1BXP4g+ASDcEA/BQ2wwnHI=,tag:7L9zhVJ6bnCnisimIN6ZlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtemVHL3NZRkpSQ3J5SDVZ
            bi83YUd5UU5jYUUzZDlNUktjallLQ1A5ZjF3CmZaUFBhdlpjSDJrNTk2YXpVbS93
            cFNVNVRzTGowVWFGNDVuMndkMVdsUjgKLS0tIG8xMzEwMjlnTjRJQ1JzbTJlQkpr
            c2NFekR4dGtKZFIvZkNRVWpLTS96UEEKQpLxoqIfBUWG7cUkDCRBbUK+QlgjTAo5
            qKub219QFjsUb+JhM9H+hKwLPhiyq5x9rdNeHp7/KrCdLkhyPKWthQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T16:19:03Z"
    mac: ENC[AES256_GCM,data:+mWGLbv11tm6eNLSzo5FG7fPqGsNWj9v9tQ0Qc7/rugE6L/sI1m3WJ8QgCOc3pT28De+RdlluWdt5L3+GWj2ccB13nwPWF3cmzR14+cwYwYxA/rWqUSL+ra+8WGqL0kkHj6Ey1ZC14Hl93/aIus/0t+p7ar/9jeIOzGYRNVKwaE=,iv:41w2ee7oYSfQJglYyOOIiwn+GeC2G9Ex0UFP+yVTNrg=,tag:J8dxmraP5sB39rIlsIkvkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:MrTYlyZBWOwtLKlHcf4BZzF8RngaIFhsUSKaB27NepKiRg==,iv:5OB5E0qgr+qSPSI4YErCjhu3UVTVc5aHIPKgtgGiFUQ=,tag:Q/awYYZ0YYsKu3BR2+UZSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtemVHL3NZRkpSQ3J5SDVZ
            bi83YUd5UU5jYUUzZDlNUktjallLQ1A5ZjF3CmZaUFBhdlpjSDJrNTk2YXpVbS93
            cFNVNVRzTGowVWFGNDVuMndkMVdsUjgKLS0tIG8xMzEwMjlnTjRJQ1JzbTJlQkpr
            c2NFekR4dGtKZFIvZkNRVWpLTS96UEEKQpLxoqIfBUWG7cUkDCRBbUK+QlgjTAo5
            qKub219QFjsUb+JhM9H+hKwLPhiyq5x9rdNeHp7/KrCdLkhyPKWthQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T16:19:03Z"
    mac: ENC[AES256_GCM,data:+mWGLbv11tm6eNLSzo5FG7fPqGsNWj9v9tQ0Qc7/rugE6L/sI1m3WJ8QgCOc3pT28De+RdlluWdt5L3+GWj2ccB13nwPWF3cmzR14+cwYwYxA/rWqUSL+ra+8WGqL0kkHj6Ey1ZC14Hl93/aIus/0t+p7ar/9jeIOzGYRNVKwaE=,iv:41w2ee7oYSfQJglYyOOIiwn+GeC2G9Ex0UFP+yVTNrg=,tag:J8dxmraP5sB39rIlsIkvkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: siyuan-secrets
    namespace: default
type: Opaque
stringData:
    AUTH_CODE: ENC[AES256_GCM,data:7t2/Unf0xijghZ0waw8Cesg6W10=,iv:IZwO88PxktrtGyuwp9hrkN9+6fYwwjUNiHvAOqdgYVw=,tag:xUzFKPh9yx/NV5iuuSvD8g==,type:str]
    SIYUAN_URL: ENC[AES256_GCM,data:FVWDkcec7swZFe0eqAzP+49YD0sifwVyl7ztaPM=,iv:hmXLd3bsEZF/N8bpdfiqY+PhikI/NEIQGMbG6KScWRY=,tag:T5hNkUl5QtvxMEHb7yEb3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtemVHL3NZRkpSQ3J5SDVZ
            bi83YUd5UU5jYUUzZDlNUktjallLQ1A5ZjF3CmZaUFBhdlpjSDJrNTk2YXpVbS93
            cFNVNVRzTGowVWFGNDVuMndkMVdsUjgKLS0tIG8xMzEwMjlnTjRJQ1JzbTJlQkpr
            c2NFekR4dGtKZFIvZkNRVWpLTS96UEEKQpLxoqIfBUWG7cUkDCRBbUK+QlgjTAo5
            qKub219QFjsUb+JhM9H+hKwLPhiyq5x9rdNeHp7/KrCdLkhyPKWthQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T16:19:03Z"
    mac: ENC[AES256_GCM,data:+mWGLbv11tm6eNLSzo5FG7fPqGsNWj9v9tQ0Qc7/rugE6L/sI1m3WJ8QgCOc3pT28De+RdlluWdt5L3+GWj2ccB13nwPWF3cmzR14+cwYwYxA/rWqUSL+ra+8WGqL0kkHj6Ey1ZC14Hl93/aIus/0t+p7ar/9jeIOzGYRNVKwaE=,iv:41w2ee7oYSfQJglYyOOIiwn+GeC2G9Ex0UFP+yVTNrg=,tag:J8dxmraP5sB39rIlsIkvkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:K2eZzzN69DmOlkEzZWUQSpNNlOEA6QlEvJKUaXmKLBNcrw==,iv:xxm7o31bbBrUZpxbwORZsI+YAGPMWF+pTk0OFdVIb/8=,tag:4fwW04Tnl1H/OrdZsKD62A==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:BI0qfFiGPdEQ9dCRWJ5Hm8oZmnd1bZfhBGfLKF4KyzE=,iv:+CREW1VdZ6kwzzYDvePA/vIzB6E6VJG3mj+5P7IjtrU=,tag:JFLkW+RgOZdALACuaseCmg==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:SrvwWeMD6MWjY55gfwXAQIS0QdL5dBZ3WpMPnj/UH3M=,iv:tpXvZuuo3Nz0Sg+xUZsthJJ60kWLcJSkAjZbu9YOsiE=,tag:BzM/0dcIA97x753Z4W2uIA==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:SFR9q+n9Fepy4yJ+jOgZclG7OV8P8tWjpH5YsOjntojwj5n5PvM3h/wQF70vD44R9zuU1gTHTHbTQzEZbGYpIxqvMqmMVDenfgZJJ9PWcp5M6yvGZK7va3aScSWRHRyEzCourxbUw2svC5262mzrPy9rOFuSyKchDKvYjISvYgkiWY6jyJH4ntSA9n9Q1vSvSM9D+Znt4BwENP4laMECOJZcEM8SwrqCJ7r280/m2k5rOywkBaMtRdvmC8OgNHJ04P7s8h/aFkTJh6ncaHHQV779AKJl/L1+GwfLWK+USQxfTRH6xqANjImUhFn0,iv:R0fxEfu9Y9SneOz0P/TIComWcPpwNvbRJTu383V3zoU=,tag:M3JhXYOBlufEhoLRhDLDbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtemVHL3NZRkpSQ3J5SDVZ
            bi83YUd5UU5jYUUzZDlNUktjallLQ1A5ZjF3CmZaUFBhdlpjSDJrNTk2YXpVbS93
            cFNVNVRzTGowVWFGNDVuMndkMVdsUjgKLS0tIG8xMzEwMjlnTjRJQ1JzbTJlQkpr
            c2NFekR4dGtKZFIvZkNRVWpLTS96UEEKQpLxoqIfBUWG7cUkDCRBbUK+QlgjTAo5
            qKub219QFjsUb+JhM9H+hKwLPhiyq5x9rdNeHp7/KrCdLkhyPKWthQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T16:19:03Z"
    mac: ENC[AES256_GCM,data:+mWGLbv11tm6eNLSzo5FG7fPqGsNWj9v9tQ0Qc7/rugE6L/sI1m3WJ8QgCOc3pT28De+RdlluWdt5L3+GWj2ccB13nwPWF3cmzR14+cwYwYxA/rWqUSL+ra+8WGqL0kkHj6Ey1ZC14Hl93/aIus/0t+p7ar/9jeIOzGYRNVKwaE=,iv:41w2ee7oYSfQJglYyOOIiwn+GeC2G9Ex0UFP+yVTNrg=,tag:J8dxmraP5sB39rIlsIkvkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
