apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:dYWy,iv:dIgtIhr/xHAoEVoIVm00K4JjK25iZ2xVyV/P4XJjLKU=,tag:npl8W2tL+/11JTTrijuWFA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:EOaiNygYNFZJb0qkrPB+WtA1j5XEbA==,iv:Wh7XBpCm3rr21zYWEYdCh+5jx3jQ88JF9oakszZasy0=,tag:fMOiItQrzV7e5bLPBeNNJg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:qSna,iv:Z3pwdocP12MwlFdReHn/PRjk8ev7+RE1Bh1QHAlNvuY=,tag:POCVZK6J6eZWE4vO+ob86A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRseW1vL0ZKNWtJY3R2
            MFZSYlRGcFlLa0FRL2NuK1ViRGozQm5KeUJBCk1DckQwMVFlUDBCdEtRNVBkeW84
            K3JvS3MxT0U0eXpLOG9TU1IrZjAxVFkKLS0tIHNJQVRCTEtqSkwxa2E5N3Vja1FJ
            M1RpUHAxdG5US1haTURKNkEyNklUdEEKVxeHM9yfwvxMHGlITC4OzW3cn/MG46UN
            rvqQA3fOoQKCd44VmcdVQWT7i26M42QBYdItnA8dWrmK/A8QPTeTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:43:37Z"
    mac: ENC[AES256_GCM,data:3QMvC11LVvk99A4LBCyceot2P9wDmDL52QlH0p6k7gy+OF/3eZHs0PlLH3cytpM0AGVji3ZKid0npAXTua2h0xq7bF2uLa80VGYeekXoO2Nxjw1w3eOtFTAeSNyTX4loO10bdzwJdBLsBT+W1nOv/oNj+pVonlXETouhBCkqZAY=,iv:ihq3R1c6XxDA4QlN2oZeniln4ZBmsWIIW1p7TeTLqLg=,tag:vihMQ8toV+u6avSLSaBwkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:jHds+lQ3Cqnl+Wb/jndCGsNpp1IuQiU08kPDnNt69SM=,iv:46YpCHiyfkBEV3vVADJ8fTv7iI2MHOxBTpCJU4bsBEU=,tag:O9JdbQ/1NxD8KN5gy58Fyw==,type:str]
    N8N_URL: ENC[AES256_GCM,data:6412VuiI3hwFq+B1FxibcX0UpB09LshtQqfbaw==,iv:xK8kFD0vH1JrqiVCqeX2CVtmx2AIrtkLDeVn35QZ+cU=,tag:0D5w9x8LPzEInAkW98bNjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRseW1vL0ZKNWtJY3R2
            MFZSYlRGcFlLa0FRL2NuK1ViRGozQm5KeUJBCk1DckQwMVFlUDBCdEtRNVBkeW84
            K3JvS3MxT0U0eXpLOG9TU1IrZjAxVFkKLS0tIHNJQVRCTEtqSkwxa2E5N3Vja1FJ
            M1RpUHAxdG5US1haTURKNkEyNklUdEEKVxeHM9yfwvxMHGlITC4OzW3cn/MG46UN
            rvqQA3fOoQKCd44VmcdVQWT7i26M42QBYdItnA8dWrmK/A8QPTeTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:43:37Z"
    mac: ENC[AES256_GCM,data:3QMvC11LVvk99A4LBCyceot2P9wDmDL52QlH0p6k7gy+OF/3eZHs0PlLH3cytpM0AGVji3ZKid0npAXTua2h0xq7bF2uLa80VGYeekXoO2Nxjw1w3eOtFTAeSNyTX4loO10bdzwJdBLsBT+W1nOv/oNj+pVonlXETouhBCkqZAY=,iv:ihq3R1c6XxDA4QlN2oZeniln4ZBmsWIIW1p7TeTLqLg=,tag:vihMQ8toV+u6avSLSaBwkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:fMaqTTlmp/Ew4bV+r/Xl4iRTByGQIBs1njqvmYo7gOyZfGG3tZ1tkII7LFA3whYD738CtyWQvjivd9PUffWkSvpYEJqvtgKOBurOuoDQIgiNYUVTq1NEts9aSGgfbjeUGhFRtpLdGzNCPlk/J5qu/CJFLMi3vHTdq7p7Yas3R8YhuTYhEmZr3sB4gZPs7P3kAo3kK7aIyEiVaDeAY3d0TSKr3Q2iCznIexXMtQSDfOCV09haXkkwFQ==,iv:xykA6/92CnXGlhIhgaLpN1ZsBO4ijMKxy5qRSKowR7Q=,tag:SxT0nF8hxlIwP53dPVNz0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRseW1vL0ZKNWtJY3R2
            MFZSYlRGcFlLa0FRL2NuK1ViRGozQm5KeUJBCk1DckQwMVFlUDBCdEtRNVBkeW84
            K3JvS3MxT0U0eXpLOG9TU1IrZjAxVFkKLS0tIHNJQVRCTEtqSkwxa2E5N3Vja1FJ
            M1RpUHAxdG5US1haTURKNkEyNklUdEEKVxeHM9yfwvxMHGlITC4OzW3cn/MG46UN
            rvqQA3fOoQKCd44VmcdVQWT7i26M42QBYdItnA8dWrmK/A8QPTeTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:43:37Z"
    mac: ENC[AES256_GCM,data:3QMvC11LVvk99A4LBCyceot2P9wDmDL52QlH0p6k7gy+OF/3eZHs0PlLH3cytpM0AGVji3ZKid0npAXTua2h0xq7bF2uLa80VGYeekXoO2Nxjw1w3eOtFTAeSNyTX4loO10bdzwJdBLsBT+W1nOv/oNj+pVonlXETouhBCkqZAY=,iv:ihq3R1c6XxDA4QlN2oZeniln4ZBmsWIIW1p7TeTLqLg=,tag:vihMQ8toV+u6avSLSaBwkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:5nAg8ICdq0WNPsCAG1a4pNnDim/Pbv2hSRypKjBXwfcnbQ==,iv:OqIAw5oWEW4698sbOrgyTtgvqZ049vRK7TLwW+0GkYY=,tag:1AIl4dlMUw/dX+bcp0biyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRseW1vL0ZKNWtJY3R2
            MFZSYlRGcFlLa0FRL2NuK1ViRGozQm5KeUJBCk1DckQwMVFlUDBCdEtRNVBkeW84
            K3JvS3MxT0U0eXpLOG9TU1IrZjAxVFkKLS0tIHNJQVRCTEtqSkwxa2E5N3Vja1FJ
            M1RpUHAxdG5US1haTURKNkEyNklUdEEKVxeHM9yfwvxMHGlITC4OzW3cn/MG46UN
            rvqQA3fOoQKCd44VmcdVQWT7i26M42QBYdItnA8dWrmK/A8QPTeTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:43:37Z"
    mac: ENC[AES256_GCM,data:3QMvC11LVvk99A4LBCyceot2P9wDmDL52QlH0p6k7gy+OF/3eZHs0PlLH3cytpM0AGVji3ZKid0npAXTua2h0xq7bF2uLa80VGYeekXoO2Nxjw1w3eOtFTAeSNyTX4loO10bdzwJdBLsBT+W1nOv/oNj+pVonlXETouhBCkqZAY=,iv:ihq3R1c6XxDA4QlN2oZeniln4ZBmsWIIW1p7TeTLqLg=,tag:vihMQ8toV+u6avSLSaBwkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:s0FLJfRirofcKPOa/wLo7QoGvqX2sT+/6mCG,iv:SXOTXnVYnNwObe/PEecL4LrGQaoYxnoP6Pl99iPKz/E=,tag:PJO5Wzn6yOOd+nkp6QNNHA==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:QxHo9EV6NAGWZ1Yz56DHdGyciRWfs0zf+lM7ubHwy/o=,iv:1ZgFPnxTQphAYIdvkpgkbT/mojOugSpHZfuOT94Jj/w=,tag:GSKUAO55/XjiN7XunDmOyA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:a4gF2vRScyga7vMOUgvSMa1Dc/Yk3BIEEzEqbfp3vVA=,iv:nbpvJ9/Vu0Jdg2olISb1aG48aRX7jYC2cURJtSdmu8Y=,tag:8MUQTw4GDLxSJMLlXLjx9A==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:6uKzLTx4gouMJVWPOY4ns2fp+1tbI201+2ISCoEqD35qqF5QGE97o+0UzMj9MsFtnjZxotoreZIn8v00R8iI5TSufZQgdkbD8hgtgh/ixVD9mAfE8eZnskQ6fdfl2d22JVbz+GLc02G1zkrvMtL4J1n1Oh4ght+vZqjrjZok+krGz3flCceee/sT6357jpm0f9zoRdT9Um6LEKEPnfD0ghVyfvfBp7U1OHG+o8wVqhg3AvhLX3ZlqJrUC4lvjNyvEY3+x7cZx3rAFU8BcvMlwdupFAkWRieBJxPQcs6upVro0LMCg5ULeUWXzu6z,iv:/KMriTbJNcVBqFaE5dH08a5Eqctx0o0MaPG5CRvrrLo=,tag:E0zCfYtksAdmFYX6EH3BiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRseW1vL0ZKNWtJY3R2
            MFZSYlRGcFlLa0FRL2NuK1ViRGozQm5KeUJBCk1DckQwMVFlUDBCdEtRNVBkeW84
            K3JvS3MxT0U0eXpLOG9TU1IrZjAxVFkKLS0tIHNJQVRCTEtqSkwxa2E5N3Vja1FJ
            M1RpUHAxdG5US1haTURKNkEyNklUdEEKVxeHM9yfwvxMHGlITC4OzW3cn/MG46UN
            rvqQA3fOoQKCd44VmcdVQWT7i26M42QBYdItnA8dWrmK/A8QPTeTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:43:37Z"
    mac: ENC[AES256_GCM,data:3QMvC11LVvk99A4LBCyceot2P9wDmDL52QlH0p6k7gy+OF/3eZHs0PlLH3cytpM0AGVji3ZKid0npAXTua2h0xq7bF2uLa80VGYeekXoO2Nxjw1w3eOtFTAeSNyTX4loO10bdzwJdBLsBT+W1nOv/oNj+pVonlXETouhBCkqZAY=,iv:ihq3R1c6XxDA4QlN2oZeniln4ZBmsWIIW1p7TeTLqLg=,tag:vihMQ8toV+u6avSLSaBwkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:lwet+g6dOg==,iv:vp5ro4Rh0y5GHabg4ixI/oOUy0n2px6VrniWPEhhkoI=,tag:djxEbdTSWLdYaWo7gzzCqA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:K3g4PrJAS0jjaqj2E/d69hKQP7E=,iv:wnGL5TP39hdMFkaqEb1ndFOKCGBcaI07i5PtRhWXHgw=,tag:dcK2k/2LC1UGY7A7f7U1ew==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:LlgiVRGLzj6EIemLvuZRTrhrEvoKqNpA+zzRCMYaLudbIsvy3A==,iv:iC9qSl155DJ3uiGIUlHdKu/a0abE3aKv5ngjM+qtcPQ=,tag:R9iXevj3hYhBpSjlFEaNjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRseW1vL0ZKNWtJY3R2
            MFZSYlRGcFlLa0FRL2NuK1ViRGozQm5KeUJBCk1DckQwMVFlUDBCdEtRNVBkeW84
            K3JvS3MxT0U0eXpLOG9TU1IrZjAxVFkKLS0tIHNJQVRCTEtqSkwxa2E5N3Vja1FJ
            M1RpUHAxdG5US1haTURKNkEyNklUdEEKVxeHM9yfwvxMHGlITC4OzW3cn/MG46UN
            rvqQA3fOoQKCd44VmcdVQWT7i26M42QBYdItnA8dWrmK/A8QPTeTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:43:37Z"
    mac: ENC[AES256_GCM,data:3QMvC11LVvk99A4LBCyceot2P9wDmDL52QlH0p6k7gy+OF/3eZHs0PlLH3cytpM0AGVji3ZKid0npAXTua2h0xq7bF2uLa80VGYeekXoO2Nxjw1w3eOtFTAeSNyTX4loO10bdzwJdBLsBT+W1nOv/oNj+pVonlXETouhBCkqZAY=,iv:ihq3R1c6XxDA4QlN2oZeniln4ZBmsWIIW1p7TeTLqLg=,tag:vihMQ8toV+u6avSLSaBwkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:8KRijM6WOOeyb+YUL1eVztMYl7zrm9Xa2pFZBL+vJ91qaq14DPjaa30CTBk=,iv:SBEaxmBnqziCT5C0UGy6nXZQqnUGphsdyEKiYPubsqw=,tag:sHLQ3OX432EiCna/Lmn/rQ==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:x0MHFwD38t25cEf1CpndUgr4nGZ043zGua9y,iv:STLmiSlFWGVT2PfZ8n964vHJnkTIRz0yoS/yzuye5eE=,tag:0AHCpSObcglO9NU0vLa3yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRseW1vL0ZKNWtJY3R2
            MFZSYlRGcFlLa0FRL2NuK1ViRGozQm5KeUJBCk1DckQwMVFlUDBCdEtRNVBkeW84
            K3JvS3MxT0U0eXpLOG9TU1IrZjAxVFkKLS0tIHNJQVRCTEtqSkwxa2E5N3Vja1FJ
            M1RpUHAxdG5US1haTURKNkEyNklUdEEKVxeHM9yfwvxMHGlITC4OzW3cn/MG46UN
            rvqQA3fOoQKCd44VmcdVQWT7i26M42QBYdItnA8dWrmK/A8QPTeTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:43:37Z"
    mac: ENC[AES256_GCM,data:3QMvC11LVvk99A4LBCyceot2P9wDmDL52QlH0p6k7gy+OF/3eZHs0PlLH3cytpM0AGVji3ZKid0npAXTua2h0xq7bF2uLa80VGYeekXoO2Nxjw1w3eOtFTAeSNyTX4loO10bdzwJdBLsBT+W1nOv/oNj+pVonlXETouhBCkqZAY=,iv:ihq3R1c6XxDA4QlN2oZeniln4ZBmsWIIW1p7TeTLqLg=,tag:vihMQ8toV+u6avSLSaBwkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: default
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:/ur2XIxzUVzLMBak6avc7Y2wna4Ec1Kzjf0M97YIfU4MWtavqaumhQ==,iv:hRbWHVUkrIKaU858hPHh8mfbju8hD5OietfeH89Pnq8=,tag:8Z0vMywsOdMvVDFp4rve/A==,type:str]
    RENOVATE_GITHUB_TOKEN: ENC[AES256_GCM,data:pE3iAbwse4uof1bIzqg3u3Rx3+roXimkXogbANSD83p/GDIUeGiotg==,iv:hSPSD50/YTcg7LypARNMKWWSp3tht4XKiF/Y+VaNJUs=,tag:IN5tG0JA7ibaiqG/5qi65A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRseW1vL0ZKNWtJY3R2
            MFZSYlRGcFlLa0FRL2NuK1ViRGozQm5KeUJBCk1DckQwMVFlUDBCdEtRNVBkeW84
            K3JvS3MxT0U0eXpLOG9TU1IrZjAxVFkKLS0tIHNJQVRCTEtqSkwxa2E5N3Vja1FJ
            M1RpUHAxdG5US1haTURKNkEyNklUdEEKVxeHM9yfwvxMHGlITC4OzW3cn/MG46UN
            rvqQA3fOoQKCd44VmcdVQWT7i26M42QBYdItnA8dWrmK/A8QPTeTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:43:37Z"
    mac: ENC[AES256_GCM,data:3QMvC11LVvk99A4LBCyceot2P9wDmDL52QlH0p6k7gy+OF/3eZHs0PlLH3cytpM0AGVji3ZKid0npAXTua2h0xq7bF2uLa80VGYeekXoO2Nxjw1w3eOtFTAeSNyTX4loO10bdzwJdBLsBT+W1nOv/oNj+pVonlXETouhBCkqZAY=,iv:ihq3R1c6XxDA4QlN2oZeniln4ZBmsWIIW1p7TeTLqLg=,tag:vihMQ8toV+u6avSLSaBwkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-secrets
    namespace: default
type: Opaque
stringData:
    JELLYFIN_KEY: ENC[AES256_GCM,data:fci/nNaRynPrGks6YNYe3XPWAyO+RtMK5th1k4m8mNU=,iv:omMYHouBPo/8/Ju5LcfTbSslIziHx9YU1znI7ErCUTM=,tag:V1fxEkHI7QlGjuOTPw88Eg==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:kPGLP1jIJoiXo06MZRsFeNyJWXTMiNvIRqc=,iv:RgPc5n52IBzRCchlFFv0RObxFzWXEGhzmxiD9Rg8vy8=,tag:b0yxbuGI+1ChbWyUOa3XqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRseW1vL0ZKNWtJY3R2
            MFZSYlRGcFlLa0FRL2NuK1ViRGozQm5KeUJBCk1DckQwMVFlUDBCdEtRNVBkeW84
            K3JvS3MxT0U0eXpLOG9TU1IrZjAxVFkKLS0tIHNJQVRCTEtqSkwxa2E5N3Vja1FJ
            M1RpUHAxdG5US1haTURKNkEyNklUdEEKVxeHM9yfwvxMHGlITC4OzW3cn/MG46UN
            rvqQA3fOoQKCd44VmcdVQWT7i26M42QBYdItnA8dWrmK/A8QPTeTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:43:37Z"
    mac: ENC[AES256_GCM,data:3QMvC11LVvk99A4LBCyceot2P9wDmDL52QlH0p6k7gy+OF/3eZHs0PlLH3cytpM0AGVji3ZKid0npAXTua2h0xq7bF2uLa80VGYeekXoO2Nxjw1w3eOtFTAeSNyTX4loO10bdzwJdBLsBT+W1nOv/oNj+pVonlXETouhBCkqZAY=,iv:ihq3R1c6XxDA4QlN2oZeniln4ZBmsWIIW1p7TeTLqLg=,tag:vihMQ8toV+u6avSLSaBwkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-secrets
    namespace: default
type: Opaque
stringData:
    HA_TOKEN: ENC[AES256_GCM,data:IkEUqvFPAaf9tA5PMYynNuWTNGhSbTC+K2TN8RLkuLRLHhq7a5RxxdUUhv1I5J8HFzMzt9xg2l1PFSw5Jqa0iZGE2KsVJ+ANS7YOaO2lP2Qj2AwE1b0PYxi+1CZfSBfgeAK2BTrP6yv7qQNpxdXPiS0J1deYDiNy2hxVtlTEzrQ6H2dDtlkUJHEZbWnsj2276KTLhaLQIHmNgBr2nmLU251p1k8m0Z+IufkdaS+Q687hxol1nB4R,iv:yozELRFxBOiWOUyd1ZzWcsPZGkSUd3/hIwgzIyiUu/k=,tag:l1G+4GK2MKDrKT624+B8Gw==,type:str]
    HA_IP: ENC[AES256_GCM,data:xlFvnWg4XHQyzjzPAm8n7lSFVpiC6k6qyvk=,iv:GxwObQ9aSjNRoUpzGsFn67mH1TidCS9crmB0s6SU154=,tag:1gR0TROccN0A3SeCHX3c1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRseW1vL0ZKNWtJY3R2
            MFZSYlRGcFlLa0FRL2NuK1ViRGozQm5KeUJBCk1DckQwMVFlUDBCdEtRNVBkeW84
            K3JvS3MxT0U0eXpLOG9TU1IrZjAxVFkKLS0tIHNJQVRCTEtqSkwxa2E5N3Vja1FJ
            M1RpUHAxdG5US1haTURKNkEyNklUdEEKVxeHM9yfwvxMHGlITC4OzW3cn/MG46UN
            rvqQA3fOoQKCd44VmcdVQWT7i26M42QBYdItnA8dWrmK/A8QPTeTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T16:43:37Z"
    mac: ENC[AES256_GCM,data:3QMvC11LVvk99A4LBCyceot2P9wDmDL52QlH0p6k7gy+OF/3eZHs0PlLH3cytpM0AGVji3ZKid0npAXTua2h0xq7bF2uLa80VGYeekXoO2Nxjw1w3eOtFTAeSNyTX4loO10bdzwJdBLsBT+W1nOv/oNj+pVonlXETouhBCkqZAY=,iv:ihq3R1c6XxDA4QlN2oZeniln4ZBmsWIIW1p7TeTLqLg=,tag:vihMQ8toV+u6avSLSaBwkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
