apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:sKKH,iv:Q7AHXgZoWbPrMgWyWC5IwodGorRjQHEmj6FdqfzKWYs=,tag:bzgufGqPLAdMChgWMInBxw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:yEsKzRRscPF28xwtlVSEkVdGYHE+Lw==,iv:qQ/UL/KGS5m8xTMVBnH8O85ktwpWumGME0xqB9jFhmg=,tag:fcC5soQm+vdTeo82ErPKEA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:I3G6,iv:tngOUj2AB8mL0FrooFmspva7PRimDyVgv9CYPVmBZQA=,tag:TBMmzO/BwjzozIUnNh6TNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdmF1ZnNlN2pzNlN0cXdj
            VmQ0SVZIQlFGam1OcG9hYjU0cjJGWkhJOVQ4ClBQQ3phRGVZdHJ3U0RRYmNTMktH
            Z1AzaUVWc1E3eUZJdlNWOXNSWDZIWFUKLS0tIGlaMFNWa2JtaFZndzhUc1Rmdmxy
            Q0lBb3JyUGhPZWVjeWQySFp2MllkMlkKNQ7bjHQc6F4Ggt+VzTpdYmL2ifnU10Kj
            45mDpuBNS4FtMwTHjrfkGEPR7VySBOvCkxbEFCAUNWgO/0sSUef9rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T18:21:12Z"
    mac: ENC[AES256_GCM,data:A/gf6vGtkSTACMV55KeTYB1vCatUV+Hm71rGoqChetzamDZJ40idgp49ttDlLct4e3R0ds5qM2sjLbGuKPEdgnZlrLjGsfgvc26AIeAWiyXOT8+GG87TOdBpdks3Hvzg9ZH5faCg37t8m0w6+kOzLieE1uAmGvmZhPedvJqhhw0=,iv:YRZDwtY9WvVkUs0XKW3u42MA467moJ+ujt+R/Nccs7A=,tag:0/5qMoR+aj2KyaGojSrrug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:IdI/MbNQ+Ilc0lj3wGB3KHkQrvlw1z6Xpn2HJa4CY1A=,iv:ZPmaKlkI9w9EJjg5MUp3Qosmghq4npTXn+584zypHpg=,tag:ThLhArV2Ob064ANIr/tcYg==,type:str]
    N8N_URL: ENC[AES256_GCM,data:2DQ5OGPBxhkGHLI132Pbw372ZQaic6nS+ri5pQ==,iv:saxmoUrO0KGVyWsO1XLxDPwdHlicAZnLno3qdHBgxzQ=,tag:pJ9KX72I5TTQp6ffXEuCdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdmF1ZnNlN2pzNlN0cXdj
            VmQ0SVZIQlFGam1OcG9hYjU0cjJGWkhJOVQ4ClBQQ3phRGVZdHJ3U0RRYmNTMktH
            Z1AzaUVWc1E3eUZJdlNWOXNSWDZIWFUKLS0tIGlaMFNWa2JtaFZndzhUc1Rmdmxy
            Q0lBb3JyUGhPZWVjeWQySFp2MllkMlkKNQ7bjHQc6F4Ggt+VzTpdYmL2ifnU10Kj
            45mDpuBNS4FtMwTHjrfkGEPR7VySBOvCkxbEFCAUNWgO/0sSUef9rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T18:21:12Z"
    mac: ENC[AES256_GCM,data:A/gf6vGtkSTACMV55KeTYB1vCatUV+Hm71rGoqChetzamDZJ40idgp49ttDlLct4e3R0ds5qM2sjLbGuKPEdgnZlrLjGsfgvc26AIeAWiyXOT8+GG87TOdBpdks3Hvzg9ZH5faCg37t8m0w6+kOzLieE1uAmGvmZhPedvJqhhw0=,iv:YRZDwtY9WvVkUs0XKW3u42MA467moJ+ujt+R/Nccs7A=,tag:0/5qMoR+aj2KyaGojSrrug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:P6K/+mmLeRXK2EoeUy5kocxGNTF8xKKSfT4rxN80UR0POO2WTjdVBP30M/Nfk/YddXvsE4V8QgZkfNq2lAggBfH+0bVGZv3Q1Jg6014xPzD7mkkYaMhGlslhgrRy+3VfMxy3+nLPRuiwuE18dCuEVpLLwl7wlkMon+sK4t6r8M8Zha7H8biycW8y+vq1H91FS15bUwHVNXuO/rFNzvLaSN8PYHUbt0+bpNwNIf09dCD0+bgcSouRhA==,iv:rcJkGdQLkPDpXEKp0WbeIQpf9trKdVa3APsEfIXWGBY=,tag:ZJteZAm+kAH2fszHmKA+SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdmF1ZnNlN2pzNlN0cXdj
            VmQ0SVZIQlFGam1OcG9hYjU0cjJGWkhJOVQ4ClBQQ3phRGVZdHJ3U0RRYmNTMktH
            Z1AzaUVWc1E3eUZJdlNWOXNSWDZIWFUKLS0tIGlaMFNWa2JtaFZndzhUc1Rmdmxy
            Q0lBb3JyUGhPZWVjeWQySFp2MllkMlkKNQ7bjHQc6F4Ggt+VzTpdYmL2ifnU10Kj
            45mDpuBNS4FtMwTHjrfkGEPR7VySBOvCkxbEFCAUNWgO/0sSUef9rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T18:21:12Z"
    mac: ENC[AES256_GCM,data:A/gf6vGtkSTACMV55KeTYB1vCatUV+Hm71rGoqChetzamDZJ40idgp49ttDlLct4e3R0ds5qM2sjLbGuKPEdgnZlrLjGsfgvc26AIeAWiyXOT8+GG87TOdBpdks3Hvzg9ZH5faCg37t8m0w6+kOzLieE1uAmGvmZhPedvJqhhw0=,iv:YRZDwtY9WvVkUs0XKW3u42MA467moJ+ujt+R/Nccs7A=,tag:0/5qMoR+aj2KyaGojSrrug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:w4jkYZONJ5N6tkftV8xNO7xlop3sL5dcfreUrc+FKFvvJA==,iv:/cvdiyEsZIeRSyMGnerRkv4nZCh1fSSaGcWM3q3b8to=,tag:e6O7f5HRim/OoxWRSusfNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdmF1ZnNlN2pzNlN0cXdj
            VmQ0SVZIQlFGam1OcG9hYjU0cjJGWkhJOVQ4ClBQQ3phRGVZdHJ3U0RRYmNTMktH
            Z1AzaUVWc1E3eUZJdlNWOXNSWDZIWFUKLS0tIGlaMFNWa2JtaFZndzhUc1Rmdmxy
            Q0lBb3JyUGhPZWVjeWQySFp2MllkMlkKNQ7bjHQc6F4Ggt+VzTpdYmL2ifnU10Kj
            45mDpuBNS4FtMwTHjrfkGEPR7VySBOvCkxbEFCAUNWgO/0sSUef9rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T18:21:12Z"
    mac: ENC[AES256_GCM,data:A/gf6vGtkSTACMV55KeTYB1vCatUV+Hm71rGoqChetzamDZJ40idgp49ttDlLct4e3R0ds5qM2sjLbGuKPEdgnZlrLjGsfgvc26AIeAWiyXOT8+GG87TOdBpdks3Hvzg9ZH5faCg37t8m0w6+kOzLieE1uAmGvmZhPedvJqhhw0=,iv:YRZDwtY9WvVkUs0XKW3u42MA467moJ+ujt+R/Nccs7A=,tag:0/5qMoR+aj2KyaGojSrrug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: siyuan-secrets
    namespace: default
type: Opaque
stringData:
    AUTH_CODE: ENC[AES256_GCM,data:Z3ssohAR3Azc9Rbo5LVWrcrUxP0=,iv:fSUSCSxUZCoAmslGNfbfL8VmTYhIH2BsVwif8Mj99IQ=,tag:s6G0aasMF7ku6gJzrsYypA==,type:str]
    SIYUAN_URL: ENC[AES256_GCM,data:IrxPyFjH53bBStzU/MJM3O/mn55d1LPOIbv/zxU=,iv:+0ndOAy1An2sw3nWLU+7X1aBYe9j7RrF0UkwZdPOsCA=,tag:Gv3BZofOHYiGIyE3FEcw8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdmF1ZnNlN2pzNlN0cXdj
            VmQ0SVZIQlFGam1OcG9hYjU0cjJGWkhJOVQ4ClBQQ3phRGVZdHJ3U0RRYmNTMktH
            Z1AzaUVWc1E3eUZJdlNWOXNSWDZIWFUKLS0tIGlaMFNWa2JtaFZndzhUc1Rmdmxy
            Q0lBb3JyUGhPZWVjeWQySFp2MllkMlkKNQ7bjHQc6F4Ggt+VzTpdYmL2ifnU10Kj
            45mDpuBNS4FtMwTHjrfkGEPR7VySBOvCkxbEFCAUNWgO/0sSUef9rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T18:21:12Z"
    mac: ENC[AES256_GCM,data:A/gf6vGtkSTACMV55KeTYB1vCatUV+Hm71rGoqChetzamDZJ40idgp49ttDlLct4e3R0ds5qM2sjLbGuKPEdgnZlrLjGsfgvc26AIeAWiyXOT8+GG87TOdBpdks3Hvzg9ZH5faCg37t8m0w6+kOzLieE1uAmGvmZhPedvJqhhw0=,iv:YRZDwtY9WvVkUs0XKW3u42MA467moJ+ujt+R/Nccs7A=,tag:0/5qMoR+aj2KyaGojSrrug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:06Fo/MigvjTXWKyFGMc8Exge+ZeaCDOkrhlt,iv:+1suUIkN5naFSQc/0P4LUwnO12ZLDo+SbXb9j7RJlWc=,tag:zHtCI9JWUmo5LPLnY2yx1g==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:h84oanHpNMS9QM7Smxnp/pNXfGqWz9o/l+Ux+q4TRJE=,iv:4KFXfBl/eFjzsBexpbBcOqbbGadp0yNbbUsQ+GKZsu0=,tag:MaIJ7tfpDO3Qhfo/6IoEUQ==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:cEpgj51yhlw+8TbHIgJvrFlOcj8mlp6pRhPHx5nTLjo=,iv:JsqLJhGfesy4VH8XZNVgN51M/L0QnV5F6U1Jpnb/C64=,tag:97JC4uZic44H4zegrv7irw==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:WvCxUkw2+Cxjq3aUzgfnH5rxrpjLcGAej1+ah44UM7kuJACJTj/CBh8Qd+C6hgkVKQ8C2Hl/XULvOGA+MK8hopY8e6SZpgvW4oxbGx1IBiuXYQkgEkf0cFOOLc3A7xmMzoYswPQkCehNgdwIj4k4ZIT8ud+xePk8f/gz8cbEdsEyEA0rOGPD3gDMlPHdVgg2GxZf48vRVC++ZBbILwFMZS0VS56ROa7J9OrPyjKOy1u68VskUSZ7qr2ZB4dhietYue0kJAi1bTRum3NK7e1UD1FvFhjjLGd1pN9AQYyQE3wLCTlnPTVCSQLmCh7U,iv:fWKQu/drPKqElLU1ohRKvmIomx8p3NdEt4N323x5NzQ=,tag:v6owjna9PNVTPkdOluI1GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdmF1ZnNlN2pzNlN0cXdj
            VmQ0SVZIQlFGam1OcG9hYjU0cjJGWkhJOVQ4ClBQQ3phRGVZdHJ3U0RRYmNTMktH
            Z1AzaUVWc1E3eUZJdlNWOXNSWDZIWFUKLS0tIGlaMFNWa2JtaFZndzhUc1Rmdmxy
            Q0lBb3JyUGhPZWVjeWQySFp2MllkMlkKNQ7bjHQc6F4Ggt+VzTpdYmL2ifnU10Kj
            45mDpuBNS4FtMwTHjrfkGEPR7VySBOvCkxbEFCAUNWgO/0sSUef9rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T18:21:12Z"
    mac: ENC[AES256_GCM,data:A/gf6vGtkSTACMV55KeTYB1vCatUV+Hm71rGoqChetzamDZJ40idgp49ttDlLct4e3R0ds5qM2sjLbGuKPEdgnZlrLjGsfgvc26AIeAWiyXOT8+GG87TOdBpdks3Hvzg9ZH5faCg37t8m0w6+kOzLieE1uAmGvmZhPedvJqhhw0=,iv:YRZDwtY9WvVkUs0XKW3u42MA467moJ+ujt+R/Nccs7A=,tag:0/5qMoR+aj2KyaGojSrrug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
