apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:m9dMjsmx8V9tJEgl/X0+x2txo7/s5lvtWjW9FzFGZfmH8w==,iv:kO5l8f2/Uwjnm/SQbAipK8QyWdzSWEHpnlvMuQRqUvg=,tag:IleNE+RabLqmxK1fiOkWZA==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:oWBQ,iv:I5NGgAR6XJDIGvNmOlhAb9OKouoK9qfhUlIa9X2xrXo=,tag:D9IN16EbFQbYiAQCgJJV5A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:OTtVB5WI5n+EBm8FFf3BLv6t54fnOA==,iv:ts/dN4kaOg1aWF7cpx7cTbyZu07ITkIvHj3oIlfUUoI=,tag:0EReAja+4oigiXbE+B7VGg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:I5rK,iv:hSCFiBkBbEGFixY6dPKQtKvEER8oWAdUGNmfBOBy8C8=,tag:obzRZoqzcN3uVmPIOIgkMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dG5oTEFMSk92REluRTJV
            Z0tLSTFIWFJvUVJUU0k2MW1lbDI0NkdySEgwClJLcE9PZUp2UndaTWZDd3YvUTEx
            bmRDU1lZR0lqbDF5OTE4SFpmU3U2UjQKLS0tIDNJQldJbjlsTUxwR1FoQm84T0Y3
            V3dUSGRhQXhPNEJyVXhVQlZkUEIvT3MK9kaZiB4JZPhvfoDYSSDb18V6HsapnJik
            Utxe/V5tUtMBhhNPYvkMB2zyAhcdHGkEQYQxJUQNuh/uYzBT3qpMPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:44:17Z"
    mac: ENC[AES256_GCM,data:vkYSZSfanMcI0OJ5c0irRVyfwAY/bebixHl01m4ffBlRWqF0ih2F3L/N8oN3+qbIh/3dvxk9rCSYyD6lYQlyduq+xFc6x2dayeZySb0NLJ+rc12JfgRwnM8habTvoCYAygG5LXyCNLOIjrRLqW7MtHCwvtu1u9HBTgcd4DoSNoM=,iv:MWO0HVTebzzLhFdC5Q+5aoEc8A20kr/orsZ86i2a+A0=,tag:+tR4GY8Qun14I+mUq3ye4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:XmuWgVmOP3hmvFm8X3gcLqeVcFpW1hx62vCFaAp64h4=,iv:gCrasoi8Xh373Q+M4sya8zhLfEpDv3D5Tx89FlwKsGE=,tag:TLZhZVluW25ZiaLqDG4+tA==,type:str]
    N8N_URL: ENC[AES256_GCM,data:mvjej7T4awP6qBCV9yoFcNlV0jlNRilaa8Qp3Q==,iv:KQ6pG6ogWvu2A4riGcBSRjFgcDeMrDlInchWCbZ1i3I=,tag:XLfEWxLBfOCY7A+gjRTV4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dG5oTEFMSk92REluRTJV
            Z0tLSTFIWFJvUVJUU0k2MW1lbDI0NkdySEgwClJLcE9PZUp2UndaTWZDd3YvUTEx
            bmRDU1lZR0lqbDF5OTE4SFpmU3U2UjQKLS0tIDNJQldJbjlsTUxwR1FoQm84T0Y3
            V3dUSGRhQXhPNEJyVXhVQlZkUEIvT3MK9kaZiB4JZPhvfoDYSSDb18V6HsapnJik
            Utxe/V5tUtMBhhNPYvkMB2zyAhcdHGkEQYQxJUQNuh/uYzBT3qpMPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:44:17Z"
    mac: ENC[AES256_GCM,data:vkYSZSfanMcI0OJ5c0irRVyfwAY/bebixHl01m4ffBlRWqF0ih2F3L/N8oN3+qbIh/3dvxk9rCSYyD6lYQlyduq+xFc6x2dayeZySb0NLJ+rc12JfgRwnM8habTvoCYAygG5LXyCNLOIjrRLqW7MtHCwvtu1u9HBTgcd4DoSNoM=,iv:MWO0HVTebzzLhFdC5Q+5aoEc8A20kr/orsZ86i2a+A0=,tag:+tR4GY8Qun14I+mUq3ye4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:kR5P2gDlZkMoMb6cJCnY+SLh9rZDL3RY3daYqpXKTrOSSTaqFg7K2wpaB5RL5/qHSojHM8RpFUbqEo06fLO5vb0T522/OpkHU/Gc4xjwBTJquvvoGg5CbcrMVoW078QHm2DsChJGljdw1bkHYv8v9aXBOD3yl/QmjsKxa0CkEmBt/AULKeqfGvzXD/N65FzuHmH9J/x3fCsOd9Ux4Y14Mey3Fr86PsjZZjY2+HV+2LiT7SvC0JDgnA==,iv:ul98q50JjV222NFNhvSJ82+Zh9cCapCRYzFy8fb3/ug=,tag:4FZUBhZi8gWjzUmbfscgNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dG5oTEFMSk92REluRTJV
            Z0tLSTFIWFJvUVJUU0k2MW1lbDI0NkdySEgwClJLcE9PZUp2UndaTWZDd3YvUTEx
            bmRDU1lZR0lqbDF5OTE4SFpmU3U2UjQKLS0tIDNJQldJbjlsTUxwR1FoQm84T0Y3
            V3dUSGRhQXhPNEJyVXhVQlZkUEIvT3MK9kaZiB4JZPhvfoDYSSDb18V6HsapnJik
            Utxe/V5tUtMBhhNPYvkMB2zyAhcdHGkEQYQxJUQNuh/uYzBT3qpMPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:44:17Z"
    mac: ENC[AES256_GCM,data:vkYSZSfanMcI0OJ5c0irRVyfwAY/bebixHl01m4ffBlRWqF0ih2F3L/N8oN3+qbIh/3dvxk9rCSYyD6lYQlyduq+xFc6x2dayeZySb0NLJ+rc12JfgRwnM8habTvoCYAygG5LXyCNLOIjrRLqW7MtHCwvtu1u9HBTgcd4DoSNoM=,iv:MWO0HVTebzzLhFdC5Q+5aoEc8A20kr/orsZ86i2a+A0=,tag:+tR4GY8Qun14I+mUq3ye4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:lSwznb/mR7gZFXtexOOwLVudfmAWdAwdPqlE/upqNaCZDQ==,iv:AGw/yqSXveRdyW6fXiF4wk1mr2UESDFJBNz5NLfksAM=,tag:xvQjoyBXE4EI7xyUsoucBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dG5oTEFMSk92REluRTJV
            Z0tLSTFIWFJvUVJUU0k2MW1lbDI0NkdySEgwClJLcE9PZUp2UndaTWZDd3YvUTEx
            bmRDU1lZR0lqbDF5OTE4SFpmU3U2UjQKLS0tIDNJQldJbjlsTUxwR1FoQm84T0Y3
            V3dUSGRhQXhPNEJyVXhVQlZkUEIvT3MK9kaZiB4JZPhvfoDYSSDb18V6HsapnJik
            Utxe/V5tUtMBhhNPYvkMB2zyAhcdHGkEQYQxJUQNuh/uYzBT3qpMPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:44:17Z"
    mac: ENC[AES256_GCM,data:vkYSZSfanMcI0OJ5c0irRVyfwAY/bebixHl01m4ffBlRWqF0ih2F3L/N8oN3+qbIh/3dvxk9rCSYyD6lYQlyduq+xFc6x2dayeZySb0NLJ+rc12JfgRwnM8habTvoCYAygG5LXyCNLOIjrRLqW7MtHCwvtu1u9HBTgcd4DoSNoM=,iv:MWO0HVTebzzLhFdC5Q+5aoEc8A20kr/orsZ86i2a+A0=,tag:+tR4GY8Qun14I+mUq3ye4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: reolink-secrets
type: Opaque
stringData:
    RL_BACKDOOR: ENC[AES256_GCM,data:yXaAEiRA7oWfisO8,iv:AmI3rNNg/LLGyuc5w0fBJx4X5pr0y4wkGFojfOeEGoM=,tag:hGjcpRLFMdhdwaEquqR/CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dG5oTEFMSk92REluRTJV
            Z0tLSTFIWFJvUVJUU0k2MW1lbDI0NkdySEgwClJLcE9PZUp2UndaTWZDd3YvUTEx
            bmRDU1lZR0lqbDF5OTE4SFpmU3U2UjQKLS0tIDNJQldJbjlsTUxwR1FoQm84T0Y3
            V3dUSGRhQXhPNEJyVXhVQlZkUEIvT3MK9kaZiB4JZPhvfoDYSSDb18V6HsapnJik
            Utxe/V5tUtMBhhNPYvkMB2zyAhcdHGkEQYQxJUQNuh/uYzBT3qpMPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:44:17Z"
    mac: ENC[AES256_GCM,data:vkYSZSfanMcI0OJ5c0irRVyfwAY/bebixHl01m4ffBlRWqF0ih2F3L/N8oN3+qbIh/3dvxk9rCSYyD6lYQlyduq+xFc6x2dayeZySb0NLJ+rc12JfgRwnM8habTvoCYAygG5LXyCNLOIjrRLqW7MtHCwvtu1u9HBTgcd4DoSNoM=,iv:MWO0HVTebzzLhFdC5Q+5aoEc8A20kr/orsZ86i2a+A0=,tag:+tR4GY8Qun14I+mUq3ye4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: siyuan-secrets
type: Opaque
stringData:
    AUTH_CODE: ENC[AES256_GCM,data:FdbQWJR16KpaS6VCkm2MhWL6P7I=,iv:bBNVDTP3UwAW8ac6xpop5ZhFR0hY8lWA/1vDfCghsf8=,tag:ZOVm77iEGhs+MeeYEbny2w==,type:str]
    SIYUAN_URL: ENC[AES256_GCM,data:rOufdQdyGrIpG1iDZT5Qgt/M8VhoIdH6nn1rYDo=,iv:vp2LgXsuI9OKZa+8vsriOcy99uxaG3IrJux/80hgB5U=,tag:h3RZVdbi9+1UGkxu4i9OHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dG5oTEFMSk92REluRTJV
            Z0tLSTFIWFJvUVJUU0k2MW1lbDI0NkdySEgwClJLcE9PZUp2UndaTWZDd3YvUTEx
            bmRDU1lZR0lqbDF5OTE4SFpmU3U2UjQKLS0tIDNJQldJbjlsTUxwR1FoQm84T0Y3
            V3dUSGRhQXhPNEJyVXhVQlZkUEIvT3MK9kaZiB4JZPhvfoDYSSDb18V6HsapnJik
            Utxe/V5tUtMBhhNPYvkMB2zyAhcdHGkEQYQxJUQNuh/uYzBT3qpMPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T02:44:17Z"
    mac: ENC[AES256_GCM,data:vkYSZSfanMcI0OJ5c0irRVyfwAY/bebixHl01m4ffBlRWqF0ih2F3L/N8oN3+qbIh/3dvxk9rCSYyD6lYQlyduq+xFc6x2dayeZySb0NLJ+rc12JfgRwnM8habTvoCYAygG5LXyCNLOIjrRLqW7MtHCwvtu1u9HBTgcd4DoSNoM=,iv:MWO0HVTebzzLhFdC5Q+5aoEc8A20kr/orsZ86i2a+A0=,tag:+tR4GY8Qun14I+mUq3ye4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
