apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:myjk,iv:xbrNGn+L3C2hXjoaXIIbKxbSlZyov2REwdmcbqlDprw=,tag:DX4ES4+VaGYLUNI8zTHMcg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:jrXWbZmU/XzPDNwgVilEo26b02FLag==,iv:E7qVtvzS/uU9x/p6BLnUf1szNjZwgn5iv+8q6UFntLo=,tag:vXxdHFpRDkLb2VvEFjq3BQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:JPhG,iv:6rbqxiKCpozsnwUCcr0XuF27ABPqP5m7CTjWiJ5YhBo=,tag:/m8IctI8BtHxwCi3adEb8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VitvWnJmQ0wrR3dsTjcy
              M1Jvd2VwL0JEUEMvS0w3dW4zRGFpRjh6SFRJCkIxVnJRZmlubitKbnk3R0E0K0ZW
              eUhyZElxVG5ySlZuREhBdGpMVjVuMlEKLS0tIDFSVGx6NWxuMktWTjlicW5kSzNk
              N0NKVUtxY1VsSTZ3bkxmRHMxeWxRYzgKeBynItuIE2BOxfIFPbHJefDLrYXsMy9H
              bn+3c0QjvokGKtf+k0FoJkVpVLXtGIslZD9SmK19FUZ+NBgptenZbg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:01Z"
    mac: ENC[AES256_GCM,data:sRhJxg1zWOVbT/nnhZMRzIB8zRwZKcKMVQlXkfuUAgFOuxrZ584C7JkK3XTi64Jwg2IYxzx8L+2jPE2DGUWzKZgxpl4o0f1aaDWcfmzC1Km2Op8iaWMi5KG7i8rENnnJpliXjvEvGWh0UQpTftP+X30a1Gkyqobg+J5Hm90QtHw=,iv:inrBiB/69vdLInOV2QNo6OckEMl3s/68yCa6jYPTsmE=,tag:dcL+HTARYLYjED0U7Smo7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:deZOVIYsrxplssnCrNOUaw4GeYzC8H3Q2DU6y9Hq53M=,iv:21Bv0Fb5cok64rTgsYSf1ZRR1KVj2Xz2xXZMokRUPEI=,tag:0shZNlhngPUgsKJL4vN/IQ==,type:str]
    N8N_URL: ENC[AES256_GCM,data:PMpSWrWEnDaXCP1z3bofGGUxX7U60B4zCqak8w==,iv:G2XwUnmqH343snp061lAbFfiKGf4D1/cWlszMLEmIFU=,tag:Ywo01mIsqUDjIre9Vh1ykg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VitvWnJmQ0wrR3dsTjcy
              M1Jvd2VwL0JEUEMvS0w3dW4zRGFpRjh6SFRJCkIxVnJRZmlubitKbnk3R0E0K0ZW
              eUhyZElxVG5ySlZuREhBdGpMVjVuMlEKLS0tIDFSVGx6NWxuMktWTjlicW5kSzNk
              N0NKVUtxY1VsSTZ3bkxmRHMxeWxRYzgKeBynItuIE2BOxfIFPbHJefDLrYXsMy9H
              bn+3c0QjvokGKtf+k0FoJkVpVLXtGIslZD9SmK19FUZ+NBgptenZbg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:01Z"
    mac: ENC[AES256_GCM,data:sRhJxg1zWOVbT/nnhZMRzIB8zRwZKcKMVQlXkfuUAgFOuxrZ584C7JkK3XTi64Jwg2IYxzx8L+2jPE2DGUWzKZgxpl4o0f1aaDWcfmzC1Km2Op8iaWMi5KG7i8rENnnJpliXjvEvGWh0UQpTftP+X30a1Gkyqobg+J5Hm90QtHw=,iv:inrBiB/69vdLInOV2QNo6OckEMl3s/68yCa6jYPTsmE=,tag:dcL+HTARYLYjED0U7Smo7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:rBN0uIN5pUWjR2CWO6cTSPN8f0RgkThCPbvDerogi2VbSqeKbR6+ZZKnfPfg0iBTwBp/cCYmJVVBr/hajxhslOoLNx2KPIgzBy2P/qQDNfBIGs8BWj/ZnQT7VxHTBK48jvDAFT+ejFHG53NJkDyUsVpgH8lnIbUlit8iQb2SiMf78EKZEuMwjwlwMgSBv5S6x/jTCQiN98XCvnRzMcnfGPSMdOUwijI13mA3v1Mg5ykhaULXO4OEtw==,iv:vl9O04G8fWqubhnaFzHaYTkwuPgA6mfwWZEiOtwh3uQ=,tag:JlbhqJ3xaAvszqHDW8R3CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VitvWnJmQ0wrR3dsTjcy
              M1Jvd2VwL0JEUEMvS0w3dW4zRGFpRjh6SFRJCkIxVnJRZmlubitKbnk3R0E0K0ZW
              eUhyZElxVG5ySlZuREhBdGpMVjVuMlEKLS0tIDFSVGx6NWxuMktWTjlicW5kSzNk
              N0NKVUtxY1VsSTZ3bkxmRHMxeWxRYzgKeBynItuIE2BOxfIFPbHJefDLrYXsMy9H
              bn+3c0QjvokGKtf+k0FoJkVpVLXtGIslZD9SmK19FUZ+NBgptenZbg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:01Z"
    mac: ENC[AES256_GCM,data:sRhJxg1zWOVbT/nnhZMRzIB8zRwZKcKMVQlXkfuUAgFOuxrZ584C7JkK3XTi64Jwg2IYxzx8L+2jPE2DGUWzKZgxpl4o0f1aaDWcfmzC1Km2Op8iaWMi5KG7i8rENnnJpliXjvEvGWh0UQpTftP+X30a1Gkyqobg+J5Hm90QtHw=,iv:inrBiB/69vdLInOV2QNo6OckEMl3s/68yCa6jYPTsmE=,tag:dcL+HTARYLYjED0U7Smo7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:ITNRpW+beM8T9SE/xulR1LJHhqJ5CAwTlgOhN6tFhEXcZw==,iv:E/nPCOTdhY4cY2NU1sHDfYFm/rXjBNJs/lAWrxVtJqk=,tag:8ukDIFAPVPPqxcxSqqtKZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VitvWnJmQ0wrR3dsTjcy
              M1Jvd2VwL0JEUEMvS0w3dW4zRGFpRjh6SFRJCkIxVnJRZmlubitKbnk3R0E0K0ZW
              eUhyZElxVG5ySlZuREhBdGpMVjVuMlEKLS0tIDFSVGx6NWxuMktWTjlicW5kSzNk
              N0NKVUtxY1VsSTZ3bkxmRHMxeWxRYzgKeBynItuIE2BOxfIFPbHJefDLrYXsMy9H
              bn+3c0QjvokGKtf+k0FoJkVpVLXtGIslZD9SmK19FUZ+NBgptenZbg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:01Z"
    mac: ENC[AES256_GCM,data:sRhJxg1zWOVbT/nnhZMRzIB8zRwZKcKMVQlXkfuUAgFOuxrZ584C7JkK3XTi64Jwg2IYxzx8L+2jPE2DGUWzKZgxpl4o0f1aaDWcfmzC1Km2Op8iaWMi5KG7i8rENnnJpliXjvEvGWh0UQpTftP+X30a1Gkyqobg+J5Hm90QtHw=,iv:inrBiB/69vdLInOV2QNo6OckEMl3s/68yCa6jYPTsmE=,tag:dcL+HTARYLYjED0U7Smo7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:66ArUACX9RWAzbfnSOUC6L5n2cNClEsooNuK,iv:I+xTh1RR3CF2YGmE2jtEPrq7ooRC9h8ofIUdJ3rztRo=,tag:u2bmO2C17gXMFQqeo3GlOA==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:8POq9oYeEHdrPzFXJe4FACWaFJ4WdiA4cTKstaOKegI=,iv:t7TX8rg1aB/pew/+lEIb+pUsV3YfLs1eCfgOr01GBGU=,tag:Q5yE+DZ4ix/gXDYGycolnA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:vkdlBV5KgpfbVOBlLUYGNk6Op3VPnAVSp2eEvOlCgfM=,iv:6UbAHD0ZyLI6t2lxd3zdQ1M6iX7lZdxIJxvc0Kn9bVM=,tag:F2ltCnLj4bWaEDPJoyR6OQ==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:bBCxc+zVY7xetqdlnRdzf+UutfLg5aAxsyVVoRss6Pw8+GMTPP0hvg68cNsglcwe4ql5XNIDqJMPtRBwxHXb48XLYfTtO8DqMMHgqHFnZjIPfUiIUeJdwjiOcKgUK0uULUXCTIOOhUvgAB8lshlDkoV3tRCx+WtDD8S13qN5VW/f1oV5YfjQR/KiARv/zeqvbnIr2R8KtHQKrASR7LfTYDkT0m43D0Vegolmyii8n5jSgvhlGEHveSvWeU69pfZAI11a//7b66QcIKkkjzRdbo9fbsiSknQdOzWkjPmKAfp5ZWczdR0R53wknRb3,iv:lBEwjMgamSiTfjOxOtGBtMFYpiMhjczZaaNrBDFXhzc=,tag:u8iMoC0mn/397YhnKuQfjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VitvWnJmQ0wrR3dsTjcy
              M1Jvd2VwL0JEUEMvS0w3dW4zRGFpRjh6SFRJCkIxVnJRZmlubitKbnk3R0E0K0ZW
              eUhyZElxVG5ySlZuREhBdGpMVjVuMlEKLS0tIDFSVGx6NWxuMktWTjlicW5kSzNk
              N0NKVUtxY1VsSTZ3bkxmRHMxeWxRYzgKeBynItuIE2BOxfIFPbHJefDLrYXsMy9H
              bn+3c0QjvokGKtf+k0FoJkVpVLXtGIslZD9SmK19FUZ+NBgptenZbg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:01Z"
    mac: ENC[AES256_GCM,data:sRhJxg1zWOVbT/nnhZMRzIB8zRwZKcKMVQlXkfuUAgFOuxrZ584C7JkK3XTi64Jwg2IYxzx8L+2jPE2DGUWzKZgxpl4o0f1aaDWcfmzC1Km2Op8iaWMi5KG7i8rENnnJpliXjvEvGWh0UQpTftP+X30a1Gkyqobg+J5Hm90QtHw=,iv:inrBiB/69vdLInOV2QNo6OckEMl3s/68yCa6jYPTsmE=,tag:dcL+HTARYLYjED0U7Smo7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:3qyT64BL1Q==,iv:QoWXoWzt68PlFBD/ffAbhLCepnki/7GXTO2r402usOo=,tag:7p6ygfrAhFNNPFUyaH9XkA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:SyjYcCtu7rlMuit56FX+Wxb2tDE=,iv:zDyHhol2klK0/xGfOE3Tv4u9orK/3SoHCqiPRDqoItE=,tag:jjOHsTR3oi8OeF7IjwYXKw==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:2MCC8po/Qtc0xgniWOc+ifOSaCEAz0T2eV1+sJ7ZRRn/TWHsEA==,iv:d2SPqLuL5E7PLU6DV34hdRFSjvz5w+KSjyyfioCS3qU=,tag:0Abo3u38mNqDI6lb82ZL5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VitvWnJmQ0wrR3dsTjcy
              M1Jvd2VwL0JEUEMvS0w3dW4zRGFpRjh6SFRJCkIxVnJRZmlubitKbnk3R0E0K0ZW
              eUhyZElxVG5ySlZuREhBdGpMVjVuMlEKLS0tIDFSVGx6NWxuMktWTjlicW5kSzNk
              N0NKVUtxY1VsSTZ3bkxmRHMxeWxRYzgKeBynItuIE2BOxfIFPbHJefDLrYXsMy9H
              bn+3c0QjvokGKtf+k0FoJkVpVLXtGIslZD9SmK19FUZ+NBgptenZbg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:01Z"
    mac: ENC[AES256_GCM,data:sRhJxg1zWOVbT/nnhZMRzIB8zRwZKcKMVQlXkfuUAgFOuxrZ584C7JkK3XTi64Jwg2IYxzx8L+2jPE2DGUWzKZgxpl4o0f1aaDWcfmzC1Km2Op8iaWMi5KG7i8rENnnJpliXjvEvGWh0UQpTftP+X30a1Gkyqobg+J5Hm90QtHw=,iv:inrBiB/69vdLInOV2QNo6OckEMl3s/68yCa6jYPTsmE=,tag:dcL+HTARYLYjED0U7Smo7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: freescout-secrets
    namespace: default
type: Opaque
stringData:
    FREESCOUT_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:YPCPRMuwEPjUmKGq6uzFbo7uNYw=,iv:c5ctddU3q6qouV5eZr4kojBcB5Z4Xm+ypD1xLon4a4Q=,tag:PDiqTQ9TF4ZPgcLXmdQwrg==,type:str]
    FREESCOUT_DB_PASSWORD: ENC[AES256_GCM,data:ohLBe488PKvH8LKn+JddH/BuuTk=,iv:KatBtYqpIg00jDJItTI3Sws+FnvAVPclVXp/w3pgDDE=,tag:rtOn5oE7EeJFOJm7kygzqw==,type:str]
    FREESCOUT_ADMIN_EMAIL: ENC[AES256_GCM,data:4fWmMxSu6iZoRbXOMpEpVgryzX0kwn4=,iv:fgTVNFd8JTeHcbwr7Kh6zpBdxkLPQ+UeWsre0eXbjQQ=,tag:K9N8ltFsW71KK3taHKSjyw==,type:str]
    FREESCOUT_ADMIN_PASSWORD: ENC[AES256_GCM,data:km2S6OXlx9Vz4w3aIa3YOyRJFuc=,iv:8aopIljOelQ/9NiueNJjKQafLsZ2sOgFKcCgU9eZLb8=,tag:PNWvGNkAzz8c4s86Mhg2fw==,type:str]
    FREESCOUT_SITE_URL: ENC[AES256_GCM,data:1Wna+PGQRSphrLelar//YkdlGZogtMkoUIpKfw==,iv:q4h171VV/aesKSOmW5eGz8tsuL8bN7oxDfnw0ZXVgiI=,tag:v4PwenoIi7oRsY2aIyOO4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VitvWnJmQ0wrR3dsTjcy
              M1Jvd2VwL0JEUEMvS0w3dW4zRGFpRjh6SFRJCkIxVnJRZmlubitKbnk3R0E0K0ZW
              eUhyZElxVG5ySlZuREhBdGpMVjVuMlEKLS0tIDFSVGx6NWxuMktWTjlicW5kSzNk
              N0NKVUtxY1VsSTZ3bkxmRHMxeWxRYzgKeBynItuIE2BOxfIFPbHJefDLrYXsMy9H
              bn+3c0QjvokGKtf+k0FoJkVpVLXtGIslZD9SmK19FUZ+NBgptenZbg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T04:04:01Z"
    mac: ENC[AES256_GCM,data:sRhJxg1zWOVbT/nnhZMRzIB8zRwZKcKMVQlXkfuUAgFOuxrZ584C7JkK3XTi64Jwg2IYxzx8L+2jPE2DGUWzKZgxpl4o0f1aaDWcfmzC1Km2Op8iaWMi5KG7i8rENnnJpliXjvEvGWh0UQpTftP+X30a1Gkyqobg+J5Hm90QtHw=,iv:inrBiB/69vdLInOV2QNo6OckEMl3s/68yCa6jYPTsmE=,tag:dcL+HTARYLYjED0U7Smo7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
