apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:k0oh,iv:wccxi6nwusHMv2fbiZClN7oT+sCR4vOPPrIrF5EGLLE=,tag:ROkFie+HQpNvg1kZhmzI2w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ruJ6kH+0541MwIZKG93EFlp0I7O/rg==,iv:0e72e9ClD5/6eMRPL3ReFQ5wscK04wYKek50dxx90zs=,tag:Z67K8y5ZjPl7f1Fh755xMw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:oRv1,iv:AnZQdP4gWypVFalkY93p3EMCZTS/ndPybcezkfQimp4=,tag:yP7CiN9bNuHIJHWLSaAWjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:D9t/jtf7XQOIinUPoz9CjDD+2Lx+WboSTbSVBbmYxs8=,iv:pGTFWWCJeY80vgPmkqvsKivzGKe1Xl1f0/KPEN8Lg+U=,tag:zjWQqMnJ2huJJxtqEemsSg==,type:str]
    N8N_URL: ENC[AES256_GCM,data:2M4Q+ZsRQyBWOnMnKDv7baSirXyzIY35cIS5Kw==,iv:CmTF3AgbpebJyqBAEtkNMjgkvtmVP2PsPZwlACPOaU0=,tag:reNKICsDAnnPOU/mJoqg5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:8LM+EaUK81iDmgmpXiwLvA0Mx68rw8pdJphSgauG5FaCy3ejba7uv8rHacmR8dr9sXnlUHewoS7b8nJQdCvYbqPpaXOLrYZ9CjB+g8nzLtSsoh0ydYdHFT7dzbALuB09FM26DkUl0iAfromuuDkRw7vu2khLzDLbJQFckMPjU2dGX+anwtarxY7NQhpp7+JJXyaNHLOKe2lEDzSWp8Vem2i9uAeGfY1cE6DR26uYDdKJQ8LmeDZTew==,iv:cQvVwxtMqP9WJHOShZjWZmuucTtbOQO2T4ZymG7sgHM=,tag:zPGxMUQytB3RIyg/4qJREQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:jZK0DdOH6YWUNy14rhleswA2XctG1a9g0/x+,iv:d6b9dDEdAjNazYeYRMXeDxTplUtMvsSrCcwZEN8StIs=,tag:tiZvQyLuzBzjnkwp1IrqMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:YaxtLTE4H583ozFyFQReV7skua6gqVCs/mqd,iv:0xsbjJ2hZvofLrvH6VuzRn+AC6QbDEf9jvlqm3PKS2E=,tag:2XlgBtIZ5cAkU9nN5at41A==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:CEn4SlgAP10+UQmGF+f64wpM7JQ6oMj7yFgY2UjsQPM=,iv:fUe6ys3ropNI2j5Mmz/2pD88tPWXmwhTSbwJ4asuk5k=,tag:p6i4IZloXBDDxYMB0XUmMQ==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:BAuJK7g8+wJea2Bt2wHStTzvdrq8nOZ6+sWJ2MylyMA=,iv:EiGAtZ0+W3EPr9m46pA4EsEutwhwtymxWoLZvxg1Qoo=,tag:WFis95l1jNrA/Kv3w79Z1w==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:4YGwgHB6n1QC+c/HFm2XM6eDu2aymvwZQdMd97gHS2J3KnZqq6eCuJtykHeiquj2j8OF2IX8YqMCcqSRVcl85PsjJ2Tgd97Az7dt4YK9hvsLh4bImEV5wMARvA1MJJaBIfSJvG+93vHej/E0DSZBrXp+6I7fkDNmIEqxcc+eu1w5v/Zj2oy5GkbQikPzupEaJ5eJ5RqhQu60aOsnfGwv3IgrlUcPpdhdEJgtmK66a3XGI1246UvzJQVLF4l1Kut6o3UdKZlRudH5iYdhgzKzR75MJTSDpAqa9mYWYqYGyRk6ji/BlF7IE4reGgj3,iv:GWQJyA3WoVftDd6aXA5/ClePNN2KZRhSowAJdUshBuw=,tag:/19vTH2rK0rADpYC/uZk7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:F+Sb+m5EeQ==,iv:uL6lrd0lsU75TbqxQ/NFjqIeiuY9PO+cKymg7lRDY0A=,tag:FZyZ1MbFOZworRqXJm5MTQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:cXGFQNBhMVckM/H1TLCwydMMxcA=,iv:cWe4IKcEoQRyVbBpnxg1c4m12hq6P6C0DgoS0cF2ESE=,tag:gtld6v5XhhhWZbZHeeIb5g==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:p37yZjyI9ei/iuUuyJ0qgeZAptt5rPE92D7rXYwYU5wuosU3pg==,iv:zG95G2eAaXTkDzEEpiWkLRuag/eYBzGph54jtgUKCx8=,tag:Rw5crdfukD8k3S7/Jz2wPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:TpYH5RnrldziOaU0jrSyv9rM0ReDQV35QUijlJnTJtmHgM0H7TJO2koeY0o=,iv:uTiJpiRZnUWxiBIR1R/GEW8bj/9cYuV4gyy8443xQNk=,tag:e9C7it6R0G2IskNQbucVFg==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:0HqRMkCTgYNHMmy9wL4FcLgf9QE2RzVJEGRH,iv:QHrl8sI3Xqtb5csuS/l4BrCHD0FAhRQV/14JCccUfqs=,tag:GXC0gXcIjp6CdCcpVAx4GA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: default
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:TzV0BlaHpP00Q1l2bR6ihcrYxamIZ5v5kJmTY9uad0joU8B0sZ3WJw==,iv:lFJrLTPWDqVcP8fksjzuV9C4e9C0bm7E0gPFgKYVsqs=,tag:So53V2QrpkoPq3fhfhNquA==,type:str]
    RENOVATE_GITHUB_TOKEN: ENC[AES256_GCM,data:Kk8aNzcupIfux9Ptk1Roff2jEya0O2QxM8vVaEwbesGWfJBeN4t55g==,iv:fDIExZ4h3PyXONWzTaVB3wj9F4q5eKjJj7Enpui54cI=,tag:Gwff90adrEXz8aWXtS9wgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-secrets
    namespace: default
type: Opaque
stringData:
    JELLYFIN_KEY: ENC[AES256_GCM,data:008w9T1AfP4+1X7kKrhrqiynM2SJTqd9M/0vK5J24zI=,iv:18etoFBbvhEGJkwPeCxKSplmfBEuFxQ5j+pZeI1PNps=,tag:TL6cFRIYTqwZzMoOHtkp2g==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:6j6DREWxMYxbnkDsUlj/rNfK4Oe/akp/6U4=,iv:mxKsIh5+1L37aUo2QLwB97Nj+RGAacIne+biF8SYxFA=,tag:+2bRtqzX7WE6gaNLlKWQyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-secrets
    namespace: default
type: Opaque
stringData:
    HA_TOKEN: ENC[AES256_GCM,data:gGLUuBHRzd9AnjPKdhzm6jAdj9A5vfvZAB3TcrPAItP9MPLN8ZL0B1oNoEKhLLf96zu9SBQj2WiACD5tgfXLRPultaMZeHVTDp2FUt2GJzrJ4kQ515JDmFfEfkONJw+9ciA+Hm7s2I/Uux5BUI282tTSGGmJCR+0RhEzBxer6Q5zlFxD4h5LEnwdvoBMPNEKuyvDmxbSnH7TZwRxiQX38gVhcvN+cUCB0ZvGiy0WLhACGxIJjw3u,iv:1BEVJAF54G+KHXehOGWK9eeFX3pQkMYhCqFXl9PhOZI=,tag:tIdjaJWMcLecr6RYVJCByA==,type:str]
    HA_IP: ENC[AES256_GCM,data:pJ7BttcVsDV/ujIdY1aTGYMv4Fiqcz+nNOM=,iv:ls0K2r5lRTao8+6BEngxWrjXjbLeNWwz2WBpGixyzYA=,tag:TCifV59Xp46IBtJ5a8xPvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: dograh-secrets
    namespace: automation
stringData:
    #ENC[AES256_GCM,data:8SAt3x5WOOc3j9NgXM5mrle5Ac9JoTSg,iv:xlO86SAIKgrbdd8S4dnaldtbYPC/4Ot9f1IRh8m4igw=,tag:J30vWZhJUewlbR9LdKtbpg==,type:comment]
    GOOGLE_API_KEY: ENC[AES256_GCM,data:5WoCGAPs/8kIEiwh2dZGAc3cZTO9ee1YTkhkmXDCUPDho0I+cae9,iv:uIE5AfHOqR7aV/4FOAoIKMOoyTG/sEpgxlQ0lUYZ7Wk=,tag:OwwB6AsBpnwiix8/YbeeMw==,type:str]
    #ENC[AES256_GCM,data:c4n1AV3KCO+DT3MG8LwjY+QjIT1ROBIeBj6/6XmOQvnkIEZPgPirR/IkM7mz/16vl2YiC6DP2oAqCBgwLRAF,iv:Xx0/hPYjOcGLBPoHamush4y25ynHAiz9M+IhpeK3zws=,tag:m4y88im5YRvbhS3k8NA8ZQ==,type:comment]
    #ENC[AES256_GCM,data:0tpwnrCoGvqRhQKLvETdyDBNOPuNuNsUjlp1If3L3eL/+UuvRNM=,iv:B+4iPhl/dfTNmSpMERQI1kinmCAPJ9ozEUAl5rmS3qI=,tag:vEygd1KQEmeA/s2drZk5dg==,type:comment]
    #ENC[AES256_GCM,data:W6no3TZyiNa91HYHLU9sSlWLpLPSydnzacLai5HhNQ==,iv:j0cxUevC7o6xZYrAf5HOLPkLkLzAguEydTIxPe4VCjM=,tag:svWeIucoLb7sPmH0YP90WQ==,type:comment]
    TWILIO_ACCOUNT_SID: ENC[AES256_GCM,data:iXtBSl3+qwVVzPd7Nt6ZXtWVcBm1nbiVqx+RyQ2Teyn2/w==,iv:8o5iTP2SCei1z1EEIfXI6kBThemb0nU7Zr1XBWUitFQ=,tag:bFUuNddIdmbvdUymq5iKZA==,type:str]
    TWILIO_AUTH_TOKEN: ENC[AES256_GCM,data:5psvPTNr8QCKJZoNK08icEVe0ZSVwy4W5aLeFhgSotg=,iv:lQX8CMPktemhDt1+naralReNkXhp0DH0KA5vXL6nyRw=,tag:9kahJZORRbhOjkYR6KCs3Q==,type:str]
    #ENC[AES256_GCM,data:+eg5odMxCgoioqXedUi1XhU3qmv83gSTfQ==,iv:6tH84W/1aFVE6kxxhit5G6ains09BIj8al7iiSjWAv4=,tag:L4y9F3TZBrQnlKgxUvxR4g==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:SfPWmXTZ+nelVUH8obJEMRw/,iv:DodCQ8s9bY6DcV8n2amd/iZz8p3c1PNidoDg+x9WQpY=,tag:bkqlM2W6SQh1MSyDQoz4rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjVlVU5LbktrV2F5aDZh
            VXVqZ21OanFza2daWUUvOE5kOWNOaWdrNWhFCndwaFN5UkhSWVZDcVhpTjBTcDFE
            eGQxa24yK3VJVGNsTUNPY2pwdnZJcFEKLS0tIEhCb0Vvc2xTUExkRUFUYWlxbEpY
            Q1MxekZqUGhqeWJlTGZvN1lKc1dpbVEKwNCRSGdZT2ixYLiMk8UPMealieDdyKsM
            QSKxBhvZvG+epeOpcOW8TTwDqH2NPqO2X8Kp/ZMj6+Kal4NdLBkmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:33:09Z"
    mac: ENC[AES256_GCM,data:LEWxKHl3vqjkhYRC7d6BEU8wot1eHSldkLCdX3bpTZBZT9JSw2fWpF6aIot3iHqsxlaBuNpWTzV0wFYvb+Sj2bB6KlpWtk0d2JvLxJso9j1RYCqIlj0YNX4hSz9X3sC+9lqi4Enzq5QdgKYOt/S77WcSXTwrHWjzAeaTL94/XtU=,iv:408XMxUOAH1nsTAZ//c+6z64EW/4fHLCJ06jFFzqVu0=,tag:sHn/vpSciL5x2SjTDjmsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
