apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:NXd2,iv:xYB1pKHZUR/oQytSw1MM+NahXpG8DKZ1O0AeRR/NoTo=,tag:e5PzUweY2202dNfgAaj1LA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:olkVPb7tEK/TQ7btmr3KYvmg44nGbg==,iv:aEqtNq355fC4edc/XisemEtO62sX36bn+8zGSdjuxwk=,tag:5ziDHs6+cG1n0q8FNhezDw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:pnAU,iv:7K5pjnuDp/THqnlfco/ShqWMugGTtpGmI+NiGBSHZbg=,tag:PQ2vvgNc6sf98NDZt0l4lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbVZna1gxaUtwOVZtT21p
            cHFxZ3VHcHVXdVZwQXdwRmtCaCtvUDZ0T0NzCjI3dXZNM3dqa2dGZjRUSHVKTld0
            OWtWdGROam1tN0RQb2VOWG5LczNNeFEKLS0tIDJKQmRhd0V4VVZSWkhtcll6TXVs
            OHBsd3dGYTlqbU9tK0JDWlRpQ2wxT1kKGe+bjmU5ggOrnxuYJxBvYs/6o6yVmm31
            QC+E7yYrQm3vh54zNQhGv+CUgmAxudoS1cjjiCJH9Ec0Mu8zXQ1+pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:07:48Z"
    mac: ENC[AES256_GCM,data:llilWhw2Mv4LyzQIMc/jTLsakxlnSg2brc7Y+0sNNUdz1TcSeBr3r4Q/N7GPenLAFd7x+0KduBG0HZ8cG4Hri14Sqf1efYb7EKAER36SOJRj48+LGOYXlUr3oANspwez0kYCru/KSKzmBgwfYsTpO7XZTQeMT9hRwuRxgYEkezI=,iv:qXgUvacPWWV9q0ZDQ86p70zblyPmhUMltpxcF/RvtT0=,tag:r9Sh3jJzg+wKmVRWp6ihyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:5OYeSs0zhRUzNVZ3x4BBJp9lSevVH2gNlA3eyeYLDZE=,iv:Fwc/TpZIMlFzEIhuwk3xd2aGub7cWc5aTeDijPCdBeM=,tag:uo+B/lZr61/kWBqiwxb4Tg==,type:str]
    N8N_URL: ENC[AES256_GCM,data:L38n5WOdlnmzc+zIKFCkAfGdD+EgeoY8No/Haw==,iv:pzCaR9hvhZNuoZ5qCOQ3JTKv9wzCnpuo5NqkNBl8aQo=,tag:3cz4ZQhG1bBYkmguzUeB6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbVZna1gxaUtwOVZtT21p
            cHFxZ3VHcHVXdVZwQXdwRmtCaCtvUDZ0T0NzCjI3dXZNM3dqa2dGZjRUSHVKTld0
            OWtWdGROam1tN0RQb2VOWG5LczNNeFEKLS0tIDJKQmRhd0V4VVZSWkhtcll6TXVs
            OHBsd3dGYTlqbU9tK0JDWlRpQ2wxT1kKGe+bjmU5ggOrnxuYJxBvYs/6o6yVmm31
            QC+E7yYrQm3vh54zNQhGv+CUgmAxudoS1cjjiCJH9Ec0Mu8zXQ1+pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:07:48Z"
    mac: ENC[AES256_GCM,data:llilWhw2Mv4LyzQIMc/jTLsakxlnSg2brc7Y+0sNNUdz1TcSeBr3r4Q/N7GPenLAFd7x+0KduBG0HZ8cG4Hri14Sqf1efYb7EKAER36SOJRj48+LGOYXlUr3oANspwez0kYCru/KSKzmBgwfYsTpO7XZTQeMT9hRwuRxgYEkezI=,iv:qXgUvacPWWV9q0ZDQ86p70zblyPmhUMltpxcF/RvtT0=,tag:r9Sh3jJzg+wKmVRWp6ihyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:RVNPZkAogrB3Fvjr6ijQRYMKkWjHMYVsZ6TfYpy3EaZ3w0zlLhTNOav/Lz8h2Wk8nlox3RmmzQzq39O8QjmFnz1Z7vZjGXG4MJJjjHGKbsy1XTKC7Oh6jNrTElmHBpMrezyyuB/LndIVaJIwSo+R8ByShGTQtuXFTA9upYuC74tth2pa5+6jjpoLohq068Mv1jUsc5T6RQEa1Kx9j7BDkli993vI8qJ5Lfavg7a+x2EP01+Z+viq4Q==,iv:lGccsBOE7viUPx4DqgPR0cdbYaTqdR2DybskSb8H4QU=,tag:u/1YwkKdm++HcvdiRn4svQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbVZna1gxaUtwOVZtT21p
            cHFxZ3VHcHVXdVZwQXdwRmtCaCtvUDZ0T0NzCjI3dXZNM3dqa2dGZjRUSHVKTld0
            OWtWdGROam1tN0RQb2VOWG5LczNNeFEKLS0tIDJKQmRhd0V4VVZSWkhtcll6TXVs
            OHBsd3dGYTlqbU9tK0JDWlRpQ2wxT1kKGe+bjmU5ggOrnxuYJxBvYs/6o6yVmm31
            QC+E7yYrQm3vh54zNQhGv+CUgmAxudoS1cjjiCJH9Ec0Mu8zXQ1+pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:07:48Z"
    mac: ENC[AES256_GCM,data:llilWhw2Mv4LyzQIMc/jTLsakxlnSg2brc7Y+0sNNUdz1TcSeBr3r4Q/N7GPenLAFd7x+0KduBG0HZ8cG4Hri14Sqf1efYb7EKAER36SOJRj48+LGOYXlUr3oANspwez0kYCru/KSKzmBgwfYsTpO7XZTQeMT9hRwuRxgYEkezI=,iv:qXgUvacPWWV9q0ZDQ86p70zblyPmhUMltpxcF/RvtT0=,tag:r9Sh3jJzg+wKmVRWp6ihyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:85jPRX3mU9GsacPG2J/UShNo9vhCcxPtQO+V96Kh3e5kDA==,iv:giieU8vo98Wnspi8d3mXHA4/hDbcoi6zKekBYdGe9a8=,tag:liFEmep4r9UzuPaybiEOxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbVZna1gxaUtwOVZtT21p
            cHFxZ3VHcHVXdVZwQXdwRmtCaCtvUDZ0T0NzCjI3dXZNM3dqa2dGZjRUSHVKTld0
            OWtWdGROam1tN0RQb2VOWG5LczNNeFEKLS0tIDJKQmRhd0V4VVZSWkhtcll6TXVs
            OHBsd3dGYTlqbU9tK0JDWlRpQ2wxT1kKGe+bjmU5ggOrnxuYJxBvYs/6o6yVmm31
            QC+E7yYrQm3vh54zNQhGv+CUgmAxudoS1cjjiCJH9Ec0Mu8zXQ1+pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:07:48Z"
    mac: ENC[AES256_GCM,data:llilWhw2Mv4LyzQIMc/jTLsakxlnSg2brc7Y+0sNNUdz1TcSeBr3r4Q/N7GPenLAFd7x+0KduBG0HZ8cG4Hri14Sqf1efYb7EKAER36SOJRj48+LGOYXlUr3oANspwez0kYCru/KSKzmBgwfYsTpO7XZTQeMT9hRwuRxgYEkezI=,iv:qXgUvacPWWV9q0ZDQ86p70zblyPmhUMltpxcF/RvtT0=,tag:r9Sh3jJzg+wKmVRWp6ihyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:pxfTl9P2/i8DLOj7FtCcVk1DivarShKW5Hyh,iv:0rg2eoK4xHiLjDMdLx9H/PS+ap3XkD5G4E9Bq0MESZA=,tag:0LjQ/XDlInVNh6fEvyKNOw==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:PqFdev65F4KoLaeTJ0pMkL9NpQlY2h01cJ16UZcJ9Es=,iv:aKHQe2ruIzFYyMm6T8sOpNP7TNg2m+plwo0VNIjBUZ4=,tag:90N22sGXj8pLo4L/O8wHYA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:x+QGNJFL0gBX6Ee/C9BlwsaM5DmJdcRVXumSC0f0SIk=,iv:gaARVx2pxn7JTg3oVmiUhmKStUtClH/18zULwy/M6xE=,tag:NF0zHpTq3LPliY2+tq1IBw==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:YI4YlM0MQSlXagGeikiCox8aCDsiiUARcgARLRHnaPoDqWxnR0USgTEgKC0tMC51bKWERz0pdCZICP7R2skJs4RiowbJgMSWnnO8JHj43RxiJWO0NTKnMgT4hPR8CIOvGtWA/+rSgvtT4/0cToIrNXmsVOldBW3QGhcQZ0cVR6HEo7lReD88ZlTrgWR8OXzQ5i577vSd15Z1UGrIpvORPQwdETMwo2zKgIZmT7XRFds94V80dPniQV5ztIcV9asKsbIY2Jg6+3bRXiBqYltK7+ZzFmqLf8strwEdzxffJuLe5ChLmdK66dFye5D7,iv:on/Bp2RtZnC+LvfoqgcAZZfdRqoO+0vrvr5Z4riMvEc=,tag:RaI3zZMYgPEBECi39Gqk7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbVZna1gxaUtwOVZtT21p
            cHFxZ3VHcHVXdVZwQXdwRmtCaCtvUDZ0T0NzCjI3dXZNM3dqa2dGZjRUSHVKTld0
            OWtWdGROam1tN0RQb2VOWG5LczNNeFEKLS0tIDJKQmRhd0V4VVZSWkhtcll6TXVs
            OHBsd3dGYTlqbU9tK0JDWlRpQ2wxT1kKGe+bjmU5ggOrnxuYJxBvYs/6o6yVmm31
            QC+E7yYrQm3vh54zNQhGv+CUgmAxudoS1cjjiCJH9Ec0Mu8zXQ1+pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:07:48Z"
    mac: ENC[AES256_GCM,data:llilWhw2Mv4LyzQIMc/jTLsakxlnSg2brc7Y+0sNNUdz1TcSeBr3r4Q/N7GPenLAFd7x+0KduBG0HZ8cG4Hri14Sqf1efYb7EKAER36SOJRj48+LGOYXlUr3oANspwez0kYCru/KSKzmBgwfYsTpO7XZTQeMT9hRwuRxgYEkezI=,iv:qXgUvacPWWV9q0ZDQ86p70zblyPmhUMltpxcF/RvtT0=,tag:r9Sh3jJzg+wKmVRWp6ihyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:RTqKA9m4Hg==,iv:r2Vtuhng76N2yzEmTsNipx0b4DWpvWHDo0r49KGohAA=,tag:87Ndj4/6Rusf9wPlWk2Fng==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:4boKCShiHVsAu/O5s6icb4o091M=,iv:Pe7az6ivfEdeGg5TvwNTMXQRZi5z12u35/AmYBLVZq4=,tag:8RaQ3Fmr+cUcfFCHQh7yrw==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:uxknZaEZVHSxlNlCB8lXkiCXHJRqUfI4ILFHXym98UM899PgOg==,iv:diogtDr2sUsNV7My/TEkh0ApXYf4BcbBb2QhJ+iSiBk=,tag:Va4oVmMDF7iUc3l9D4yjeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbVZna1gxaUtwOVZtT21p
            cHFxZ3VHcHVXdVZwQXdwRmtCaCtvUDZ0T0NzCjI3dXZNM3dqa2dGZjRUSHVKTld0
            OWtWdGROam1tN0RQb2VOWG5LczNNeFEKLS0tIDJKQmRhd0V4VVZSWkhtcll6TXVs
            OHBsd3dGYTlqbU9tK0JDWlRpQ2wxT1kKGe+bjmU5ggOrnxuYJxBvYs/6o6yVmm31
            QC+E7yYrQm3vh54zNQhGv+CUgmAxudoS1cjjiCJH9Ec0Mu8zXQ1+pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:07:48Z"
    mac: ENC[AES256_GCM,data:llilWhw2Mv4LyzQIMc/jTLsakxlnSg2brc7Y+0sNNUdz1TcSeBr3r4Q/N7GPenLAFd7x+0KduBG0HZ8cG4Hri14Sqf1efYb7EKAER36SOJRj48+LGOYXlUr3oANspwez0kYCru/KSKzmBgwfYsTpO7XZTQeMT9hRwuRxgYEkezI=,iv:qXgUvacPWWV9q0ZDQ86p70zblyPmhUMltpxcF/RvtT0=,tag:r9Sh3jJzg+wKmVRWp6ihyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
