apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:rQ29,iv:EkDW/ZRUkoYnHsif6jsgOSaLmYoCXSms+eopv3UszyI=,tag:wLVpHCASAc4JMw33AXMWzA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PNs+qnPOr+Jak6WUWr7qpbN8RP1SZg==,iv:HhqlcGesuvU4oXihKKwhKvRX6nxGl2+kpcS2qdGfPOI=,tag:lGhQsEOXE0vkFus/imJBVg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:wt6g,iv:Lkb7/g5rmD2Dc7bNMldQv/u8hrKprtnXuhyM3x6g1FQ=,tag:5w7NkOHQx2UGebj1i/8BfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:6DSktSGcnPYZXzVCrVGRl1pn2zJZlTVpJI3SaPkyvrk=,iv:Hb31XaUXCnS4Yi6jaAK8BMtvIaUExqt0hX2bvBrXGUA=,tag:4nSEELGrSg/DOMQ6f8rRZg==,type:str]
    N8N_URL: ENC[AES256_GCM,data:Cz5BW4hERp0Kcc2GgohPgHVzaEhVrkahQ1af0w==,iv:XpPf2T2S65nGXsfufNGp2zQE7AeEKa7N4ICxnzW2Xoc=,tag:uEm8sHNGwpylrNCQTB+i4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:IbdsACZ8RDd45CRJ5NnoEBr8o+M1+g7JMHvtBpJqj9RU7klaOV8DuzPdWxZVFbigvhXw9lPGa4fnhoC1b7mC5nVMRU2+nh6k3o1H4jdm7KwfvByTanjQiIYI6A5cYm3VXjdbldUsxUdIuwckZIU1NGdACGFS9ytHZoQSZ7SZmPYYmrN64f9nphCb0f++BbumBAiUc5YRozI3MGTS+azwaECn/RqvfvN1BYx8uU7OGUlkzCjXtIZawA==,iv:d7D2MUcrl1u1XSQkRhP0aS6p5TM9aAP/opLTEurO7e4=,tag:M6G51JszgjCpKKNPubJKwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:qASH5mVw6Wt4383aW1Pggn4Bch9NwO6AIO74,iv:JyW99j54kuviA+AEnYElufy9VGjc97VX8cvqmu+S1NU=,tag:5x47Qw7omTEy5XGiZP4/6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:lOJYa+QUMl2cKUrYiAqN2DHL7nAgydoafpQk,iv:Dioe1CPtuSq8v6AhBDvZdsWkDl0T7MhAG5XSp+iB1X8=,tag:0NThktYLt/w5EqI8rT/8hQ==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:JPUPBcy5l/xkKkYWmtd5oYPt3hyDPGHqJWvfZGnJZm8=,iv:8cMhB6xoHhR8wMplqU8VeD8lW41oYv57L3uAsFarEnE=,tag:GszEqXyEdJIq4P0qRvRyxQ==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:IymL1oBSycGAMsriH4QvfdqYwRfhPxrhuaCIDrFcTMw=,iv:IAKGmeaxv/gO5Q/40gvnX6hDJDvAB36ge1PIflt7kSs=,tag:ixzcNc5Ndn6igkNoBE2q9Q==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:NhS6RFcCqXUHd/XQgliFiAeAonthrnCWGj3nQsAmw23l7ZyTuOXNlayOkyvbVlQH0fMn0sWXeBECUaRTup3K6FONRhfakNi0EMLrXG0R5PGv2ZEbAkiLVQmnW/LtRORLzCSR7eow4QN6rJstrnztBE58YVNb9pi6su+zt6ZsEvXV4lalaaFfVDcDV897cPdMC5z0f7NNKZnWYPqhYn0SzzXGkcWZu3cPjOSfYppQgVenUy+4jNKmI7RJIu5SkUBhkB8hXKi1hiGNe+Vlq94YDS3RxM7A15m8ChDdoSLlioS0ZlPbmSaZB8MFVieS,iv:mFmFFVP0uXkkrtWv3lZFg+WqJNX1mawltBBOfoWLYb8=,tag:Cn5nvIBF7hUCx8FQO+HpYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:itmaEC0tkA==,iv:UMFlYvM6pgOaJijWnahUnh/bwLj+v4LAF32oXlWxtc0=,tag:C/4P8TbjEjQPCrY8KgdvvA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:65AKGn+//1FSF7Htd81xDwl/jy4=,iv:xI6M5EZlB1dowdNQ8ngA1mz1WxwVJXN21L5s8vTzsyo=,tag:gV89yjRFLcOlB9Ez3Z7X8g==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:YEnFQGjBmeKzZaDnhBmwFdmCdTiB39Z1LAIez6VbT/72wYczbw==,iv:68O519K5HH20UMN7YCL07xMTSaehAdHTUyZuW80J3WA=,tag:yodTo298Q/cIrvVDhZ4Eow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:qSpmnsp2tUb59y5z1XdIVqith+8vDLJ/DGE8qg/RdivOImw4svn6vW9tcLE=,iv:q9ugGyHKYCeZhgmCU1YNtSwQzxdY8TaTf0U5JIGEKZE=,tag:ec4n6Qfcck+FWj+ru0lMqA==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:Rc+A9x9WeC2uhP2g6DmWvqKQXZh3Ok0Gwtlc,iv:EcEz3C2rAXowvZhZz5+cfQbxyOS8A6x8pJhvN8Numa0=,tag:vIyuqe+TGJvx8U1ZWDRCEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: default
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:WRlVRJINPREzGwtl8PqVcUopp0UDmNJeKWlQCeRfrVVF+1hi0kZIIw==,iv:j7p0QWF9PX1+O3f3ZC4tW2pOpZe/K5z/+0dSFIuR4YY=,tag:RY9mvqYcxjzuKqStGbsbHQ==,type:str]
    RENOVATE_GITHUB_TOKEN: ENC[AES256_GCM,data:oAprnyukrvW/lRRju1Ji5bEDMVkjYIotJHZlHboSisM13u6M5vFmZQ==,iv:7LOcw54LsD5VelDxNQElQU9uxDQAwBRpV6o0f1jL36k=,tag:Nhdi/9CFbL0MwqcAUUDpUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-secrets
    namespace: default
type: Opaque
stringData:
    JELLYFIN_KEY: ENC[AES256_GCM,data:w/IVZ2oSJ5eu3lbb9xozHRuwhJ7MbFyceYmvnesuM1M=,iv:S3BgoDdpa0K20C2oIXI46hsfMEZ7uSmcxav3HvIAa8E=,tag:FQhYQbgneqiuSZbh5GR/5g==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:PwlnhWdgn1OwZiXwwVoVZL112FXekY4lA08=,iv:a6CefHzRlfaGagXaQAjBTH6d+tUupFagKj+xwcWPpFw=,tag:C6jCw7OY0XJe4YPe/mep+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-secrets
    namespace: default
type: Opaque
stringData:
    HA_TOKEN: ENC[AES256_GCM,data:vlI02wg3vSfFVXsTUuIOdlOMUC+z3d2V7PnAWxbCjFrcIDaE7OWWKuyiSO00S07uQMvmMJo7e92DC3xDFQVIwqW58tBMNOVzI7cb65yMLNByNJ8pzYXQ3NeGpvEwjbcRiofeuQTJieyTaIKL5z1HgVtxyoP4ebxQwe7fnDWq6+Dn+FvM8kEeT1zV8RraRR7xPJq4bAdlGvSe+4YJIltze6ef9kBaI8xL4adpcFcy6HrVAOnvsAwu,iv:nrVNHkVLrKQ3BEzyt4xyhnpq8KEIgVajSclKH/f5VmI=,tag:vvMMbf5tpTeHDS0+XjxuPw==,type:str]
    HA_IP: ENC[AES256_GCM,data:PWMk1MSbC9MMtrnK1DVBEtFkX27FNqxuHSE=,iv:ciDbyQXM6rqmhbPgz+lR0MMCSba199Zpz92ItEgc8cg=,tag:ZL4VhczFxCKHOiI7NAjUTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: dograh-secrets
    namespace: default
stringData:
    #ENC[AES256_GCM,data:CmEMKuK9AYtfvjAKLVtJzTgIvIasEMDq,iv:Zy1p1Nseyjp6BvINmIgJGxspOtwcF+uaDapxbngrUow=,tag:rBwHnFef5gBMgJgwNS992A==,type:comment]
    GOOGLE_API_KEY: ENC[AES256_GCM,data:sBiooZ6NoSXPW3p7nx3Oa2PK15D1YrG4pbKcw4gYTkkRdtWOK156,iv:9bFars1/SiYQMvJgBEb9AnMmwxjQGICKgNpoiMfcbuU=,tag:/RPyYaIDX8h/P08L4ez7SQ==,type:str]
    #ENC[AES256_GCM,data:LZy8myoJf4jSPyIB1L0bcPL5LhIaRS4zVIfhFPOTlIc92h6VMCkuUeKem6lZjt9bYeVu+TQ58gmI+iXAGK32,iv:Lvwa6F6XBYlsH4HDLvEgVXwBFunHHNKH9VpFK2Y+m4w=,tag:3mY8JMrNuzRogVThTOlCdg==,type:comment]
    #ENC[AES256_GCM,data:gij+bJcqNHW6MNp5swWkSfxNhYICgS1uFuspND79BjdRQXXQX8A=,iv:rFMX0QKLNQVnyrANJOtsDzL6E8/J2lZobv5EMBj6xfw=,tag:eP9qG1Rh5pqzj0xI8kmstg==,type:comment]
    #ENC[AES256_GCM,data:ceZC8UUGvGThlmk78MRiH/rqK4DETRQA1glYQYgJQg==,iv:0EFDP5PQuqtLWUPcrsm4Q1Zn3Imqtq/bBWZXa6zrDc4=,tag:vFHfDC7NeUmXvgqSAAQyJg==,type:comment]
    TWILIO_ACCOUNT_SID: ENC[AES256_GCM,data:Q9d3mD1lszt5lKZ0kb8ObOhnppxMYl92NHQV04kFVX4UqA==,iv:giNlN4F9RRgClhPSEXRVMEjuE6qDjdeSjeM2XdHUWqY=,tag:Rs3RI1njX3rLHkXPGSrdHQ==,type:str]
    TWILIO_AUTH_TOKEN: ENC[AES256_GCM,data:+YVPLR9gR+Y3UVT4HWSVzqSjJWwXwPpZG2iXYg6kH9A=,iv:i/+Ws//uiXAfXNrBr3CB1rny56Km/oW4jOCXT1O+ni4=,tag:i0AYRt31Z+W8S/nsK7IClg==,type:str]
    #ENC[AES256_GCM,data:9DbVdqzKs50lk/r6kw75eD5xfXQL5A3QMQ==,iv:bGZFiJ2CXDCxYq9x6fDwd9Wm61B5W+JG/XCz+yxq6mY=,tag:35StjK/k3CphwBlDsvqoRg==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:0sv6G4HWK5TBtSZ3FSqW97UK,iv:+mqGrghRV/uUYuHwY1wNHLtl89rEXOVJYiWxNkhB9pU=,tag:M27H9b7RdNcOzf6ojXLZsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bnNZMVd6RGhLMVhkWXJ1
            cVpZU2s1NFhCK3lkY0l0U0R1NitKS3RkNVRBCjJQT0pDVnZLNDZBaXJLL0ZIZHR5
            dmFoblJiNVRhOXhMNlh2RWZXWlRodUEKLS0tIFNjdUh2d1U3dEJ2bjQ0Q0YrNW53
            RUVXQkhXdEREbDkwaE9PcFdTUWpUUlEKsDDjcDmOWFJHqnl5TO4uy1xzbqnZrn7z
            9jhcyVrqMmH8sz2fy1HMbO6JRC8q0bbGiS0MH/bTW8nN79x1YthMcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:42:17Z"
    mac: ENC[AES256_GCM,data:i/0zaaRculKQdktxXhDecn3aMxr9MZAMvCa1ZbdZtCZC8/K7MS2jeV9JKNbVT+Pk30EgYBDm1gH6iRpvsWrf2IPn8AUb3+mOUdHdiStCiSoaQFXz0PSoIN5a5jdFGfEPurWfr7h2WGscTbZ0l2XpZX6OF2CYq9saEw7em80KNt4=,iv:QHcaOD6YnB5noVyYeRCuPPrpAaG0NEoLL7uLrxrsuS4=,tag:w1mzOr5eoMQGbTeRb2z/xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
