apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:DQyC,iv:XHaG38rxP0n79RYahKUtOUhNch+NkpVOp/c2yYZXGYw=,tag:3AFSHb375/3tlpJgCLUw5w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:b2Idl+UWRhwB9Nx2HFaP8tY8kAC6oA==,iv:fFRh71lYifezwpMoxWY/KwOqcZSx4Ptm57Ufhq00wwE=,tag:1gMzBT805+CO0f/B/lFeEQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:qoDb,iv:mtXn5E6ithGCBGPOlvOurfGfqQlyfInoaWsIEUbmswQ=,tag:MuDFO1flzXEO1Qem3lM7xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVEVFTVMxUGZlQ0d5RDhS
            YVVkNEpiTjl6VlVqNW52Z0lnMmRiVWovZ0JjCjNjQ0JGK25TczN6UmxCZWt3cE5j
            ZlhCUjA0ZmZVYUlWSkh4ZVRPZ0ZGeE0KLS0tIHBsQnRMLzVuc1lnWGhOUGdxcjZp
            UmZNUE5waXJ5UkFJY0kzUGFLU2l4WnMK82wKX1knpQ87nmx7UXGQWe/RbiLRsdjQ
            4gkQt0FNIIEQy80e1wxzVW1Tft/8Zb5beOFO8mvobpzkoyljmQvjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T02:42:29Z"
    mac: ENC[AES256_GCM,data:n6IJHmaz+5R6NSXUONYV9xfOD1/8rGEq7tsWqSxa+PoLtkwEmy63qO2C3xO1TopNGGjizK1Eer+qzhzt7mNcf3pYjaTam5Mg1watA2Kt/PcELTil5YLkt7Ug/4oE5B1DvxLnj0v9L2h1Dui4ZcvkYaPeb+TMixMVQlh/cwQl4vQ=,iv:3Bm5G5JrwU8HHq3cT2j1d51F8JTGTeDC8AWZULm25E0=,tag:rz0Srw3vcK6X3V4F7DNFpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:fTJggsAgc4OcOY0B/xFEwMH9Nv9EZ3/ynDyeYiFRmGw=,iv:2+YzCgl0WfHaDy8EKHnQOPvlzaQtbphDzPk3DIWqCQg=,tag:wk/jrJz5fSz42PP7CpaUqQ==,type:str]
    N8N_URL: ENC[AES256_GCM,data:+1dUQnpT6Mff17ZIGzYPMQ6hsGsvT9EQC1G5Kw==,iv:W4s13z4ciNgl6up8wKev2ykOUr1Xpb0eTzQWgmORvYw=,tag:jAx5gkXb9Eaotl4w7fF82Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVEVFTVMxUGZlQ0d5RDhS
            YVVkNEpiTjl6VlVqNW52Z0lnMmRiVWovZ0JjCjNjQ0JGK25TczN6UmxCZWt3cE5j
            ZlhCUjA0ZmZVYUlWSkh4ZVRPZ0ZGeE0KLS0tIHBsQnRMLzVuc1lnWGhOUGdxcjZp
            UmZNUE5waXJ5UkFJY0kzUGFLU2l4WnMK82wKX1knpQ87nmx7UXGQWe/RbiLRsdjQ
            4gkQt0FNIIEQy80e1wxzVW1Tft/8Zb5beOFO8mvobpzkoyljmQvjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T02:42:29Z"
    mac: ENC[AES256_GCM,data:n6IJHmaz+5R6NSXUONYV9xfOD1/8rGEq7tsWqSxa+PoLtkwEmy63qO2C3xO1TopNGGjizK1Eer+qzhzt7mNcf3pYjaTam5Mg1watA2Kt/PcELTil5YLkt7Ug/4oE5B1DvxLnj0v9L2h1Dui4ZcvkYaPeb+TMixMVQlh/cwQl4vQ=,iv:3Bm5G5JrwU8HHq3cT2j1d51F8JTGTeDC8AWZULm25E0=,tag:rz0Srw3vcK6X3V4F7DNFpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:5CXv69lefxJO0WaJrk+rRWc83IGTXkNWtlgL8A0jmadFCwXDex6dQKoDiD6FCGu48GReKUHhQWCC6X2te26hviAr/Eg/qdfifVyx/JrrX4mHxZiUAZIz6leTUYqT3bDnCO0gFazmCEN8yh67zm2gxbe9ThXEw2wyYietql9PFSIUsW2l1iBd4SruP+mExFtnon7HQgV+O2SqCZqxyLrGDUxOTqJSGS616/f84fanShuV6taalHZ1GQ==,iv:ZmaF4f1dkp2GbOlzQl7+Q4q4E6/OZCkdPjKv5PqExt4=,tag:NG/x+u5uAW59K5O/i249gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVEVFTVMxUGZlQ0d5RDhS
            YVVkNEpiTjl6VlVqNW52Z0lnMmRiVWovZ0JjCjNjQ0JGK25TczN6UmxCZWt3cE5j
            ZlhCUjA0ZmZVYUlWSkh4ZVRPZ0ZGeE0KLS0tIHBsQnRMLzVuc1lnWGhOUGdxcjZp
            UmZNUE5waXJ5UkFJY0kzUGFLU2l4WnMK82wKX1knpQ87nmx7UXGQWe/RbiLRsdjQ
            4gkQt0FNIIEQy80e1wxzVW1Tft/8Zb5beOFO8mvobpzkoyljmQvjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T02:42:29Z"
    mac: ENC[AES256_GCM,data:n6IJHmaz+5R6NSXUONYV9xfOD1/8rGEq7tsWqSxa+PoLtkwEmy63qO2C3xO1TopNGGjizK1Eer+qzhzt7mNcf3pYjaTam5Mg1watA2Kt/PcELTil5YLkt7Ug/4oE5B1DvxLnj0v9L2h1Dui4ZcvkYaPeb+TMixMVQlh/cwQl4vQ=,iv:3Bm5G5JrwU8HHq3cT2j1d51F8JTGTeDC8AWZULm25E0=,tag:rz0Srw3vcK6X3V4F7DNFpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:zvE0LUtiu9ohhgVDS9c+5EIUjmp2V5HhHWGEv8VG2Q4jjA==,iv:mC7A0NwRcYI6eg8Ytlw8La84ZC/j+f/8k6AfQ1hgWEs=,tag:WL80f7wTeySdbV2pvruqTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVEVFTVMxUGZlQ0d5RDhS
            YVVkNEpiTjl6VlVqNW52Z0lnMmRiVWovZ0JjCjNjQ0JGK25TczN6UmxCZWt3cE5j
            ZlhCUjA0ZmZVYUlWSkh4ZVRPZ0ZGeE0KLS0tIHBsQnRMLzVuc1lnWGhOUGdxcjZp
            UmZNUE5waXJ5UkFJY0kzUGFLU2l4WnMK82wKX1knpQ87nmx7UXGQWe/RbiLRsdjQ
            4gkQt0FNIIEQy80e1wxzVW1Tft/8Zb5beOFO8mvobpzkoyljmQvjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T02:42:29Z"
    mac: ENC[AES256_GCM,data:n6IJHmaz+5R6NSXUONYV9xfOD1/8rGEq7tsWqSxa+PoLtkwEmy63qO2C3xO1TopNGGjizK1Eer+qzhzt7mNcf3pYjaTam5Mg1watA2Kt/PcELTil5YLkt7Ug/4oE5B1DvxLnj0v9L2h1Dui4ZcvkYaPeb+TMixMVQlh/cwQl4vQ=,iv:3Bm5G5JrwU8HHq3cT2j1d51F8JTGTeDC8AWZULm25E0=,tag:rz0Srw3vcK6X3V4F7DNFpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:W40mLTWttWBx2KN7v+nk5sPJEeEPbFIH0YFe,iv:ycDBrtVikzF2NhuZjoFIUTRit4LRH17ejdnVUGJl4+Q=,tag:8HvL5e/fXP6yfmQHYyPxMg==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:2aPMj+JYexy62aTBHpwvX07WMjI/IgDYtgnETv5o2gA=,iv:88jvDG6i6ojsfCCy7pe9c5HjDXWfgKoczT/GJpkgqtA=,tag:pU2WjprF/npJXJN9r4R3ug==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:zOnN1EpOcq2uQtln+E6gDADC5ih3AdCcmg3n09Kivdo=,iv:YcxULAK4y5rbzTa6gpnz/Jgzk3PMm9gwdhx1+wXx9os=,tag:dTYoqMW61OV1YgneX61dYA==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:046BpmAuMcg90PsByel0LDURgCuYro+fC25GgtOGM1nyCCJ+L8zKLEiiNmltZS76J6+ZdZ0NmCC0sj9aBDesD3v9/ZUkKRSNYyI8nDegzSyapN40FbjyuP+UM4VW76ssDet7+UgFgR4ls7LYepW77W4KRfl2wsUBT7Y/A6cr5ko9CRiN6aKdeIvway7/97a4oEPHOOndcDwnP1MiFwirkrE4q9vy+Hk6uhNalz+IudxwJAiS++hyLQ5v/pv+FMBLiPbpzGO/7NakPf2h04tTT6LdyRqiOTB0+6kfs/HNXpVM16/4BIQCIYQUlVOF,iv:oBisQdvPpj5jN+EF//EyqiY7AoqVUxpAJbwiabpsOo4=,tag:rLIolMjIfCzrqNBNLGMgsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVEVFTVMxUGZlQ0d5RDhS
            YVVkNEpiTjl6VlVqNW52Z0lnMmRiVWovZ0JjCjNjQ0JGK25TczN6UmxCZWt3cE5j
            ZlhCUjA0ZmZVYUlWSkh4ZVRPZ0ZGeE0KLS0tIHBsQnRMLzVuc1lnWGhOUGdxcjZp
            UmZNUE5waXJ5UkFJY0kzUGFLU2l4WnMK82wKX1knpQ87nmx7UXGQWe/RbiLRsdjQ
            4gkQt0FNIIEQy80e1wxzVW1Tft/8Zb5beOFO8mvobpzkoyljmQvjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T02:42:29Z"
    mac: ENC[AES256_GCM,data:n6IJHmaz+5R6NSXUONYV9xfOD1/8rGEq7tsWqSxa+PoLtkwEmy63qO2C3xO1TopNGGjizK1Eer+qzhzt7mNcf3pYjaTam5Mg1watA2Kt/PcELTil5YLkt7Ug/4oE5B1DvxLnj0v9L2h1Dui4ZcvkYaPeb+TMixMVQlh/cwQl4vQ=,iv:3Bm5G5JrwU8HHq3cT2j1d51F8JTGTeDC8AWZULm25E0=,tag:rz0Srw3vcK6X3V4F7DNFpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:dHz5bYbF6A==,iv:WjwkQsz8P64j943Dq+7GXLfJlKzZsyp4Ouwjs73e8mE=,tag:x/0DHiqv1cdLE9/zMPpu7g==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:+pgNz/EKjLg/TVMAgPsyEvq2UWo=,iv:O3En9iFGyrv6l9P8H3Mp6EaYYcEhSYKQ5j74KyRI6Ds=,tag:8Ck7QNVd50jovlt+G9qhSg==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:eptrChhU688EZM6o40pYDW+SM//vbR4piF/HQvDZ6FoBYkXTtQ==,iv:Z+2LGhbJ9rTN8H6Kdn/0NWIWbi+sG7mIXMaza7eP5bg=,tag:hqDPRce8/+GS4k6RfxeanQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVEVFTVMxUGZlQ0d5RDhS
            YVVkNEpiTjl6VlVqNW52Z0lnMmRiVWovZ0JjCjNjQ0JGK25TczN6UmxCZWt3cE5j
            ZlhCUjA0ZmZVYUlWSkh4ZVRPZ0ZGeE0KLS0tIHBsQnRMLzVuc1lnWGhOUGdxcjZp
            UmZNUE5waXJ5UkFJY0kzUGFLU2l4WnMK82wKX1knpQ87nmx7UXGQWe/RbiLRsdjQ
            4gkQt0FNIIEQy80e1wxzVW1Tft/8Zb5beOFO8mvobpzkoyljmQvjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T02:42:29Z"
    mac: ENC[AES256_GCM,data:n6IJHmaz+5R6NSXUONYV9xfOD1/8rGEq7tsWqSxa+PoLtkwEmy63qO2C3xO1TopNGGjizK1Eer+qzhzt7mNcf3pYjaTam5Mg1watA2Kt/PcELTil5YLkt7Ug/4oE5B1DvxLnj0v9L2h1Dui4ZcvkYaPeb+TMixMVQlh/cwQl4vQ=,iv:3Bm5G5JrwU8HHq3cT2j1d51F8JTGTeDC8AWZULm25E0=,tag:rz0Srw3vcK6X3V4F7DNFpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:NPpvg3aWrfZyvehYyIlovRYG6hApVPluWN0zg1LfFFdXEZTR42LDPlUmaDQ=,iv:nh0LZNhtJL4yYv8gqokqyT1aAFGjka6MszaNbHlhD5Y=,tag:qiZL66R+hymd0NvSvJulnA==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:b+3y5uMbx6eczyrRVW4SOHuNdHklqeUcBLxH,iv:yIpm/BAgXYS5rNAbqBs7tkGOdmZK7FpZX+/J/sWIG7U=,tag:IzcldiOhS+Y+Y4WwezU2lA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVEVFTVMxUGZlQ0d5RDhS
            YVVkNEpiTjl6VlVqNW52Z0lnMmRiVWovZ0JjCjNjQ0JGK25TczN6UmxCZWt3cE5j
            ZlhCUjA0ZmZVYUlWSkh4ZVRPZ0ZGeE0KLS0tIHBsQnRMLzVuc1lnWGhOUGdxcjZp
            UmZNUE5waXJ5UkFJY0kzUGFLU2l4WnMK82wKX1knpQ87nmx7UXGQWe/RbiLRsdjQ
            4gkQt0FNIIEQy80e1wxzVW1Tft/8Zb5beOFO8mvobpzkoyljmQvjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T02:42:29Z"
    mac: ENC[AES256_GCM,data:n6IJHmaz+5R6NSXUONYV9xfOD1/8rGEq7tsWqSxa+PoLtkwEmy63qO2C3xO1TopNGGjizK1Eer+qzhzt7mNcf3pYjaTam5Mg1watA2Kt/PcELTil5YLkt7Ug/4oE5B1DvxLnj0v9L2h1Dui4ZcvkYaPeb+TMixMVQlh/cwQl4vQ=,iv:3Bm5G5JrwU8HHq3cT2j1d51F8JTGTeDC8AWZULm25E0=,tag:rz0Srw3vcK6X3V4F7DNFpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: default
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:isOXtgi1rlqG/64GHuYKHUER8BDm/9P7lrDmBTPvo5HyIoa31aC6Fw==,iv:oQb7LTl8KbQ7YTk7wgpkQEpF1lK17B7ak3QIdsqTPFo=,tag:34+pPQYZ7pHaJUVaoM+OZA==,type:str]
    RENOVATE_GITHUB_TOKEN: ENC[AES256_GCM,data:03zqtabdM3uOuFi5M5J6Rfope6xe2qdUqk5IbrHinK1j74PdlqV6uA==,iv:vCzw0PaKL2yqNY2vvAggkkmjIcmfHQQ6KzM7NYcDKbw=,tag:aZ2As5khy6ksgCtH0teUBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVEVFTVMxUGZlQ0d5RDhS
            YVVkNEpiTjl6VlVqNW52Z0lnMmRiVWovZ0JjCjNjQ0JGK25TczN6UmxCZWt3cE5j
            ZlhCUjA0ZmZVYUlWSkh4ZVRPZ0ZGeE0KLS0tIHBsQnRMLzVuc1lnWGhOUGdxcjZp
            UmZNUE5waXJ5UkFJY0kzUGFLU2l4WnMK82wKX1knpQ87nmx7UXGQWe/RbiLRsdjQ
            4gkQt0FNIIEQy80e1wxzVW1Tft/8Zb5beOFO8mvobpzkoyljmQvjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T02:42:29Z"
    mac: ENC[AES256_GCM,data:n6IJHmaz+5R6NSXUONYV9xfOD1/8rGEq7tsWqSxa+PoLtkwEmy63qO2C3xO1TopNGGjizK1Eer+qzhzt7mNcf3pYjaTam5Mg1watA2Kt/PcELTil5YLkt7Ug/4oE5B1DvxLnj0v9L2h1Dui4ZcvkYaPeb+TMixMVQlh/cwQl4vQ=,iv:3Bm5G5JrwU8HHq3cT2j1d51F8JTGTeDC8AWZULm25E0=,tag:rz0Srw3vcK6X3V4F7DNFpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
